export const gradeTenMoreLessons = {
  math: [
    ["propositions", "Mệnh đề và phủ định", "Mệnh đề là câu khẳng định có tính đúng hoặc sai, không thể vừa đúng vừa sai. Phủ định của mệnh đề P kí hiệu là P̄, đúng khi P sai. Phủ định của “với mọi x, P(x)” là “tồn tại x sao cho P(x) sai”. Mệnh đề “nếu P thì Q” chỉ sai khi P đúng và Q sai.", "Phủ định của “Mọi số nguyên tố đều lẻ” là “Có số nguyên tố không lẻ” – đúng vì có số 2.", "Viết phủ định của mệnh đề “Mọi học sinh trong lớp đều thích Toán”."],
    ["law-of-cosines", "Hệ thức lượng: định lí côsin và định lí sin", "Định lí côsin: a² = b² + c² − 2bc·cos A, dùng khi biết hai cạnh và góc xen giữa. Định lí sin: a/sin A = b/sin B = c/sin C = 2R, với R là bán kính đường tròn ngoại tiếp. Hai định lí giúp giải tam giác bất kì, không chỉ tam giác vuông.", "b = 3, c = 4, A = 60° thì a² = 9 + 16 − 2·3·4·0,5 = 13, a = √13.", "Tính cạnh còn lại khi biết hai cạnh 5 và 7, góc xen giữa 120°."],
    ["data-measures", "Các số đặc trưng của mẫu số liệu", "Số trung bình, trung vị và mốt đo xu thế trung tâm. Khoảng biến thiên, phương sai và độ lệch chuẩn đo độ phân tán. Trung vị ít bị ảnh hưởng bởi giá trị bất thường hơn số trung bình. Độ lệch chuẩn là căn bậc hai của phương sai.", "Mẫu 2, 4, 4, 6, 9 có trung bình 5, trung vị 4, mốt 4, khoảng biến thiên 7.", "Thu thập điểm một bài kiểm tra của 7 bạn và tính trung bình, trung vị."],
  ],
  science: [
    ["work-power", "Công, công suất và bảo toàn năng lượng", "Công của lực A = F·s·cos α, đơn vị joule (J). Công suất P = A/t cho biết tốc độ thực hiện công, đơn vị watt (W). Khi bỏ qua ma sát, cơ năng (động năng cộng thế năng) của vật được bảo toàn.", "Kéo vật với lực 10 N đi 5 m cùng hướng lực thì công là 50 J; làm trong 10 s thì công suất là 5 W.", "Tính công khi xách cặp 30 N đi ngang 20 m (lực vuông góc chuyển động) và giải thích."],
    ["reaction-rate", "Tốc độ phản ứng và chất xúc tác", "Tốc độ phản ứng phụ thuộc nồng độ, nhiệt độ, diện tích bề mặt tiếp xúc và chất xúc tác. Chất xúc tác làm tăng tốc độ phản ứng nhưng không bị tiêu hao sau phản ứng. Enzyme là chất xúc tác sinh học trong cơ thể sống.", "Đá vôi dạng bột phản ứng với acid nhanh hơn dạng viên vì diện tích bề mặt lớn hơn.", "Giải thích vì sao bảo quản thực phẩm trong tủ lạnh giúp chậm hỏng."],
    ["cell-structure", "Tế bào nhân sơ và tế bào nhân thực", "Tế bào nhân sơ (như vi khuẩn) chưa có màng nhân, kích thước nhỏ. Tế bào nhân thực có nhân được bao bọc bởi màng và nhiều bào quan. Ti thể là nơi diễn ra hô hấp tế bào; lục lạp ở tế bào thực vật thực hiện quang hợp.", "Vi khuẩn E. coli là tế bào nhân sơ; tế bào lá cây là tế bào nhân thực có lục lạp.", "Lập bảng so sánh ba điểm khác nhau giữa tế bào nhân sơ và nhân thực."],
  ],
  literature: [
    ["cheo-tuong", "Đọc chèo và tuồng", "Chèo là sân khấu dân gian Bắc Bộ, nhân vật mang tính ước lệ, kết hợp hát, múa, nói lối; nội dung gần đời sống thường ngày. Tuồng thường đề cao trung nghĩa, nhân vật mang tính anh hùng. Khi đọc kịch bản, chú ý lời thoại, chỉ dẫn sân khấu và xung đột.", "Vở chèo “Quan Âm Thị Kính” thể hiện nỗi oan và đức nhẫn nhục của người phụ nữ.", "Chọn một lời thoại trong trích đoạn chèo và nêu tính cách nhân vật được bộc lộ."],
    ["literary-analysis", "Viết bài nghị luận phân tích một tác phẩm", "Bài phân tích tác phẩm cần luận đề rõ, các luận điểm về nội dung và nghệ thuật, mỗi luận điểm có dẫn chứng từ văn bản và lời phân tích. Tránh kể lại cốt truyện; tập trung vào cách tác giả tạo hiệu quả.", "Thay vì kể nhân vật làm gì, phân tích chi tiết ấy cho thấy điều gì về nhân vật.", "Lập dàn ý ba luận điểm cho bài phân tích một bài thơ em đã học."],
    ["binh-ngo", "Nguyễn Trãi và “Bình Ngô đại cáo”", "“Bình Ngô đại cáo” do Nguyễn Trãi viết năm 1428, sau thắng lợi của khởi nghĩa Lam Sơn. Tác phẩm khẳng định nền độc lập, tư tưởng nhân nghĩa “yên dân”, tố cáo tội ác giặc Minh và tổng kết cuộc kháng chiến. Lập luận chặt chẽ, giọng văn hào hùng.", "Câu mở đầu nêu tư tưởng “Việc nhân nghĩa cốt ở yên dân”.", "Tìm các yếu tố khẳng định chủ quyền dân tộc trong phần đầu tác phẩm."],
  ],
  english: [
    ["gerund-infinitive", "Gerund và to-infinitive sau động từ", "Một số động từ theo sau bởi to-infinitive: want, decide, hope, plan. Một số theo sau bởi V-ing: enjoy, avoid, finish, mind. Remember, stop, try có thể đi với cả hai nhưng nghĩa khác nhau.", "I stopped to buy water (dừng lại để mua). I stopped buying soft drinks (bỏ thói quen).", "Viết hai cặp câu với remember to V và remember V-ing để thấy khác biệt."],
    ["non-defining-relatives", "Mệnh đề quan hệ không xác định", "Mệnh đề quan hệ không xác định bổ sung thông tin thêm cho danh từ đã xác định, được ngăn bằng dấu phẩy. Không dùng that trong mệnh đề này và không lược bỏ đại từ quan hệ.", "Hanoi, which is the capital of Vietnam, has many lakes.", "Nối hai câu thành một: My teacher is very kind. She teaches English."],
    ["modal-passive", "Câu bị động với động từ khuyết thiếu", "Câu bị động với động từ khuyết thiếu có dạng modal + be + quá khứ phân từ: can be done, must be finished, should be reduced. Cấu trúc này thường dùng trong nội quy, hướng dẫn và đề xuất.", "Plastic waste should be reduced. Phones must be turned off during the test.", "Viết bốn nội quy cho phòng thí nghiệm bằng câu bị động với must hoặc should."],
  ],
  history: [
    ["southeast-asia", "Văn minh Đông Nam Á", "Đông Nam Á có nền văn minh lúa nước lâu đời, tiếp thu chọn lọc ảnh hưởng từ Ấn Độ và Trung Hoa. Thành tựu tiêu biểu gồm kiến trúc Angkor Wat (Campuchia), Borobudur (Indonesia), chữ viết dựa trên chữ Phạn. Tín ngưỡng, lễ hội gắn với nông nghiệp.", "Angkor Wat là quần thể đền tháp đá đồ sộ được xây dựng vào thế kỉ XII.", "Nêu hai điểm chung trong văn hóa các nước Đông Nam Á."],
    ["champa-funan", "Văn minh Champa và Phù Nam", "Champa hình thành ở miền Trung Việt Nam ngày nay, để lại nhiều tháp Chăm và khu đền tháp Mỹ Sơn, được UNESCO ghi danh năm 1999. Phù Nam phát triển ở Nam Bộ, có thương cảng Óc Eo buôn bán với nhiều nước. Hai nền văn minh chịu ảnh hưởng văn hóa Ấn Độ.", "Hiện vật ở Óc Eo có đồng tiền La Mã, cho thấy giao thương rộng.", "Tìm hiểu một di tích Chăm và nêu đặc điểm kiến trúc."],
    ["dai-viet-civilisation", "Văn minh Đại Việt", "Văn minh Đại Việt phát triển rực rỡ từ thế kỉ X đến XIX. Văn Miếu được xây dựng năm 1070, khoa thi đầu tiên tổ chức năm 1075. Chữ Nôm được dùng để sáng tác văn học. Nông nghiệp lúa nước, thủ công nghiệp và nhiều công trình kiến trúc phát triển.", "Bia tiến sĩ ở Văn Miếu ghi tên những người đỗ đạt qua các khoa thi.", "Nêu ý nghĩa của việc mở khoa thi đối với nhà nước Đại Việt."],
  ],
  geography: [
    ["hydrosphere", "Thủy quyển: sông, hồ và nước ngầm", "Thủy quyển gồm nước trong biển, đại dương, sông, hồ, băng và nước ngầm. Nước ngọt chỉ chiếm khoảng 2,5% tổng lượng nước, phần lớn nằm trong băng và nước ngầm. Chế độ nước sông phụ thuộc lượng mưa, địa hình và thực vật.", "Sông ở vùng có rừng thường có lũ lên chậm hơn vì rừng giữ nước.", "Giải thích vì sao cần tiết kiệm nước ngọt dù Trái Đất có nhiều nước."],
    ["population-growth", "Dân số và gia tăng dân số", "Gia tăng tự nhiên là hiệu số giữa tỉ suất sinh và tỉ suất tử. Gia tăng cơ học là chênh lệch giữa nhập cư và xuất cư. Dân số thế giới vượt 8 tỉ người vào năm 2022. Gia tăng dân số nhanh hoặc dân số già hóa đều đặt ra thách thức.", "Tỉ suất sinh 20‰ và tỉ suất tử 7‰ cho tỉ suất gia tăng tự nhiên 1,3%.", "Tính tỉ suất gia tăng tự nhiên với tỉ suất sinh 15‰ và tử 6‰."],
    ["urbanisation", "Đô thị hóa và chất lượng sống", "Đô thị hóa là quá trình tăng số dân thành thị, mở rộng đô thị và phổ biến lối sống đô thị. Đô thị hóa thúc đẩy kinh tế, dịch vụ nhưng có thể gây ách tắc, ô nhiễm, thiếu nhà ở nếu không được quy hoạch tốt.", "Giao thông công cộng giúp giảm ách tắc ở các đô thị lớn.", "Nêu hai giải pháp giảm ô nhiễm không khí ở đô thị."],
  ],
  informatics: [
    ["python-functions", "Hàm trong Python", "Hàm là khối lệnh có tên, nhận tham số và có thể trả về giá trị bằng return. Định nghĩa hàm bằng def. Hàm giúp tránh lặp mã, chia chương trình thành phần nhỏ dễ kiểm tra.", "def square(x): return x * x; square(4) trả về 16.", "Viết hàm nhận chiều dài, chiều rộng và trả về diện tích hình chữ nhật."],
    ["python-lists", "Danh sách (list) trong Python", "List lưu nhiều giá trị theo thứ tự, chỉ số bắt đầu từ 0. len() cho số phần tử, append() thêm phần tử vào cuối. Có thể duyệt list bằng vòng lặp for.", "a = [3, 5, 7] thì a[0] là 3, len(a) là 3; a.append(9) cho [3, 5, 7, 9].", "Viết chương trình tính tổng các số trong một list điểm."],
    ["python-strings", "Xâu kí tự trong Python", "Xâu (str) là dãy kí tự đặt trong dấu nháy. len() cho độ dài, toán tử in kiểm tra xâu con, cắt xâu s[a:b] lấy kí tự từ vị trí a đến trước b. Xâu không thể thay đổi trực tiếp từng kí tự.", "s = \"EduQuest\" thì s[0:3] là \"Edu\" và \"Quest\" in s là True.", "Viết chương trình đếm số chữ “a” trong một câu nhập vào."],
  ],
  technology: [
    ["orthographic", "Hình chiếu vuông góc", "Bản vẽ kĩ thuật dùng hình chiếu vuông góc để biểu diễn vật thể: hình chiếu đứng, hình chiếu bằng, hình chiếu cạnh. Theo phương pháp chiếu góc thứ nhất, hình chiếu bằng đặt dưới hình chiếu đứng, hình chiếu cạnh đặt bên phải. Nét liền đậm thể hiện cạnh thấy, nét đứt thể hiện cạnh khuất.", "Hình hộp chữ nhật có cả ba hình chiếu đều là hình chữ nhật.", "Vẽ ba hình chiếu của một khối hộp có rãnh trên mặt."],
    ["soil-improvement", "Đất trồng và cải tạo đất", "Đất trồng gồm phần rắn, lỏng, khí; độ phì nhiêu quyết định khả năng cung cấp dinh dưỡng. Độ chua đo bằng pH. Đất chua có thể cải tạo bằng bón vôi; đất bạc màu cần bổ sung phân hữu cơ, luân canh, che phủ đất.", "Bón vôi trên đất chua giúp tăng pH và cải thiện điều kiện cho cây.", "Đề xuất cách cải tạo đất cát nghèo dinh dưỡng."],
    ["smart-agriculture", "Công nghệ cao trong nông nghiệp", "Nông nghiệp công nghệ cao dùng nhà kính, tưới nhỏ giọt, thủy canh, cảm biến đo độ ẩm và điều khiển tự động. Lợi ích: tiết kiệm nước, phân bón, nâng năng suất. Hạn chế: chi phí đầu tư và yêu cầu kĩ thuật cao.", "Tưới nhỏ giọt đưa nước đến gốc cây, giảm thất thoát do bốc hơi.", "Thiết kế mô hình tưới tự động đơn giản cho một vườn rau nhỏ."],
  ],
  civics: [
    ["tax-budget", "Tham khảo: ngân sách nhà nước và thuế", "Ngân sách nhà nước là toàn bộ các khoản thu, chi của nhà nước. Thuế là khoản nộp bắt buộc, nguồn thu chủ yếu của ngân sách, dùng cho giáo dục, y tế, hạ tầng. Có thuế trực thu như thuế thu nhập cá nhân và thuế gián thu như thuế giá trị gia tăng.", "Giá hàng hóa bán lẻ thường đã bao gồm thuế giá trị gia tăng.", "Tìm hiểu một công trình công cộng ở địa phương được đầu tư từ ngân sách."],
    ["credit", "Tham khảo: tín dụng và sử dụng có trách nhiệm", "Tín dụng là quan hệ vay mượn trên nguyên tắc hoàn trả cả gốc và lãi đúng hạn. Lãi suất cho biết chi phí đi vay. Chỉ vay khi có kế hoạch trả nợ; tránh tín dụng đen với lãi suất cao bất thường và đòi nợ trái pháp luật.", "Vay 1.000.000đ lãi 10%/năm thì sau một năm trả 1.100.000đ.", "So sánh rủi ro khi vay ở tổ chức tín dụng hợp pháp và tín dụng đen."],
    ["constitution", "Tham khảo: Hiến pháp và hệ thống pháp luật", "Hiến pháp là luật cơ bản của Nhà nước, có hiệu lực pháp lí cao nhất. Các văn bản pháp luật khác không được trái Hiến pháp. Hiến pháp hiện hành được ban hành năm 2013 và có thể được sửa đổi, bổ sung; khi học cần tra cứu văn bản còn hiệu lực từ nguồn chính thức.", "Quyền học tập của công dân được ghi nhận trong Hiến pháp.", "Tìm một quyền cơ bản của công dân trong Hiến pháp và nêu ví dụ thực tế."],
  ],
  "physical-education": [
    ["volleyball", "Bóng chuyền: chuyền bóng cao tay và đệm bóng", "Chuyền cao tay dùng các ngón tay tạo hình phễu trên trán, đẩy bóng bằng sức duỗi tay và chân. Đệm bóng dùng hai cẳng tay áp sát, chân khuỵu, nâng bóng bằng chuyển động của chân. Di chuyển đến dưới bóng trước khi chạm.", "Đệm bóng bằng cánh tay thẳng, không vung tay mạnh.", "Tập chuyền bóng với bạn 20 lần liên tiếp và ghi số lần bóng rơi."],
    ["relay", "Chạy tiếp sức: trao và nhận gậy", "Chạy tiếp sức cần phối hợp nhịp nhàng giữa người trao và người nhận. Người nhận xuất phát khi người trao đến vạch đánh dấu, đưa tay ra sau khi nghe hiệu lệnh. Việc trao gậy phải diễn ra trong vùng trao gậy.", "Hô “Hắc!” khi trao giúp người nhận biết đúng thời điểm đưa tay.", "Cùng nhóm luyện trao gậy 5 lần và đánh giá lần nào mượt nhất."],
    ["sports-nutrition", "Dinh dưỡng cho người luyện tập", "Tinh bột cung cấp năng lượng, chất đạm giúp phục hồi cơ, nước bù lượng mất qua mồ hôi. Ăn bữa chính trước khi tập khoảng 2–3 giờ, có thể ăn nhẹ trước 30–60 phút. Không dùng thực phẩm chức năng khi chưa có tư vấn chuyên môn.", "Sau buổi tập, ăn sữa chua với chuối giúp bổ sung năng lượng và chất đạm.", "Lên thực đơn một ngày cho học sinh có buổi tập thể thao buổi chiều."],
  ],
  music: [
    ["genres", "Tham khảo: các thể loại âm nhạc phổ biến", "Âm nhạc có nhiều thể loại: nhạc cổ điển, nhạc pop, rock, jazz, nhạc dân gian. Jazz nổi bật với ứng tác (biểu diễn ngẫu hứng); rock thường dùng guitar điện và trống mạnh. Mỗi thể loại gắn với bối cảnh lịch sử, văn hóa riêng.", "Một bản jazz có thể được chơi khác nhau mỗi lần vì nghệ sĩ ứng tác.", "Nghe hai bài thuộc hai thể loại và so sánh nhạc cụ, nhịp điệu."],
    ["nha-nhac", "Tham khảo: Nhã nhạc cung đình Huế", "Nhã nhạc là âm nhạc cung đình triều Nguyễn, biểu diễn trong các nghi lễ, yến tiệc. Dàn nhạc gồm nhiều nhạc cụ dân tộc như trống, kèn, đàn nhị. Nhã nhạc cung đình Huế được UNESCO công nhận năm 2003.", "Nhã nhạc vang lên trong lễ tế Nam Giao, thể hiện sự trang nghiêm.", "Tìm hiểu một nhạc cụ trong dàn Nhã nhạc và mô tả âm sắc."],
    ["voice-types", "Tham khảo: giọng hát và các bè", "Giọng hát chia theo âm vực: nữ cao (soprano), nữ trầm (alto), nam cao (tenor), nam trầm (bass). Hát bè là nhiều giọng hát các giai điệu khác nhau cùng lúc, tạo hòa âm. Nhận biết âm vực giúp chọn bài phù hợp, tránh hại giọng.", "Hợp xướng bốn bè gồm soprano, alto, tenor, bass.", "Tìm âm vực thoải mái của giọng em bằng cách hát gam lên xuống."],
  ],
  "visual-arts": [
    ["photography", "Tham khảo: bố cục trong nhiếp ảnh", "Quy tắc một phần ba chia khung hình thành 9 ô bằng hai đường ngang và hai đường dọc; đặt chủ thể gần giao điểm giúp ảnh cân bằng, sinh động. Chú ý ánh sáng, hậu cảnh gọn và đường dẫn hướng mắt. Hỏi ý kiến trước khi chụp người khác.", "Đặt đường chân trời ở một phần ba dưới để nhấn mạnh bầu trời.", "Chụp ba bức ảnh cùng chủ thể với ba bố cục khác nhau và so sánh."],
    ["fashion-design", "Tham khảo: thiết kế thời trang cơ bản", "Thiết kế thời trang bắt đầu từ ý tưởng, phác thảo dáng, chọn chất liệu và màu. Trang phục cần phù hợp mục đích sử dụng, thời tiết và người mặc. Thời trang bền vững khuyến khích tái sử dụng, chọn vải bền.", "Áo đồng phục thể thao cần vải thấm hút mồ hôi và dễ vận động.", "Phác thảo một bộ trang phục cho chuyến dã ngoại của lớp."],
    ["architecture", "Tham khảo: kiến trúc và không gian sống", "Kiến trúc kết hợp công năng, kết cấu và thẩm mĩ. Nhà truyền thống Việt Nam thường có mái dốc, hiên rộng để thích nghi khí hậu nóng ẩm, mưa nhiều. Kiến trúc xanh tận dụng ánh sáng, thông gió tự nhiên.", "Nhà rông Tây Nguyên có mái cao, nhọn, là nơi sinh hoạt cộng đồng.", "Quan sát một công trình ở địa phương và nêu cách nó thích nghi với khí hậu."],
  ],
  "national-defense": [
    ["armed-forces-tradition", "Truyền thống Quân đội và Công an nhân dân Việt Nam", "Quân đội nhân dân Việt Nam tiền thân là Đội Việt Nam Tuyên truyền Giải phóng quân thành lập ngày 22/12/1944. Công an nhân dân Việt Nam được thành lập ngày 19/8/1945. Hai lực lượng có truyền thống trung thành, gắn bó với nhân dân.", "Ngày 22/12 hằng năm là ngày kỉ niệm thành lập Quân đội nhân dân Việt Nam.", "Tìm hiểu một tấm gương tiêu biểu của lực lượng vũ trang và nêu phẩm chất đáng học."],
    ["drill-commands", "Đội ngũ từng người không có súng", "Điều lệnh đội ngũ gồm các động tác: nghiêm, nghỉ, quay tại chỗ, đi đều, đứng lại. Khẩu lệnh thường có dự lệnh (báo trước) và động lệnh (thực hiện). Tập đúng giúp rèn tác phong, kỉ luật và phối hợp tập thể.", "Khẩu lệnh “Bên trái – quay”: “Bên trái” là dự lệnh, “quay” là động lệnh.", "Tập động tác quay tại chỗ và nhờ bạn nhận xét."],
    ["traffic-law", "Phòng, chống vi phạm trật tự an toàn giao thông", "Vi phạm giao thông là nguyên nhân hàng đầu gây tai nạn. Đội mũ bảo hiểm khi đi xe máy, xe đạp điện; không phóng nhanh, vượt ẩu, dùng điện thoại khi lái. Pháp luật nghiêm cấm điều khiển phương tiện khi trong máu hoặc hơi thở có nồng độ cồn.", "Không lái xe sau khi uống rượu bia, dù chỉ một lượng nhỏ.", "Liệt kê ba lỗi vi phạm giao thông phổ biến của học sinh và cách phòng tránh."],
  ],
  "career-experience": [
    ["critical-thinking", "Tư duy phản biện khi ra quyết định", "Tư duy phản biện là xem xét thông tin, bằng chứng và các góc nhìn khác nhau trước khi kết luận. Đặt câu hỏi: nguồn tin là ai, bằng chứng là gì, có cách hiểu khác không. Áp dụng khi chọn môn học, câu lạc bộ, nghề nghiệp.", "Trước khi tin quảng cáo “học 1 tuần thành thạo tiếng Anh”, kiểm tra bằng chứng.", "Phân tích một quyết định gần đây của em theo ba câu hỏi phản biện."],
    ["time-balance", "Cân bằng học tập và hoạt động ngoại khóa", "Hoạt động ngoại khóa giúp phát triển kĩ năng, nhưng cần cân bằng với học tập và nghỉ ngơi. Lập lịch tuần, ưu tiên việc quan trọng và biết từ chối khi quá tải.", "Chọn hai câu lạc bộ phù hợp thay vì tham gia năm câu lạc bộ cùng lúc.", "Lập lịch tuần có thời gian học, ngoại khóa và nghỉ ngơi."],
    ["stem-careers", "Tìm hiểu nhóm ngành STEM", "STEM gồm khoa học, công nghệ, kĩ thuật và toán học. Các nghề STEM như kĩ sư, nhà khoa học dữ liệu, kĩ thuật viên y sinh cần tư duy logic, kĩ năng giải quyết vấn đề. Có thể trải nghiệm qua dự án khoa học, câu lạc bộ robot.", "Kĩ sư môi trường dùng kiến thức hóa học và sinh học để xử lí nước thải.", "Chọn một nghề STEM, tìm hiểu ngành học liên quan và kĩ năng cần thiết."],
  ],
};
