export const gradeNineMoreLessons = {
  math: [
    ["linear-systems", "Hệ hai phương trình bậc nhất hai ẩn", "Hệ hai phương trình bậc nhất hai ẩn có thể giải bằng phương pháp thế hoặc cộng đại số. Phương pháp thế: rút một ẩn từ một phương trình rồi thay vào phương trình kia. Phương pháp cộng: nhân để hệ số một ẩn đối nhau rồi cộng hai phương trình. Thay nghiệm vào cả hai phương trình để kiểm tra.", "x + y = 5 và x − y = 1: cộng hai phương trình được 2x = 6, x = 3, y = 2.", "Giải bài toán: 2 bút và 3 vở giá 26.000đ, 1 bút và 1 vở giá 10.000đ."],
    ["inequalities", "Bất đẳng thức và bất phương trình bậc nhất", "Bất phương trình bậc nhất một ẩn có dạng ax + b > 0 (hoặc <, ≥, ≤) với a khác 0. Khi nhân hoặc chia hai vế cho số âm, phải đổi chiều bất đẳng thức. Tập nghiệm có thể biểu diễn trên trục số.", "−2x < 6 chia hai vế cho −2 được x > −3.", "Giải 3x − 5 ≥ 7 và biểu diễn tập nghiệm trên trục số."],
    ["trig-ratios", "Tỉ số lượng giác của góc nhọn", "Trong tam giác vuông, với góc nhọn α: sin α = cạnh đối/cạnh huyền, cos α = cạnh kề/cạnh huyền, tan α = cạnh đối/cạnh kề. Một số giá trị đặc biệt: sin 30° = 1/2, cos 60° = 1/2, tan 45° = 1. Tỉ số lượng giác giúp tính chiều cao, khoảng cách khó đo trực tiếp.", "Đứng cách cây 10 m, nhìn ngọn cây với góc 45° thì cây cao khoảng 10 m cộng chiều cao tầm mắt.", "Tính chiều cao cột cờ khi bóng dài 8 m và góc nhìn từ đầu bóng là 30° (tan 30° ≈ 0,58)."],
  ],
  science: [
    ["reactivity-series", "Kim loại và dãy hoạt động hóa học", "Dãy hoạt động hóa học sắp xếp kim loại theo mức độ phản ứng giảm dần: K, Na, Ca, Mg, Al, Zn, Fe, Pb, (H), Cu, Ag, Au. Kim loại đứng trước H phản ứng với acid loãng như HCl giải phóng khí hydrogen; kim loại sau H như Cu, Ag không phản ứng.", "Zn + 2HCl → ZnCl₂ + H₂. Đồng ngâm trong HCl loãng không có bọt khí.", "Dự đoán kim loại nào trong Fe, Cu, Mg phản ứng với HCl loãng và giải thích."],
    ["refraction-lenses", "Khúc xạ ánh sáng và thấu kính", "Khúc xạ là hiện tượng tia sáng đổi hướng khi truyền qua mặt phân cách hai môi trường. Thấu kính hội tụ có phần rìa mỏng hơn phần giữa, hội tụ chùm tia song song; thấu kính phân kì rìa dày hơn, làm chùm tia loe ra. Người cận thị đeo kính phân kì.", "Chiếc đũa trong cốc nước trông như bị gãy ở mặt nước do khúc xạ.", "Dùng kính lúp hội tụ ánh sáng Mặt Trời thành một điểm (không để lâu) và giải thích."],
    ["mendel", "Di truyền học Mendel", "Mendel lai đậu Hà Lan và phát hiện tính trạng trội, lặn. Mỗi tính trạng do một cặp nhân tố di truyền (allele) quy định. Lai thuần chủng AA × aa cho F1 đều Aa mang tính trạng trội; cho F1 tự thụ phấn, F2 có tỉ lệ kiểu hình xấp xỉ 3 trội : 1 lặn.", "Hạt vàng (A) trội so với hạt xanh (a): F2 có khoảng 3 hạt vàng cho mỗi 1 hạt xanh.", "Viết sơ đồ lai Aa × aa và cho biết tỉ lệ kiểu hình."],
  ],
  literature: [
    ["truyen-kieu", "Truyện thơ Nôm và Truyện Kiều", "Truyện thơ Nôm là tác phẩm tự sự viết bằng chữ Nôm, thường theo thể lục bát. “Truyện Kiều” của Nguyễn Du gồm 3.254 câu lục bát, kể cuộc đời Thúy Kiều, thể hiện lòng thương cảm với số phận con người. Tác phẩm nổi bật về nghệ thuật tả cảnh ngụ tình và khắc họa nhân vật.", "Câu “Làn thu thủy nét xuân sơn” tả đôi mắt và lông mày Thúy Kiều bằng hình ảnh thiên nhiên.", "Chọn hai câu Truyện Kiều tả cảnh và nêu cảm xúc của nhân vật được gợi ra."],
    ["detective-stories", "Đọc truyện trinh thám", "Truyện trinh thám xoay quanh một vụ án hoặc bí ẩn, nhân vật thám tử dùng quan sát và suy luận để tìm ra sự thật. Chú ý các manh mối, chi tiết đánh lạc hướng và lập luận ở phần kết. Đọc chậm, ghi chú manh mối giúp theo dõi mạch truyện.", "Thám tử Sherlock Holmes thường suy luận từ chi tiết nhỏ như vết bùn trên giày.", "Ghi lại ba manh mối trong một truyện trinh thám và giải thích vai trò của chúng."],
    ["wordplay", "Chơi chữ và điệp ngữ", "Chơi chữ lợi dụng đặc sắc về âm, nghĩa của từ như đồng âm, gần âm để tạo sắc thái dí dỏm. Điệp ngữ lặp lại từ ngữ để nhấn mạnh, tạo nhịp điệu. Cần dùng phù hợp ngữ cảnh, tránh gây hiểu lầm.", "“Lợi thì có lợi nhưng răng không còn”: “lợi” vừa là lợi ích vừa là phần nướu răng.", "Viết một câu có điệp ngữ về quê hương và giải thích tác dụng."],
  ],
  english: [
    ["used-to", "Used to: thói quen trong quá khứ", "Used to + động từ nguyên mẫu diễn tả thói quen hoặc trạng thái trong quá khứ nay không còn. Phủ định: didn't use to; câu hỏi: Did you use to...? Phân biệt với be used to + V-ing nghĩa là quen với việc gì.", "I used to walk to school, but now I cycle. She is used to getting up early.", "Viết ba câu về điều em từng làm khi còn nhỏ."],
    ["phrasal-verbs", "Cụm động từ thường gặp", "Cụm động từ gồm động từ và tiểu từ, nghĩa có thể khác nghĩa từng từ: look after (chăm sóc), give up (từ bỏ), find out (tìm ra), turn off (tắt). Nên học cụm động từ trong câu ví dụ.", "Please turn off the lights. I found out the answer.", "Đặt câu với năm cụm động từ và dùng chúng trong một đoạn văn ngắn."],
    ["wh-to-infinitive", "Từ để hỏi + to-infinitive", "Cấu trúc từ để hỏi (what, how, where, when, who) + to + động từ nguyên mẫu dùng để nói về việc nên làm hoặc cách làm. Thường đi sau know, decide, ask, learn, wonder.", "I don't know what to do. Can you show me how to use this app?", "Viết ba câu với how to, where to, what to về chuyến đi sắp tới."],
  ],
  history: [
    ["world-war-two", "Chiến tranh thế giới thứ hai", "Chiến tranh thế giới thứ hai (1939–1945) bắt đầu khi Đức tấn công Ba Lan ngày 1/9/1939. Phe Đồng minh gồm Liên Xô, Mỹ, Anh… chiến đấu chống phe phát xít Đức, Italy, Nhật Bản. Chiến tranh gây thiệt hại to lớn nhất lịch sử; Liên Hợp Quốc được thành lập năm 1945 để duy trì hòa bình.", "Phát xít Đức đầu hàng tháng 5/1945; Nhật Bản đầu hàng tháng 8/1945.", "Nêu hai bài học về hòa bình rút ra từ Chiến tranh thế giới thứ hai."],
    ["cold-war", "Chiến tranh lạnh", "Sau năm 1945, Mỹ và Liên Xô đối đầu về chính trị, kinh tế, quân sự nhưng không xung đột trực tiếp, gọi là Chiến tranh lạnh. Thế giới chia thành hai phe. Bức tường Berlin sụp đổ năm 1989; Liên Xô tan rã năm 1991, Chiến tranh lạnh kết thúc.", "Cuộc chạy đua vào vũ trụ là một biểu hiện của cạnh tranh giữa hai phe.", "Giải thích vì sao gọi là chiến tranh “lạnh”."],
    ["reunification", "Kháng chiến chống Mỹ và thống nhất đất nước", "Sau năm 1954, Việt Nam tạm chia cắt làm hai miền. Nhân dân hai miền tiến hành kháng chiến chống Mỹ. Hiệp định Paris được kí ngày 27/1/1973, Mỹ rút quân. Ngày 30/4/1975, Chiến dịch Hồ Chí Minh toàn thắng, đất nước thống nhất.", "Năm 1976, Quốc hội thống nhất đặt tên nước là Cộng hòa xã hội chủ nghĩa Việt Nam.", "Lập trục thời gian từ 1954 đến 1976 với bốn sự kiện chính."],
  ],
  geography: [
    ["red-river-delta", "Vùng Đồng bằng sông Hồng", "Đồng bằng sông Hồng có đất phù sa màu mỡ, mật độ dân số cao, lịch sử khai thác lâu đời. Thế mạnh gồm trồng lúa, rau vụ đông, công nghiệp và dịch vụ; Hà Nội là trung tâm chính trị, văn hóa. Thách thức gồm sức ép dân số, ô nhiễm môi trường và quỹ đất hạn chế.", "Hệ thống đê sông Hồng giúp chống lũ nhưng làm một số ô ruộng trong đê không được bồi phù sa.", "Nêu một thuận lợi và một thách thức khi dân số đông ở vùng này."],
    ["central-highlands", "Vùng Tây Nguyên", "Tây Nguyên gồm các cao nguyên xếp tầng, đất đỏ badan màu mỡ, khí hậu có mùa khô sâu sắc. Vùng là nơi trồng nhiều cà phê, cao su, hồ tiêu và có tiềm năng thủy điện. Bảo vệ rừng và giải quyết thiếu nước mùa khô là vấn đề quan trọng.", "Cà phê Tây Nguyên chiếm tỉ trọng lớn trong sản lượng cà phê cả nước.", "Giải thích vì sao thiếu nước mùa khô ảnh hưởng đến cây công nghiệp."],
    ["transport", "Giao thông vận tải và bưu chính viễn thông", "Việt Nam có nhiều loại hình giao thông: đường bộ, đường sắt, đường sông, đường biển và hàng không. Đường bộ chiếm tỉ trọng lớn trong vận chuyển hàng hóa, hành khách. Viễn thông và Internet phát triển nhanh, hỗ trợ học tập, kinh doanh.", "Cảng biển nước sâu giúp tàu lớn vận chuyển hàng xuất khẩu trực tiếp.", "So sánh ưu điểm của đường sắt và đường hàng không khi đi xa."],
  ],
  informatics: [
    ["if-countif", "Bảng tính: hàm IF và COUNTIF", "Hàm IF trả về kết quả tùy điều kiện đúng hay sai: =IF(B2>=5,\"Đạt\",\"Chưa đạt\"). Hàm COUNTIF đếm số ô thỏa điều kiện: =COUNTIF(B2:B30,\">=8\"). Tùy cài đặt vùng, dấu phân cách đối số có thể là dấu phẩy hoặc dấu chấm phẩy.", "Bảng điểm 30 bạn dùng COUNTIF để đếm số bạn đạt từ 8 điểm.", "Lập bảng điểm 5 bạn, dùng IF để xếp loại và COUNTIF để đếm số bạn đạt."],
    ["spreadsheet-charts", "Biểu đồ trong bảng tính", "Biểu đồ giúp trình bày dữ liệu trực quan. Biểu đồ cột so sánh các nhóm, biểu đồ đường thể hiện xu hướng theo thời gian, biểu đồ tròn thể hiện tỉ lệ các phần trong tổng. Cần có tiêu đề, chú thích và đơn vị rõ ràng.", "Nhiệt độ trung bình 12 tháng nên dùng biểu đồ đường để thấy sự thay đổi.", "Chọn loại biểu đồ phù hợp cho số học sinh mỗi lớp và giải thích."],
    ["it-careers", "Nghề nghiệp trong lĩnh vực tin học", "Lĩnh vực tin học có nhiều nghề: lập trình viên, kĩ sư dữ liệu, chuyên viên an ninh mạng, thiết kế trải nghiệm người dùng, quản trị hệ thống. Các nghề cần tư duy logic, học liên tục và làm việc nhóm. Có thể bắt đầu khám phá qua dự án nhỏ.", "Chuyên viên an ninh mạng kiểm tra lỗ hổng để bảo vệ dữ liệu của tổ chức.", "Tìm hiểu một nghề tin học: công việc hằng ngày, kĩ năng cần có."],
  ],
  technology: [
    ["home-wiring", "Lắp đặt mạng điện trong nhà", "Sơ đồ nguyên lí thể hiện mối liên hệ điện giữa các phần tử; sơ đồ lắp đặt thể hiện vị trí lắp thực tế. Lắp đặt cần đúng quy trình, dùng dây và thiết bị phù hợp công suất. Học sinh chỉ thực hành khi đã ngắt nguồn và có giáo viên giám sát.", "Công tắc phải lắp trên dây pha để khi tắt, đèn không còn điện.", "Vẽ sơ đồ nguyên lí mạch gồm cầu chì, công tắc và một bóng đèn."],
    ["no-cook-dishes", "Chế biến món ăn không dùng nhiệt", "Món không dùng nhiệt như salad, nộm cần đặc biệt chú ý vệ sinh: rửa tay, rửa rau dưới vòi nước, dùng thớt riêng cho đồ sống và đồ chín. Dùng dao cẩn thận, cắt hướng ra ngoài. Ăn ngay sau khi chế biến.", "Nộm rau muống cần rửa kĩ, ngâm nước muối loãng rồi trộn với gia vị.", "Viết quy trình làm một món salad đơn giản gồm bốn bước."],
    ["energy-saving", "Sử dụng điện tiết kiệm trong gia đình", "Dùng thiết bị có nhãn năng lượng hiệu suất cao, tắt thiết bị khi không dùng, rút phích để tránh tiêu thụ điện ở chế độ chờ. Đặt điều hòa khoảng 26°C trở lên và đóng kín cửa. Tận dụng ánh sáng tự nhiên.", "Đèn LED dùng ít điện hơn đèn sợi đốt cho cùng độ sáng.", "Tính điện năng tiêu thụ của một thiết bị trong tháng theo công suất và số giờ dùng."],
  ],
  civics: [
    ["ideals", "Sống có lí tưởng", "Lí tưởng sống là mục đích cao đẹp mà một người hướng tới, định hướng hành động hằng ngày. Người có lí tưởng biết đặt mục tiêu, nỗ lực và đóng góp cho cộng đồng. Lí tưởng của thanh niên gắn với học tập, rèn luyện và trách nhiệm xã hội.", "Một bạn mơ làm bác sĩ đã tình nguyện tham gia sơ cứu ở trường.", "Viết một đoạn ngắn về lí tưởng của em và bước đầu tiên để thực hiện."],
    ["legal-liability", "Vi phạm pháp luật và trách nhiệm pháp lí", "Vi phạm pháp luật là hành vi trái pháp luật, có lỗi, do người có năng lực trách nhiệm pháp lí thực hiện. Có bốn loại trách nhiệm pháp lí: hình sự, hành chính, dân sự và kỉ luật. Hiểu pháp luật giúp phòng tránh vi phạm.", "Đi xe máy không đội mũ bảo hiểm có thể bị xử phạt hành chính.", "Nêu một ví dụ cho mỗi loại trách nhiệm pháp lí."],
    ["adapting-change", "Thích ứng với thay đổi", "Thay đổi có thể là chuyển trường, chuyển nhà, gia đình thay đổi hoặc bước vào kì thi. Thích ứng là chấp nhận, điều chỉnh suy nghĩ và hành động phù hợp. Có thể chia nhỏ mục tiêu, giữ thói quen tích cực và tìm hỗ trợ khi cần.", "Khi chuyển trường, chủ động làm quen bạn mới và hỏi thầy cô về nội quy.", "Kể về một thay đổi em đã trải qua và cách em thích ứng."],
  ],
  "physical-education": [
    ["badminton", "Cầu lông: cầm vợt và phát cầu", "Cầm vợt kiểu bắt tay, ngón cái và ngón trỏ tạo hình chữ V. Phát cầu thấp thuận tay: thả cầu, vung vợt từ dưới lên đánh cầu qua lưới. Khi phát, đánh chéo sang ô đối diện. Khởi động kĩ cổ tay, vai.", "Phát cầu thấp, sát lưới khiến đối phương khó tấn công.", "Tập phát cầu 10 lần và ghi số lần cầu rơi đúng ô."],
    ["breaststroke", "Bơi ếch: nhịp thở và phối hợp", "Bơi ếch phối hợp quạt tay, đạp chân và thở: kéo tay rồi ngẩng đầu thở, duỗi tay rồi đạp chân và lướt. Chỉ tập ở bể bơi có cứu hộ, không bơi khi mệt hoặc vừa ăn no.", "Lướt thả lỏng sau mỗi nhịp đạp giúp tiết kiệm sức.", "Ghi lại số nhịp tay và thở trong 25 m bơi."],
    ["bodyweight", "Bài tập sức mạnh bằng trọng lượng cơ thể", "Chống đẩy, gánh (squat), plank giúp tăng sức mạnh mà không cần dụng cụ. Ưu tiên kĩ thuật đúng hơn số lần: lưng thẳng, gối không vượt quá xa mũi chân khi squat. Tăng dần khối lượng tập, nghỉ đủ giữa các hiệp.", "Plank đúng: thân thẳng từ đầu đến gót, siết cơ bụng, không võng lưng.", "Thiết kế bài tập 10 phút gồm ba động tác và ghi lại tiến bộ sau hai tuần."],
  ],
  music: [
    ["cheo", "Hát chèo và sân khấu truyền thống", "Chèo là loại hình sân khấu dân gian của đồng bằng Bắc Bộ, kết hợp hát, múa, nói, nhạc. Nhân vật mang tính ước lệ: đào, kép, hề. Dàn nhạc chèo có trống, đàn nhị, sáo. Chèo phản ánh đời sống và ước mơ của người dân.", "Vai hề chèo dùng tiếng cười để phê phán thói xấu.", "Xem một trích đoạn chèo và nêu một đặc điểm về hát hoặc múa."],
    ["vn-composers", "Nhạc sĩ Việt Nam và tác phẩm tiêu biểu", "Âm nhạc Việt Nam có nhiều nhạc sĩ gắn với lịch sử đất nước. Văn Cao là tác giả “Tiến quân ca”, được chọn làm Quốc ca. Phạm Tuyên sáng tác “Như có Bác trong ngày đại thắng” năm 1975. Tìm hiểu hoàn cảnh sáng tác giúp hiểu sâu tác phẩm.", "“Tiến quân ca” có giai điệu hùng tráng, nhịp hành khúc.", "Chọn một bài hát Việt Nam và tìm hiểu tác giả, hoàn cảnh sáng tác."],
    ["recording", "Ghi âm và chỉnh âm thanh cơ bản", "Ghi âm tốt cần phòng yên tĩnh, micro đặt cách miệng vừa phải. Tránh âm thanh quá to làm vỡ tiếng. Phần mềm cho phép cắt, điều chỉnh âm lượng, giảm tiếng ồn. Chỉ dùng nhạc nền có quyền sử dụng.", "Đặt micro hơi lệch khỏi hướng miệng để giảm tiếng gió khi hát.", "Ghi âm một đoạn hát ngắn, nghe lại và nêu một điểm cần cải thiện."],
  ],
  "visual-arts": [
    ["logo-design", "Thiết kế logo", "Logo tốt đơn giản, dễ nhớ, dễ nhận biết và vẫn rõ khi thu nhỏ hoặc in đen trắng. Logo nên phản ánh đặc điểm của tổ chức. Bắt đầu bằng nhiều phác thảo, chọn và tinh chỉnh phương án tốt nhất.", "Logo câu lạc bộ đọc sách có thể kết hợp hình quyển sách và chữ cái đầu.", "Phác ba phương án logo cho lớp em và chọn một."],
    ["installation-art", "Nghệ thuật sắp đặt và tái chế", "Nghệ thuật sắp đặt bố trí vật thể trong không gian để tạo ý nghĩa, người xem có thể đi quanh, trải nghiệm. Dùng vật liệu tái chế vừa tiết kiệm vừa truyền thông điệp về môi trường. Chú ý an toàn khi cắt, dán vật liệu.", "Dùng chai nhựa tái chế tạo hình con cá để nói về rác thải đại dương.", "Lên ý tưởng tác phẩm sắp đặt từ vật liệu tái chế ở trường."],
    ["lacquer", "Tranh sơn mài Việt Nam", "Sơn mài là chất liệu truyền thống dùng sơn ta, phủ nhiều lớp, sau đó mài để lộ màu và độ sâu. Họa sĩ dùng vàng, bạc, vỏ trứng, son để tạo hiệu quả. Nguyễn Gia Trí là họa sĩ tiêu biểu đưa sơn mài thành nghệ thuật hội họa.", "Vỏ trứng gắn trên tranh sơn mài tạo mảng trắng có vân rạn tự nhiên.", "Quan sát một bức tranh sơn mài và mô tả màu sắc, chất liệu."],
  ],
  "national-defense": [
    ["cyber-safety", "Tham khảo: an toàn trên không gian mạng", "Đây là kĩ năng an toàn mở rộng. Dùng mật khẩu mạnh, khác nhau cho mỗi tài khoản và bật xác thực hai lớp. Không bấm đường dẫn lạ, không cung cấp mã OTP cho bất kì ai. Báo người lớn khi bị đe dọa, lừa đảo trên mạng.", "Tin nhắn “Bạn trúng thưởng, nhập mã OTP để nhận quà” là dấu hiệu lừa đảo.", "Kiểm tra mật khẩu các tài khoản của em và bật xác thực hai lớp nếu có thể."],
    ["fire-extinguisher", "Tham khảo: sử dụng bình chữa cháy", "Bình chữa cháy chỉ dùng cho đám cháy nhỏ khi vẫn có lối thoát. Các bước: rút chốt, hướng vòi vào gốc lửa, bóp cò, quét qua lại. Không dùng nước dập cháy điện hoặc xăng dầu. Nếu lửa lớn, thoát ra ngay và gọi 114.", "Đứng ở đầu hướng gió, cách đám cháy vài mét khi phun.", "Tìm vị trí bình chữa cháy ở trường và đọc hướng dẫn trên bình."],
    ["defense-tradition", "Tham khảo: truyền thống dựng nước và giữ nước", "Lịch sử Việt Nam gắn với nhiều cuộc đấu tranh giữ nước: Bạch Đằng, kháng chiến chống Mông – Nguyên, khởi nghĩa Lam Sơn, Quang Trung đại phá quân Thanh. Truyền thống đoàn kết, lấy ít địch nhiều là bài học quý. Tìm hiểu qua nguồn sử liệu đáng tin cậy.", "Hội thề Diên Hồng thể hiện sự đồng lòng của triều đình và nhân dân thời Trần.", "Chọn một sự kiện giữ nước và nêu bài học về tinh thần đoàn kết."],
  ],
  "career-experience": [
    ["self-introduction", "Viết hồ sơ học tập và bản tự giới thiệu", "Bản tự giới thiệu ngắn gọn nêu sở thích, điểm mạnh, hoạt động đã tham gia và mục tiêu. Dùng ví dụ cụ thể thay cho lời khen chung chung. Hồ sơ học tập lưu sản phẩm, giấy chứng nhận và nhận xét.", "Thay vì “Em năng động”, viết “Em tổ chức ba buổi đọc sách cho lớp”.", "Viết bản tự giới thiệu 100 chữ với ít nhất hai ví dụ cụ thể."],
    ["exam-stress", "Quản lí cảm xúc trước kì thi", "Lo lắng trước thi là bình thường; mức vừa phải giúp tập trung. Ôn tập theo kế hoạch, ngủ đủ, ăn uống điều độ. Khi căng thẳng, hít thở sâu, nghĩ về điều đã chuẩn bị. Tránh so sánh với người khác.", "Đêm trước kì thi ngủ sớm thay vì thức khuya ôn lại toàn bộ.", "Lập kế hoạch ôn tập hai tuần trước kì thi, có thời gian nghỉ."],
    ["local-labour-market", "Nghề nghiệp và thị trường lao động địa phương", "Thị trường lao động phản ánh nhu cầu tuyển dụng của doanh nghiệp, cơ quan. Mỗi địa phương có ngành nghề thế mạnh riêng. Tìm hiểu qua trung tâm dịch vụ việc làm, báo chí chính thống, người làm nghề.", "Địa phương có khu công nghiệp thường cần nhiều kĩ thuật viên, công nhân lành nghề.", "Phỏng vấn một người làm nghề ở địa phương về yêu cầu công việc."],
  ],
};
