export const gradeTwelveMoreLessons = {
  math: [
    ["asymptotes", "Đường tiệm cận của đồ thị hàm số", "Đường thẳng y = b là tiệm cận ngang nếu f(x) tiến tới b khi x tiến tới +∞ hoặc −∞. Đường thẳng x = a là tiệm cận đứng nếu f(x) tiến tới vô cực khi x tiến tới a. Với hàm phân thức y = (ax + b)/(cx + d), tiệm cận đứng x = −d/c và tiệm cận ngang y = a/c.", "y = (2x + 1)/(x − 1) có tiệm cận đứng x = 1 và tiệm cận ngang y = 2.", "Tìm các đường tiệm cận của y = (x + 3)/(2x − 4)."],
    ["planes-oxyz", "Phương trình mặt phẳng trong không gian Oxyz", "Mặt phẳng đi qua điểm M(x₀; y₀; z₀) và có vectơ pháp tuyến n = (a; b; c) có phương trình a(x − x₀) + b(y − y₀) + c(z − z₀) = 0. Vectơ pháp tuyến vuông góc với mặt phẳng. Hai mặt phẳng song song khi vectơ pháp tuyến cùng phương và không trùng nhau.", "Mặt phẳng qua O(0; 0; 0) có vectơ pháp tuyến (1; 2; 3) là x + 2y + 3z = 0.", "Viết phương trình mặt phẳng qua A(1; 0; 2) và có vectơ pháp tuyến (2; −1; 1)."],
    ["conditional-probability", "Xác suất có điều kiện", "Xác suất của A khi biết B đã xảy ra: P(A|B) = P(A ∩ B)/P(B) với P(B) > 0. Công thức nhân: P(A ∩ B) = P(B)·P(A|B). Công thức Bayes giúp cập nhật xác suất khi có thông tin mới.", "Gieo xúc xắc được số chẵn; xác suất số đó là 6 bằng (1/6)/(1/2) = 1/3.", "Rút ngẫu nhiên một thẻ từ 1 đến 10, biết thẻ là số lẻ. Tính xác suất thẻ lớn hơn 5."],
  ],
  science: [
    ["radioactivity", "Hạt nhân nguyên tử và phóng xạ", "Phóng xạ là quá trình hạt nhân không bền tự phát ra tia α, β, γ và biến đổi thành hạt nhân khác. Chu kì bán rã T là thời gian để một nửa số hạt nhân phóng xạ bị phân rã. Phóng xạ có ứng dụng trong y học, nhưng cần che chắn và tuân thủ quy định an toàn.", "Chất có chu kì bán rã 8 ngày, sau 16 ngày còn lại 1/4 lượng ban đầu.", "Tính lượng còn lại của 80 g chất phóng xạ sau ba chu kì bán rã."],
    ["ac-transformer", "Dòng điện xoay chiều và máy biến áp", "Dòng điện xoay chiều đổi chiều tuần hoàn; điện lưới Việt Nam có tần số 50 Hz. Máy biến áp lí tưởng có U₁/U₂ = N₁/N₂. Truyền tải điện đi xa bằng điện áp cao giúp giảm hao phí trên đường dây.", "Máy biến áp có cuộn sơ cấp 1000 vòng, thứ cấp 50 vòng biến 220 V thành 11 V.", "Giải thích vì sao đường dây truyền tải điện dùng điện áp rất cao."],
    ["evolution", "Tiến hóa và chọn lọc tự nhiên", "Theo Darwin, các cá thể trong quần thể có biến dị; những biến dị có lợi giúp cá thể sống sót, sinh sản nhiều hơn và được di truyền cho thế hệ sau. Qua nhiều thế hệ, quần thể thích nghi với môi trường. Hiện tượng vi khuẩn kháng kháng sinh là ví dụ chọn lọc tự nhiên.", "Dùng kháng sinh không đủ liều có thể giữ lại vi khuẩn kháng thuốc.", "Giải thích vì sao cần dùng kháng sinh theo đúng chỉ định của bác sĩ."],
  ],
  literature: [
    ["resistance-poetry", "Thơ ca kháng chiến", "Thơ ca thời kháng chiến thể hiện tinh thần yêu nước, hình tượng người lính và tình đồng chí. “Tây Tiến” của Quang Dũng (1948) khắc họa người lính vừa hào hùng vừa hào hoa trên nền thiên nhiên Tây Bắc dữ dội, thơ mộng. Khi đọc, chú ý bút pháp lãng mạn và hiện thực.", "Câu “Tây Tiến đoàn binh không mọc tóc” vừa nói gian khổ vừa thể hiện vẻ ngang tàng.", "Phân tích hình ảnh người lính trong một khổ thơ kháng chiến em chọn."],
    ["post-1975-story", "Truyện ngắn sau năm 1975", "Văn học sau 1975 hướng nhiều hơn tới đời sống thường nhật, số phận cá nhân và các vấn đề đạo đức. “Chiếc thuyền ngoài xa” của Nguyễn Minh Châu đặt ra mối quan hệ giữa nghệ thuật và cuộc đời qua cái nhìn của nhân vật nghệ sĩ.", "Bức ảnh đẹp chiếc thuyền ngoài xa đối lập với cảnh bạo lực gia đình khi thuyền vào bờ.", "Nêu thông điệp về cách nhìn cuộc sống em rút ra từ một truyện ngắn sau 1975."],
    ["declaration", "Tuyên ngôn Độc lập", "“Tuyên ngôn Độc lập” do Chủ tịch Hồ Chí Minh đọc ngày 2/9/1945, khai sinh nước Việt Nam Dân chủ Cộng hòa. Mở đầu, tác giả trích dẫn Tuyên ngôn Độc lập của Mỹ (1776) và Tuyên ngôn Nhân quyền và Dân quyền của Pháp (1791). Lập luận chặt chẽ, bằng chứng xác thực, lời văn đanh thép.", "Việc trích dẫn văn kiện của Mỹ, Pháp tạo cơ sở pháp lí và đạo lí cho bản tuyên ngôn.", "Phân tích tác dụng của phần trích dẫn mở đầu tác phẩm."],
  ],
  english: [
    ["inversion", "Đảo ngữ để nhấn mạnh", "Khi câu bắt đầu bằng trạng từ phủ định như Never, Rarely, Seldom, Not only, trợ động từ đứng trước chủ ngữ. Not only ... but also ... dùng để nhấn mạnh hai ý. Cấu trúc này thường gặp trong văn viết trang trọng.", "Never have I seen such a beautiful view. Not only did he finish early, but he also helped others.", "Viết lại ba câu thường thành câu đảo ngữ với Never, Rarely, Not only."],
    ["noun-clauses", "Mệnh đề danh ngữ", "Mệnh đề danh ngữ đóng vai trò như danh từ: làm chủ ngữ, tân ngữ hoặc bổ ngữ. Thường bắt đầu bằng that, what, whether, if, wh-words. Trong câu hỏi gián tiếp, mệnh đề giữ trật tự câu khẳng định.", "What he said surprised me. I wonder where she lives.", "Viết ba câu có mệnh đề danh ngữ làm chủ ngữ, tân ngữ và bổ ngữ."],
    ["formal-email", "Viết email trang trọng", "Email trang trọng có tiêu đề rõ, lời chào phù hợp, mục đích nêu ngay đầu, nội dung ngắn gọn và lời kết lịch sự. Dear Sir or Madam thường kết bằng Yours faithfully; Dear Mr/Ms + họ thường kết bằng Yours sincerely (cách dùng Anh – Anh). Tránh từ viết tắt thân mật.", "Subject: Request for information about the summer course. Dear Ms Smith, I am writing to ask about...", "Viết email trang trọng 100 từ hỏi thông tin về một khóa học."],
  ],
  history: [
    ["united-nations", "Liên Hợp Quốc và trật tự thế giới", "Liên Hợp Quốc được thành lập năm 1945 với mục tiêu duy trì hòa bình, an ninh quốc tế và thúc đẩy hợp tác. Các cơ quan chính gồm Đại hội đồng, Hội đồng Bảo an, Ban Thư kí. Việt Nam trở thành thành viên Liên Hợp Quốc ngày 20/9/1977.", "Các tổ chức chuyên môn như UNESCO, WHO, UNICEF thuộc hệ thống Liên Hợp Quốc.", "Nêu một đóng góp của Việt Nam trong hoạt động của Liên Hợp Quốc."],
    ["ho-chi-minh-journey", "Hồ Chí Minh và hành trình tìm đường cứu nước", "Ngày 5/6/1911, Nguyễn Tất Thành rời bến Nhà Rồng ra đi tìm đường cứu nước. Năm 1920, Người tiếp cận Luận cương của Lênin về vấn đề dân tộc và thuộc địa. Đầu năm 1930, Người chủ trì hội nghị hợp nhất các tổ chức cộng sản thành Đảng Cộng sản Việt Nam.", "Trong hành trình, Người làm nhiều nghề để sống và tìm hiểu các nước.", "Lập trục thời gian hành trình 1911–1930 với bốn mốc."],
    ["foreign-relations", "Đối ngoại Việt Nam thời kì Đổi mới", "Từ năm 1986, Việt Nam thực hiện chính sách đối ngoại rộng mở, đa phương hóa, đa dạng hóa. Năm 1995, Việt Nam bình thường hóa quan hệ với Hoa Kỳ và gia nhập ASEAN. Năm 2007, Việt Nam trở thành thành viên Tổ chức Thương mại Thế giới (WTO).", "Gia nhập WTO giúp hàng hóa Việt Nam tiếp cận thị trường rộng hơn.", "Nêu hai tác động của hội nhập quốc tế đối với đời sống người dân."],
  ],
  geography: [
    ["natural-resources", "Tài nguyên thiên nhiên và sử dụng hợp lí", "Việt Nam có tài nguyên đa dạng: đất, nước, rừng, khoáng sản, biển. Khai thác quá mức gây suy thoái, cạn kiệt. Sử dụng hợp lí gồm khai thác đi đôi với bảo vệ, tái tạo, ứng dụng công nghệ tiết kiệm và tuân thủ quy định pháp luật.", "Trồng rừng thay thế sau khai thác giúp duy trì tài nguyên rừng.", "Đề xuất hai biện pháp sử dụng tài nguyên nước hợp lí ở địa phương."],
    ["tourism", "Du lịch Việt Nam", "Việt Nam có tài nguyên du lịch tự nhiên và văn hóa phong phú, nhiều di sản thế giới như Vịnh Hạ Long (ghi danh năm 1994), Phong Nha – Kẻ Bàng (2003). Du lịch bền vững cần bảo vệ môi trường, tôn trọng văn hóa địa phương và mang lại lợi ích cho cộng đồng.", "Du khách mang túi rác về khi tham quan hang động giúp bảo vệ cảnh quan.", "Thiết kế lịch trình du lịch hai ngày ở địa phương em theo hướng bền vững."],
    ["population-labour", "Dân số và lao động Việt Nam", "Dân số Việt Nam đã vượt 100 triệu người, đang bước vào giai đoạn già hóa. Nguồn lao động dồi dào, nhưng cần nâng cao trình độ chuyên môn, kĩ năng. Lao động đang chuyển dịch từ nông nghiệp sang công nghiệp và dịch vụ.", "Nhiều lao động trẻ chuyển đến các khu công nghiệp, đô thị tìm việc.", "Nêu hai thách thức và hai cơ hội của dân số Việt Nam hiện nay."],
  ],
  informatics: [
    ["css", "CSS và định dạng trang web", "CSS định dạng giao diện trang web: màu sắc, phông chữ, bố cục. Quy tắc CSS gồm bộ chọn và các khai báo thuộc tính: giá trị. Tách nội dung (HTML) và trình bày (CSS) giúp dễ bảo trì. Chú ý độ tương phản và cỡ chữ để mọi người đều đọc được.", "h1 { color: navy; font-size: 32px; } làm tiêu đề màu xanh đậm, cỡ 32px.", "Viết quy tắc CSS cho đoạn văn: phông không chân, cỡ 18px, giãn dòng 1,5."],
    ["ip-dns", "Địa chỉ IP, giao thức và tên miền", "Mỗi thiết bị trên Internet có địa chỉ IP: IPv4 dài 32 bit, IPv6 dài 128 bit. Giao thức TCP/IP quy định cách truyền dữ liệu. Hệ thống tên miền (DNS) chuyển tên miền dễ nhớ thành địa chỉ IP. HTTPS mã hóa dữ liệu giữa trình duyệt và máy chủ.", "Khi gõ một tên miền, máy tính hỏi DNS để biết địa chỉ IP của máy chủ.", "Giải thích vì sao cần IPv6 khi số thiết bị kết nối tăng nhanh."],
    ["machine-learning", "Học máy nhập môn", "Học máy là nhánh của trí tuệ nhân tạo, giúp máy tính học từ dữ liệu thay vì lập trình từng quy tắc. Học có giám sát dùng dữ liệu đã gán nhãn để dự đoán. Dữ liệu thiên lệch có thể dẫn đến kết quả thiên lệch; cần kiểm tra, đánh giá mô hình.", "Bộ lọc thư rác học từ nhiều email đã được đánh dấu “rác” hoặc “không rác”.", "Nêu một ứng dụng học máy em gặp và một rủi ro cần lưu ý."],
  ],
  technology: [
    ["electronic-components", "Linh kiện điện tử cơ bản", "Điện trở hạn chế dòng điện, đơn vị ôm (Ω). Tụ điện tích và phóng điện. Diode cho dòng điện đi qua chủ yếu theo một chiều; LED là diode phát quang. Transistor dùng để khuếch đại tín hiệu hoặc làm công tắc điện tử.", "Mắc điện trở nối tiếp với LED để tránh LED bị hỏng do dòng quá lớn.", "Vẽ mạch gồm pin, điện trở, LED và giải thích vai trò của điện trở."],
    ["logic-gates", "Điện tử số và cổng logic", "Điện tử số xử lí tín hiệu hai mức 0 và 1. Cổng AND cho 1 khi tất cả đầu vào là 1; cổng OR cho 1 khi ít nhất một đầu vào là 1; cổng NOT đảo tín hiệu. Bảng chân lí liệt kê đầu ra cho mọi tổ hợp đầu vào.", "Đèn chỉ sáng khi cả hai công tắc đều bật là mô hình cổng AND.", "Lập bảng chân lí cho cổng OR hai đầu vào."],
    ["embedded-systems", "Vi điều khiển và hệ thống nhúng", "Hệ thống nhúng là máy tính chuyên dụng gắn trong thiết bị, thường dùng vi điều khiển. Hệ thống gồm cảm biến (đầu vào), bộ xử lí và cơ cấu chấp hành (đầu ra). Ví dụ: máy giặt, điều hòa, robot. Có thể học qua bo mạch giáo dục như Arduino.", "Hệ thống tưới cây: cảm biến độ ẩm đo đất khô, vi điều khiển bật máy bơm.", "Thiết kế sơ đồ khối cho hệ thống bật đèn tự động khi trời tối."],
  ],
  civics: [
    ["economic-integration", "Tham khảo: hội nhập kinh tế quốc tế", "Hội nhập kinh tế quốc tế là gắn kết nền kinh tế quốc gia với kinh tế khu vực và thế giới qua thương mại, đầu tư, hiệp định. Việt Nam là thành viên WTO và tham gia nhiều hiệp định thương mại tự do. Hội nhập mang lại cơ hội và cạnh tranh gay gắt hơn.", "Hiệp định thương mại tự do giúp giảm thuế cho hàng xuất khẩu của Việt Nam.", "Nêu một cơ hội và một thách thức của hội nhập đối với doanh nghiệp nhỏ."],
    ["family-law", "Tham khảo: quyền và nghĩa vụ trong hôn nhân và gia đình", "Theo Luật Hôn nhân và gia đình năm 2014, nam từ đủ 20 tuổi, nữ từ đủ 18 tuổi được kết hôn; việc kết hôn do hai bên tự nguyện. Vợ chồng bình đẳng về quyền và nghĩa vụ. Con cái có bổn phận kính trọng, chăm sóc cha mẹ; cha mẹ không được phân biệt đối xử giữa các con.", "Tảo hôn (kết hôn khi chưa đủ tuổi) là hành vi bị pháp luật nghiêm cấm.", "Tìm hiểu một quyền của con trong gia đình theo pháp luật."],
    ["personal-data", "Tham khảo: quyền bảo vệ dữ liệu cá nhân", "Dữ liệu cá nhân gồm thông tin gắn với một người cụ thể như họ tên, số định danh, hình ảnh, vị trí. Người dùng có quyền được biết, đồng ý và yêu cầu xóa dữ liệu theo quy định. Hạn chế chia sẻ thông tin trên mạng; tra cứu văn bản pháp luật hiện hành về bảo vệ dữ liệu cá nhân.", "Ứng dụng xin quyền truy cập danh bạ không cần thiết thì có thể từ chối.", "Kiểm tra quyền truy cập của ba ứng dụng trên điện thoại và tắt quyền không cần."],
  ],
  "physical-education": [
    ["basketball-shot", "Bóng rổ: ném rổ một tay trên vai", "Ném rổ một tay trên vai: chân rộng bằng vai, bóng đặt trên lòng bàn tay thuận, tay kia đỡ bên. Duỗi chân và tay đồng thời, bật cổ tay để bóng xoáy ngược. Mắt nhìn vành rổ, giữ khuỷu tay hướng về rổ.", "Bóng xoáy ngược giúp bóng dễ rơi vào rổ khi chạm vành.", "Ném 20 quả từ vị trí ném phạt và ghi tỉ lệ thành công."],
    ["aerobics", "Thể dục nhịp điệu và aerobic", "Aerobic là các bài tập theo nhạc với cường độ vừa phải, kéo dài, giúp tăng sức bền tim mạch. Bài tập gồm khởi động, phần chính, thả lỏng. Chọn giày có đệm, mặt sàn phẳng, tăng dần cường độ.", "Bài aerobic 20 phút với nhạc khoảng 120–140 nhịp/phút phù hợp người mới tập.", "Biên soạn một bài aerobic 8 nhịp gồm bốn động tác."],
    ["heart-rate", "Đo nhịp tim và cường độ tập", "Nhịp tim cho biết cường độ vận động. Có thể đo ở cổ tay hoặc cổ trong 15 giây rồi nhân 4. Nhịp tim tối đa thường được ước tính khoảng 220 trừ tuổi. Cường độ vừa: thở nhanh nhưng vẫn nói chuyện được. Tổ chức Y tế Thế giới khuyến nghị trẻ 5–17 tuổi vận động trung bình đến mạnh trung bình 60 phút mỗi ngày.", "Đếm được 30 nhịp trong 15 giây thì nhịp tim là 120 lần/phút.", "Đo nhịp tim lúc nghỉ và sau 2 phút chạy tại chỗ, so sánh kết quả."],
  ],
  music: [
    ["music-industry", "Tham khảo: âm nhạc và công nghiệp giải trí", "Công nghiệp âm nhạc gồm sáng tác, sản xuất, phát hành, biểu diễn và truyền thông. Nền tảng phát trực tuyến thay đổi cách nghe và trả thù lao. Quyền tác giả bảo vệ người sáng tác; nghe, dùng nhạc hợp pháp là tôn trọng nghệ sĩ.", "Dùng nhạc có bản quyền làm nền video công khai cần xin phép hoặc dùng thư viện nhạc được cấp phép.", "Tìm hiểu các nghề trong một ê-kíp sản xuất âm nhạc."],
    ["lyric-writing", "Tham khảo: viết lời ca khúc", "Lời ca cần ý tưởng rõ, hình ảnh cụ thể và cấu trúc như đoạn – điệp khúc. Với tiếng Việt, dấu thanh ảnh hưởng đến cao độ khi hát; lời và giai điệu cần khớp để không bị “ngang”. Tránh sao chép lời của người khác.", "Tiếng mang thanh sắc thường hợp với nốt cao hơn tiếng mang thanh huyền.", "Viết bốn câu lời ca về trường em và thử hát theo một giai điệu đơn giản."],
    ["gongs", "Tham khảo: Không gian văn hóa Cồng chiêng Tây Nguyên", "Cồng chiêng gắn với đời sống tâm linh, lễ hội của các dân tộc Tây Nguyên. Mỗi chiếc cồng, chiêng giữ một âm, nhiều người cùng đánh tạo nên bản nhạc. Không gian văn hóa Cồng chiêng Tây Nguyên được UNESCO công nhận năm 2005.", "Trong lễ hội, dàn chiêng vừa đánh vừa di chuyển theo vòng tròn.", "Tìm hiểu một lễ hội có cồng chiêng và vai trò của âm nhạc trong lễ hội."],
  ],
  "visual-arts": [
    ["contemporary-art", "Tham khảo: nghệ thuật đương đại", "Nghệ thuật đương đại dùng nhiều hình thức: sắp đặt, trình diễn, video, nghệ thuật số. Tác phẩm thường đặt câu hỏi về xã hội, môi trường, bản sắc. Khi xem, chú ý ý tưởng, chất liệu và cách người xem tham gia.", "Một tác phẩm sắp đặt dùng rác nhựa nhặt từ bờ biển để nói về ô nhiễm.", "Xem một tác phẩm đương đại và viết ba câu hỏi nó gợi ra cho em."],
    ["ux-design", "Tham khảo: thiết kế trải nghiệm người dùng", "Thiết kế trải nghiệm người dùng tập trung vào việc sản phẩm dễ dùng, hữu ích và dễ tiếp cận. Quy trình gồm tìm hiểu người dùng, phác thảo, làm mẫu thử và kiểm tra với người thật. Thiết kế tốt chú ý người khuyết tật, ví dụ cỡ chữ và độ tương phản.", "Nút bấm đủ lớn trên điện thoại giúp người dùng không bấm nhầm.", "Phác giao diện một ứng dụng nhắc lịch học và hỏi ý kiến hai bạn."],
    ["museum-display", "Tham khảo: bảo tàng và trưng bày", "Trưng bày cần sắp xếp hiện vật theo chủ đề, có nhãn thông tin rõ và lối đi hợp lí. Ánh sáng, khoảng cách và độ cao giúp người xem quan sát thoải mái. Bảo tàng còn có nhiệm vụ bảo quản, nghiên cứu và giáo dục.", "Nhãn hiện vật ghi tên, niên đại, chất liệu và nguồn gốc.", "Thiết kế một góc trưng bày nhỏ ở lớp về chủ đề lịch sử địa phương."],
  ],
  "national-defense": [
    ["harmful-information", "Phòng, chống thông tin xấu độc trên mạng", "Thông tin xấu độc gồm tin giả, xuyên tạc, kích động gây chia rẽ hoặc gây hoang mang. Trước khi chia sẻ, kiểm tra nguồn, ngày đăng, đối chiếu với kênh chính thống. Không bình luận kích động; báo cáo nội dung vi phạm trên nền tảng.", "Ảnh cũ được đăng lại với chú thích sai để gây hoang mang là dạng tin giả thường gặp.", "Chọn một tin trên mạng và kiểm tra nguồn theo ba bước."],
    ["border-sovereignty", "Bảo vệ chủ quyền lãnh thổ và biên giới quốc gia", "Biên giới quốc gia là ranh giới xác định chủ quyền trên đất liền, trên biển, trên không và trong lòng đất. Bảo vệ biên giới là trách nhiệm của Nhà nước và toàn dân, kết hợp với giữ quan hệ hữu nghị với các nước láng giềng. Mọi tranh chấp cần giải quyết bằng biện pháp hòa bình.", "Hệ thống cột mốc biên giới đánh dấu đường biên giới trên đất liền.", "Nêu hai việc công dân có thể làm để góp phần bảo vệ chủ quyền quốc gia."],
    ["cpr", "Hồi sinh tim phổi cơ bản", "Khi gặp người bất tỉnh, không thở hoặc thở bất thường: bảo đảm an toàn hiện trường, gọi 115, bắt đầu ép tim. Ép ở giữa ngực, sâu khoảng 5–6 cm với người lớn, tốc độ 100–120 lần/phút, để ngực nảy lên hết sau mỗi lần ép. Dùng máy khử rung tự động (AED) nếu có. Nên học thực hành với người hướng dẫn được đào tạo.", "Ép tim theo nhịp một bài hát có tempo khoảng 100–120 nhịp/phút giúp giữ đúng tốc độ.", "Ghi lại thứ tự các bước xử trí khi phát hiện người ngừng tim."],
  ],
  "career-experience": [
    ["cv-writing", "Viết CV và thư xin việc", "CV trình bày ngắn gọn thông tin liên hệ, học vấn, kinh nghiệm, kĩ năng, hoạt động. Thư xin việc giải thích lí do ứng tuyển và sự phù hợp với vị trí. Thông tin phải trung thực, có ví dụ cụ thể, không lỗi chính tả.", "Thay vì “có kĩ năng lãnh đạo”, ghi “trưởng ban tổ chức hội trại 120 học sinh”.", "Viết CV một trang cho bản thân với ba hoạt động nổi bật."],
    ["interview-prep", "Chuẩn bị phỏng vấn", "Phỏng vấn tuyển sinh hoặc tuyển dụng cần tìm hiểu về tổ chức, chuẩn bị câu trả lời có ví dụ. Có thể dùng cách STAR: tình huống, nhiệm vụ, hành động, kết quả. Trang phục phù hợp, đến đúng giờ, lắng nghe và đặt câu hỏi.", "Khi được hỏi về khó khăn đã vượt qua, kể một tình huống cụ thể theo STAR.", "Tập trả lời câu hỏi “Hãy giới thiệu về bản thân” trong 1 phút."],
    ["independent-finance", "Quản lí tài chính khi bắt đầu tự lập", "Khi tự lập, cần lập ngân sách hằng tháng cho tiền nhà, ăn uống, đi lại, học tập và tiết kiệm. Theo dõi chi tiêu, giữ quỹ dự phòng, cẩn trọng với vay tiêu dùng và lừa đảo. Đọc kĩ hợp đồng thuê nhà, việc làm trước khi kí.", "Ghi chép chi tiêu bằng ứng dụng giúp phát hiện khoản chi không cần thiết.", "Lập ngân sách tháng giả định cho sinh viên năm nhất với thu nhập 4 triệu đồng."],
  ],
};
