export const gradeEightMoreLessons = {
  math: [
    ["linear-functions", "Hàm số bậc nhất và đồ thị", "Hàm số bậc nhất có dạng y = ax + b với a khác 0. Đồ thị là một đường thẳng; a gọi là hệ số góc, b là tung độ gốc. Để vẽ, chỉ cần xác định hai điểm thuộc đồ thị. Hai đường thẳng có cùng hệ số góc và khác tung độ gốc thì song song.", "y = 2x + 1 đi qua (0; 1) và (1; 3).", "Vẽ đồ thị y = −x + 2 và cho biết đồ thị cắt trục hoành tại điểm nào."],
    ["linear-equations", "Phương trình bậc nhất một ẩn", "Phương trình bậc nhất một ẩn có dạng ax + b = 0 với a khác 0, có nghiệm duy nhất x = −b/a. Khi giải, chuyển hạng tử sang vế kia thì đổi dấu; nhân hoặc chia hai vế cho cùng một số khác 0. Thay nghiệm vào phương trình để kiểm tra.", "3x − 6 = 0 nên 3x = 6, x = 2. Kiểm tra: 3·2 − 6 = 0.", "Giải 2(x − 1) = x + 3 và kiểm tra lại nghiệm."],
    ["thales", "Định lí Thalès và đường trung bình", "Nếu một đường thẳng song song với một cạnh của tam giác và cắt hai cạnh còn lại thì nó định ra trên hai cạnh đó những đoạn thẳng tương ứng tỉ lệ. Đường trung bình nối trung điểm hai cạnh, song song với cạnh thứ ba và bằng nửa cạnh ấy.", "Tam giác có cạnh đáy 10 cm thì đường trung bình song song với đáy dài 5 cm.", "Dùng định lí Thalès giải thích cách đo chiều rộng một con sông mà không cần qua sông."],
  ],
  science: [
    ["acids-bases", "Acid, base và thang pH", "Acid có vị chua, làm quỳ tím hóa đỏ; base làm quỳ tím hóa xanh. Thang pH đo độ acid: pH < 7 là acid, pH = 7 trung tính, pH > 7 là base. Không nếm, ngửi trực tiếp hóa chất; đeo kính và găng khi làm thí nghiệm.", "Nước chanh có pH khoảng 2; nước xà phòng có pH lớn hơn 7.", "Dự đoán màu quỳ tím khi nhúng vào giấm và vào nước vôi trong."],
    ["density", "Khối lượng riêng", "Khối lượng riêng D = m/V cho biết khối lượng của một đơn vị thể tích, đơn vị kg/m³ hoặc g/cm³. Nước có khối lượng riêng khoảng 1000 kg/m³. Vật có khối lượng riêng nhỏ hơn chất lỏng thì nổi, lớn hơn thì chìm.", "Khối gỗ 200 g có thể tích 250 cm³ nên D = 0,8 g/cm³ và nổi trên nước.", "Đo khối lượng và thể tích một vật nhỏ ở nhà, tính khối lượng riêng."],
    ["nervous-system", "Hệ thần kinh và giác quan", "Hệ thần kinh gồm bộ phận trung ương (não, tủy sống) và bộ phận ngoại biên (dây thần kinh). Phản xạ là phản ứng của cơ thể trả lời kích thích qua hệ thần kinh. Bảo vệ mắt: đọc sách cách mắt khoảng 25–30 cm, đủ sáng, nghỉ mắt sau thời gian dài nhìn màn hình.", "Rụt tay lại khi chạm vật nóng là phản xạ.", "Ghi thời gian dùng màn hình của em trong một ngày và đề xuất cách nghỉ mắt."],
  ],
  literature: [
    ["tang-poetry", "Thơ Đường luật", "Thơ thất ngôn bát cú Đường luật có tám câu, mỗi câu bảy chữ; thất ngôn tứ tuyệt có bốn câu. Bài bát cú thường có bố cục đề, thực, luận, kết; hai câu thực và hai câu luận đối nhau. Thơ thường gieo vần bằng ở cuối các câu 1, 2, 4, 6, 8.", "“Qua Đèo Ngang” của Bà Huyện Thanh Quan là bài thất ngôn bát cú.", "Tìm cặp câu đối trong một bài thơ Đường luật và chỉ ra các từ đối nhau."],
    ["historical-fiction", "Truyện lịch sử", "Truyện lịch sử dựa trên sự kiện, nhân vật có thật nhưng có hư cấu chi tiết, lời thoại. Khi đọc, chú ý bối cảnh, nhân vật và thông điệp của tác giả. Không coi mọi chi tiết trong truyện là sử liệu chính xác.", "Một truyện về Quang Trung có thể tưởng tượng lời nói của nhân vật dù sự kiện chính có thật.", "Chọn một chi tiết trong truyện lịch sử và tra cứu xem chi tiết đó có trong sử liệu không."],
    ["imitative-words", "Từ tượng hình và từ tượng thanh", "Từ tượng hình gợi hình ảnh, dáng vẻ, trạng thái: lom khom, lênh khênh, lấp lánh. Từ tượng thanh mô phỏng âm thanh: róc rách, ào ào, tích tắc. Hai loại từ này làm câu văn sinh động, giàu sức gợi.", "“Dòng suối róc rách chảy qua những tảng đá lấp lánh” có cả từ tượng thanh và tượng hình.", "Viết đoạn văn ba câu tả cơn mưa, dùng ít nhất hai từ tượng thanh."],
  ],
  english: [
    ["sentence-types", "Câu đơn, câu ghép và câu phức", "Câu đơn có một mệnh đề độc lập. Câu ghép nối hai mệnh đề độc lập bằng and, but, or, so. Câu phức có mệnh đề phụ bắt đầu bằng when, because, although, if. Dùng đa dạng loại câu giúp bài viết mạch lạc.", "I was tired, so I went to bed early. Although it rained, we played football.", "Viết lại hai câu đơn thành một câu ghép và một câu phức."],
    ["present-simple-future", "Hiện tại đơn cho lịch trình", "Hiện tại đơn có thể diễn tả sự việc tương lai theo lịch trình, thời gian biểu cố định như tàu xe, lịch học, chương trình. Thường có mốc thời gian đi kèm.", "The train leaves at 7 a.m. tomorrow. The film starts at 8 p.m.", "Viết ba câu về lịch trình của chuyến tham quan sắp tới."],
    ["articles", "Mạo từ a, an và the", "A/an dùng trước danh từ đếm được số ít chưa xác định. An đứng trước từ bắt đầu bằng âm nguyên âm: an apple, an hour; a đứng trước âm phụ âm: a university. The dùng khi người nghe biết rõ vật được nói đến hoặc vật duy nhất.", "I saw a dog. The dog was very friendly. The sun is hot.", "Điền a, an hoặc the vào năm câu tự viết về lớp học."],
  ],
  history: [
    ["bourgeois-revolutions", "Các cuộc cách mạng tư sản tiêu biểu", "Cách mạng tư sản Anh (thế kỉ XVII), Chiến tranh giành độc lập ở Bắc Mỹ với Tuyên ngôn Độc lập 1776 và Cách mạng Pháp 1789 đã xóa bỏ hoặc hạn chế chế độ phong kiến, mở đường cho chủ nghĩa tư bản. Tuyên ngôn Nhân quyền và Dân quyền (1789) nêu tư tưởng tự do, bình đẳng.", "Ngày 14/7/1789, quần chúng Paris tấn công ngục Bastille, mở đầu Cách mạng Pháp.", "Nêu một tư tưởng trong Tuyên ngôn Nhân quyền và Dân quyền còn giá trị hôm nay."],
    ["french-invasion", "Thực dân Pháp xâm lược Việt Nam", "Năm 1858, liên quân Pháp – Tây Ban Nha tấn công Đà Nẵng, mở đầu cuộc xâm lược. Triều Nguyễn lần lượt kí các hiệp ước nhượng bộ, đến Hiệp ước Patenôtre (1884) thì Việt Nam bị đặt dưới ách cai trị của Pháp. Năm 1885, vua Hàm Nghi ra chiếu Cần vương, phát động phong trào kháng chiến.", "Nhân dân Nam Kì tự động kháng Pháp dù triều đình đã kí hiệp ước nhượng đất.", "Lập trục thời gian từ 1858 đến 1885 với ba sự kiện chính."],
    ["world-war-one", "Chiến tranh thế giới thứ nhất", "Chiến tranh thế giới thứ nhất diễn ra từ năm 1914 đến 1918 giữa hai khối: phe Liên minh (Đức, Áo – Hung…) và phe Hiệp ước (Anh, Pháp, Nga…). Chiến tranh gây thiệt hại to lớn về người và của. Trong chiến tranh, Cách mạng tháng Mười Nga năm 1917 thành công.", "Chiến tranh hào ở mặt trận phía Tây khiến hàng triệu binh lính thương vong.", "Nêu hai hậu quả của chiến tranh đối với đời sống người dân."],
  ],
  geography: [
    ["vietnam-position", "Vị trí địa lí và phạm vi lãnh thổ Việt Nam", "Việt Nam nằm ở rìa phía đông bán đảo Đông Dương, trong khu vực Đông Nam Á, nội chí tuyến bán cầu Bắc. Lãnh thổ gồm vùng đất, vùng biển và vùng trời. Đường bờ biển dài khoảng 3.260 km. Vị trí này tạo khí hậu nhiệt đới ẩm gió mùa và thuận lợi giao lưu quốc tế.", "Nhờ nằm trên tuyến hàng hải quốc tế, Việt Nam có điều kiện phát triển cảng biển.", "Nêu hai thuận lợi và một khó khăn do vị trí địa lí mang lại."],
    ["sea-islands", "Biển đảo Việt Nam", "Vùng biển Việt Nam gồm nội thủy, lãnh hải (rộng 12 hải lí), vùng tiếp giáp lãnh hải, vùng đặc quyền kinh tế (200 hải lí tính từ đường cơ sở) và thềm lục địa. Việt Nam có nhiều đảo, quần đảo, trong đó có quần đảo Hoàng Sa và Trường Sa. Biển giàu tài nguyên hải sản, dầu khí và tiềm năng du lịch.", "Một hải lí bằng 1.852 m, nên 12 hải lí khoảng 22 km.", "Kể ba nguồn lợi từ biển và một việc làm để bảo vệ môi trường biển."],
    ["biodiversity-vn", "Sinh vật và đa dạng sinh học Việt Nam", "Việt Nam có đa dạng sinh học cao với nhiều hệ sinh thái: rừng nhiệt đới, rừng ngập mặn, rạn san hô. Nhiều loài quý hiếm đang bị đe dọa do phá rừng, săn bắt. Các vườn quốc gia và khu bảo tồn giúp bảo vệ loài; Cúc Phương là vườn quốc gia đầu tiên (1962).", "Rừng ngập mặn bảo vệ bờ biển khỏi sóng và là nơi sinh sản của nhiều loài thủy sản.", "Tìm hiểu một loài quý hiếm ở Việt Nam và nguyên nhân bị đe dọa."],
  ],
  informatics: [
    ["computer-history", "Lịch sử phát triển máy tính", "Máy tính phát triển qua các thế hệ: dùng đèn điện tử, transistor, mạch tích hợp và bộ vi xử lí. Mỗi thế hệ làm máy nhỏ hơn, nhanh hơn, tiết kiệm điện hơn. Ngày nay máy tính có mặt trong điện thoại, ô tô và thiết bị gia dụng.", "Máy tính đầu tiên dùng đèn điện tử chiếm cả căn phòng; điện thoại ngày nay mạnh hơn nhiều.", "So sánh một máy tính em dùng với máy tính thế hệ đầu về kích thước và tốc độ."],
    ["image-editing", "Chỉnh sửa ảnh cơ bản", "Phần mềm chỉnh sửa ảnh cho phép cắt ảnh, điều chỉnh độ sáng, tương phản và làm việc với lớp (layer). Lớp giúp chỉnh từng phần mà không ảnh hưởng phần khác. Luôn lưu bản gốc; không chỉnh ảnh để gây hiểu lầm hay xúc phạm người khác.", "Cắt bỏ phần thừa của ảnh để chủ thể nổi bật hơn.", "Chỉnh một bức ảnh phong cảnh: cắt bố cục và điều chỉnh độ sáng, ghi lại các bước."],
    ["copyright", "Bản quyền và ghi nguồn tài nguyên số", "Tác phẩm như ảnh, nhạc, bài viết, phần mềm được bảo hộ quyền tác giả. Khi dùng, cần xin phép hoặc dùng tài nguyên có giấy phép phù hợp và ghi nguồn. Một số tài nguyên dùng giấy phép Creative Commons với điều kiện riêng.", "Dùng ảnh có giấy phép CC BY thì phải ghi tên tác giả.", "Tìm một hình ảnh có giấy phép sử dụng tự do và viết dòng ghi nguồn đúng."],
  ],
  technology: [
    ["materials", "Vật liệu cơ khí", "Vật liệu cơ khí gồm kim loại đen (thép, gang – hợp kim của sắt và carbon), kim loại màu (đồng, nhôm) và phi kim loại (chất dẻo, cao su). Gang có hàm lượng carbon lớn hơn 2,14%, cứng nhưng giòn; thép dẻo dai hơn. Chọn vật liệu theo tính chất và công dụng.", "Dây điện dùng lõi đồng vì dẫn điện tốt, vỏ nhựa vì cách điện.", "Kể ba đồ vật trong nhà và cho biết vật liệu chính của từng đồ vật."],
    ["electric-circuits", "Mạch điện và an toàn điện", "Mạch điện cơ bản gồm nguồn, dây dẫn, thiết bị đóng cắt và tải tiêu thụ. Cầu chì, aptomat bảo vệ mạch khi quá tải hoặc ngắn mạch. Không chạm vào dây điện hở; khi có người bị điện giật, phải ngắt nguồn trước khi cứu.", "Aptomat tự ngắt khi cắm quá nhiều thiết bị công suất lớn cùng lúc.", "Vẽ sơ đồ mạch điện gồm pin, công tắc và bóng đèn."],
    ["hand-tools", "Gia công cơ khí bằng tay", "Gia công bằng tay gồm đo, vạch dấu, cưa, dũa, khoan. Vật cần gia công phải được kẹp chặt. Đeo kính bảo hộ, giữ tay cách xa lưỡi cưa, dọn phoi bằng chổi chứ không bằng tay. Chỉ thực hành khi có giáo viên hướng dẫn.", "Vạch dấu trước khi cưa giúp đường cắt thẳng và đúng kích thước.", "Liệt kê dụng cụ cần để cắt một thanh gỗ dài 20 cm và các lưu ý an toàn."],
  ],
  civics: [
    ["diligent-work", "Lao động cần cù, sáng tạo", "Cần cù là chăm chỉ, kiên trì làm việc; sáng tạo là tìm cách làm mới, hiệu quả hơn. Cả hai giúp nâng cao kết quả học tập và lao động. Sáng tạo không phải đi tắt bỏ qua quy trình an toàn.", "Một bạn thiết kế thời gian biểu học bằng màu sắc để dễ theo dõi.", "Nêu một cách làm sáng tạo hơn cho một việc em thường làm."],
    ["hazard-prevention", "Phòng ngừa tai nạn vũ khí, cháy nổ và chất độc hại", "Pháp luật nghiêm cấm tàng trữ, sử dụng trái phép vũ khí, vật liệu nổ và chất độc hại. Không tự chế, mua bán, sử dụng pháo nổ; không nhặt, nghịch vật lạ nghi là bom mìn. Khi phát hiện vật nghi nguy hiểm, tránh xa và báo cơ quan chức năng.", "Thấy vật kim loại lạ khi đào đất, đánh dấu từ xa và báo chính quyền địa phương.", "Viết ba lời nhắc an toàn cho em nhỏ về vật lạ và hóa chất."],
    ["labour-rights", "Quyền và nghĩa vụ lao động của công dân", "Công dân có quyền làm việc, lựa chọn nghề nghiệp và nghĩa vụ lao động để nuôi sống bản thân, đóng góp cho xã hội. Pháp luật bảo vệ người chưa thành niên: người từ đủ 13 đến dưới 15 tuổi chỉ được làm công việc nhẹ theo danh mục quy định. Cưỡng bức lao động là vi phạm pháp luật.", "Phụ giúp gia đình việc nhà vừa sức là trách nhiệm lao động phù hợp lứa tuổi.", "Tìm hiểu một công việc người lớn trong gia đình em làm và quyền lợi họ được hưởng."],
  ],
  "physical-education": [
    ["football-skills", "Bóng đá: dẫn bóng và sút cầu môn", "Dẫn bóng bằng má trong hoặc mu bàn chân, bóng sát chân, mắt quan sát xung quanh. Khi sút, đặt chân trụ cạnh bóng, mũi chân hướng về đích, chạm bóng bằng mu bàn chân. Không đá vào người, mang giày phù hợp.", "Chân trụ đặt quá xa bóng thường làm cú sút bay cao.", "Tập dẫn bóng qua năm cọc và ghi thời gian ba lần."],
    ["shuttlecock", "Đá cầu: tâng và chuyền cầu", "Đá cầu cần sự khéo léo, phản xạ và thăng bằng. Các kĩ thuật cơ bản: tâng cầu bằng đùi, bằng má trong bàn chân, chuyền cầu cho bạn. Khởi động kĩ cổ chân, gối; tập ở mặt sân bằng phẳng.", "Tâng cầu bằng má trong luân phiên hai chân giúp cân đối cơ thể.", "Đếm số lần tâng cầu liên tiếp nhiều nhất và đặt mục tiêu cải thiện."],
    ["warm-up-stretch", "Khởi động và giãn cơ đúng cách", "Khởi động trước khi tập bằng các động tác vận động nhẹ, xoay khớp, tăng dần cường độ. Giãn cơ sau khi tập: giữ tư thế 15–30 giây, thở đều, không nhún mạnh. Giãn cơ đúng giúp giảm căng cứng và chấn thương.", "Chạy nhẹ 3 phút, xoay cổ chân, gối, hông trước khi đá bóng.", "Thiết kế bài khởi động 5 phút cho tiết thể dục."],
  ],
  music: [
    ["accidentals", "Dấu hóa: thăng, giáng, bình", "Dấu thăng (#) nâng cao độ nốt lên nửa cung, dấu giáng (b) hạ xuống nửa cung, dấu bình hủy tác dụng của dấu thăng hoặc giáng. Dấu hóa bất thường chỉ có tác dụng trong ô nhịp nơi nó xuất hiện.", "Pha thăng cao hơn Pha nửa cung; trên đàn phím là phím đen bên phải Pha.", "Tìm trong một bản nhạc hai nốt có dấu hóa và gọi tên chúng."],
    ["film-music", "Âm nhạc trong phim", "Nhạc phim tạo không khí, gợi cảm xúc và dẫn dắt người xem. Nhạc nhanh, mạnh thường dùng trong cảnh hồi hộp; nhạc chậm, nhẹ cho cảnh lắng đọng. Âm thanh hiệu ứng và im lặng cũng là công cụ kể chuyện.", "Tắt tiếng một đoạn phim hồi hộp sẽ thấy cảm giác căng thẳng giảm hẳn.", "Chọn một đoạn phim ngắn, mô tả nhạc nền và cảm xúc nó tạo ra."],
    ["don-ca-tai-tu", "Đờn ca tài tử Nam Bộ", "Đờn ca tài tử là loại hình âm nhạc dân gian Nam Bộ, kết hợp hát và đàn, thường biểu diễn trong sinh hoạt cộng đồng. Nhạc cụ gồm đàn kìm, đàn tranh, đàn cò, đàn bầu, guitar phím lõm. Nghệ thuật Đờn ca tài tử Nam Bộ được UNESCO ghi danh năm 2013.", "Người chơi tài tử thường biểu diễn ngẫu hứng trong các buổi gặp gỡ.", "Nghe một bài đờn ca tài tử và nêu hai nhạc cụ em nhận ra."],
  ],
  "visual-arts": [
    ["packaging", "Thiết kế bao bì", "Bao bì bảo vệ sản phẩm và truyền tải thông tin: tên, công dụng, thành phần, hạn dùng. Thiết kế tốt có bố cục rõ, màu sắc phù hợp với sản phẩm và dễ nhận biết. Nên cân nhắc vật liệu thân thiện môi trường.", "Bao bì nước cam dùng màu cam và hình quả cam để nhận biết nhanh.", "Thiết kế mặt trước hộp đựng bánh với tên, hình và một thông tin chính."],
    ["renaissance", "Mĩ thuật Phục hưng", "Phục hưng (thế kỉ XIV–XVI, khởi đầu ở Italy) đề cao con người, nghiên cứu giải phẫu và luật xa gần. Tác phẩm tiêu biểu: “Mona Lisa” của Leonardo da Vinci, tượng “David” và tranh trần nhà nguyện Sistine của Michelangelo.", "Luật xa gần giúp tranh Phục hưng tạo chiều sâu không gian trên mặt phẳng.", "Quan sát một tác phẩm Phục hưng và chỉ ra yếu tố tạo chiều sâu."],
    ["portrait-proportions", "Vẽ chân dung: tỉ lệ khuôn mặt", "Khuôn mặt người có tỉ lệ cơ bản: mắt nằm khoảng giữa chiều cao đầu; khoảng cách giữa hai mắt xấp xỉ chiều rộng một mắt; tai nằm trong khoảng từ lông mày đến chóp mũi. Phác hình bằng đường trục trước khi vẽ chi tiết.", "Vẽ đường dọc giữa mặt và đường ngang ở giữa đầu để đặt mắt đúng vị trí.", "Vẽ chân dung một người thân bằng các đường trục tỉ lệ."],
  ],
  "national-defense": [
    ["drug-prevention", "Tham khảo: phòng, chống ma túy", "Đây là kĩ năng an toàn mở rộng. Ma túy gây nghiện, tổn hại não và sức khỏe, có thể được ngụy trang trong kẹo, nước uống, thuốc lá điện tử. Từ chối dứt khoát mọi lời mời “thử một lần”, không nhận đồ ăn uống của người lạ và báo người lớn khi bị dụ dỗ.", "Khi được mời hút thử thuốc lá điện tử không rõ nguồn gốc, nói “không” và rời đi.", "Viết ba câu từ chối dứt khoát khi bị mời dùng chất lạ."],
    ["disaster-safety", "Tham khảo: an toàn khi bão, lũ", "Theo dõi thông báo chính thức của cơ quan phòng chống thiên tai. Chuẩn bị đèn pin, nước sạch, đồ ăn khô, thuốc. Không lội qua dòng nước chảy xiết, tránh xa dây điện bị đứt. Sơ tán theo hướng dẫn của chính quyền.", "Nước chảy xiết sâu đến đầu gối có thể làm người lớn mất thăng bằng.", "Cùng gia đình lập danh sách đồ dùng thiết yếu khi có bão."],
    ["burn-first-aid", "Tham khảo: sơ cứu bỏng nhẹ", "Với bỏng nhiệt nhẹ, làm mát vùng bỏng dưới vòi nước sạch mát khoảng 20 phút. Tháo nhẫn, đồng hồ trước khi sưng. Không bôi kem đánh răng, nước mắm, đá lạnh trực tiếp. Bỏng rộng, bỏng sâu hoặc bỏng mặt cần gọi 115 hoặc đến cơ sở y tế.", "Bị nước sôi bắn vào tay: xả dưới vòi nước mát rồi che bằng gạc sạch.", "Ghi lại các bước sơ cứu bỏng nhẹ và dán ở gần bếp."],
  ],
  "career-experience": [
    ["online-friendship", "Ứng xử trong tình bạn và trên mạng", "Ứng xử trên mạng cần tôn trọng như ngoài đời: không bình luận xúc phạm, không chia sẻ ảnh, thông tin của bạn khi chưa được đồng ý. Khi có mâu thuẫn, trao đổi trực tiếp, bình tĩnh. Báo người lớn khi bị bắt nạt qua mạng.", "Trước khi đăng ảnh nhóm, hỏi ý kiến các bạn trong ảnh.", "Viết ba quy tắc ứng xử cho nhóm chat của lớp."],
    ["occupational-safety", "Nghề nghiệp và an toàn lao động", "Mỗi nghề có yêu cầu riêng về kĩ năng, sức khỏe và an toàn lao động. Trang bị bảo hộ như mũ, găng, kính giúp giảm tai nạn. Tìm hiểu nghề cần biết cả rủi ro, không chỉ thu nhập.", "Thợ hàn cần mặt nạ bảo vệ mắt khỏi tia hồ quang.", "Chọn một nghề và liệt kê thiết bị bảo hộ cần có."],
    ["needs-wants", "Tự chủ chi tiêu: phân biệt cần và muốn", "Nhu cầu cần thiết là thứ không thể thiếu cho cuộc sống, học tập; mong muốn là thứ thích có nhưng không bắt buộc. Trước khi mua, tự hỏi: mình có thật sự cần, có thể chờ hay dùng thứ khác không. Ghi chép chi tiêu giúp hiểu thói quen của bản thân.", "Vở học là nhu cầu; bút màu phiên bản giới hạn thường là mong muốn.", "Phân loại mười món em muốn mua thành “cần” và “muốn”."],
  ],
};
