export const gradeSixMoreLessons = {
  math: [
    ["decimals", "Số thập phân và làm tròn", "Số thập phân gồm phần nguyên và phần thập phân, ngăn bởi dấu phẩy. So sánh hai số thập phân bằng cách so phần nguyên trước, rồi lần lượt từng hàng phần mười, phần trăm. Làm tròn đến hàng nào thì xét chữ số ngay bên phải hàng đó: từ 5 trở lên thì cộng thêm 1 vào hàng làm tròn, nhỏ hơn 5 thì giữ nguyên.", "3,47 làm tròn đến hàng phần mười là 3,5. 0,5 lớn hơn 0,45 vì ở hàng phần mười 5 > 4.", "Làm tròn 12,364 đến hàng phần trăm và giải thích chữ số nào quyết định kết quả."],
    ["percentages", "Tỉ số phần trăm trong đời sống", "Tỉ số phần trăm của a và b là a : b × 100%. Muốn tìm m% của một số, nhân số đó với m rồi chia cho 100. Phần trăm giúp so sánh các nhóm có tổng khác nhau; luôn hỏi “phần trăm của cái gì”.", "Lớp có 40 bạn, 10 bạn đeo kính: tỉ số là 10 : 40 × 100% = 25%. 20% của 150.000đ là 30.000đ.", "Một áo giá 200.000đ được giảm 15%. Tính số tiền giảm và số tiền phải trả."],
    ["data-charts", "Thu thập dữ liệu và biểu đồ cột", "Dữ liệu có thể là số (chiều cao, điểm) hoặc không phải số (màu yêu thích). Bảng thống kê ghi các giá trị và số lần xuất hiện. Biểu đồ cột có các cột rộng bằng nhau; trục số lượng chia đều và thường bắt đầu từ 0 để không phóng đại chênh lệch.", "Khảo sát 30 bạn: 12 thích bóng đá, 10 thích cầu lông, 8 thích bơi. Cột bóng đá cao nhất, nhưng chỉ chiếm 40% số bạn.", "Khảo sát 10 người thân về món ăn sáng, lập bảng thống kê và vẽ biểu đồ cột."],
  ],
  science: [
    ["measurement", "Đo lường và chọn dụng cụ đo", "Đơn vị đo chuẩn: chiều dài là mét (m), khối lượng là kilôgam (kg), thời gian là giây (s); nhiệt độ hằng ngày thường đo bằng độ C. Trước khi đo, ước lượng rồi chọn dụng cụ có giới hạn đo và độ chia nhỏ nhất phù hợp. Đặt mắt nhìn vuông góc với vạch chia khi đọc kết quả.", "Đo chiều dài bút chì dùng thước có độ chia nhỏ nhất 1 mm; đo chiều dài lớp học nên dùng thước cuộn.", "Chọn dụng cụ để đo khối lượng một quả táo và thời gian chạy 60 m; giải thích lựa chọn."],
    ["forces", "Lực và tác dụng của lực", "Lực là tác dụng đẩy hoặc kéo của vật này lên vật khác, đơn vị là newton (N). Lực có thể làm vật thay đổi tốc độ, đổi hướng chuyển động hoặc biến dạng. Có lực tiếp xúc như lực ma sát và lực không tiếp xúc như trọng lực, lực hút của nam châm.", "Đá quả bóng làm bóng chuyển động; nam châm hút đinh sắt mà không cần chạm vào.", "Tìm hai ví dụ lực ma sát có ích và một ví dụ ma sát gây hao mòn."],
    ["energy", "Năng lượng và tiết kiệm năng lượng", "Năng lượng có nhiều dạng: động năng, nhiệt năng, quang năng, điện năng, hóa năng. Năng lượng có thể chuyển từ dạng này sang dạng khác, nhưng luôn có một phần hao phí, thường dưới dạng nhiệt. Nguồn tái tạo như Mặt Trời, gió; nguồn không tái tạo như than, dầu mỏ.", "Bóng đèn biến điện năng thành quang năng và một phần nhiệt năng hao phí; đèn LED ít hao phí hơn đèn sợi đốt.", "Liệt kê ba thiết bị trong nhà và nêu dạng năng lượng mỗi thiết bị tạo ra."],
  ],
  literature: [
    ["luc-bat", "Thơ lục bát", "Lục bát gồm các cặp câu sáu tiếng và tám tiếng. Tiếng thứ sáu câu lục vần với tiếng thứ sáu câu bát; tiếng thứ tám câu bát vần với tiếng thứ sáu của câu lục tiếp theo. Nhịp thường chẵn (2/2/2), giọng thơ mềm mại, gần lời ăn tiếng nói dân gian.", "Ca dao “Trâu ơi ta bảo trâu này / Trâu ra ngoài ruộng trâu cày với ta”: “này” vần với “cày”.", "Chép một cặp lục bát em thích, gạch chân các tiếng hiệp vần."],
    ["memoir", "Đọc kí và hồi kí", "Kí ghi chép người thật, việc thật, kết hợp kể, tả và bộc lộ cảm xúc. Hồi kí là dạng kí người viết kể lại trải nghiệm của chính mình, thường ở ngôi thứ nhất. Khi đọc, phân biệt sự việc được ghi lại với suy nghĩ, đánh giá của người viết.", "Câu “Tôi vẫn nhớ buổi sáng đầu tiên đến trường” mở ra lời hồi tưởng ngôi thứ nhất.", "Viết ba câu hồi kí về một ngày đáng nhớ, có một câu thể hiện cảm xúc."],
    ["word-structure", "Từ đơn, từ phức và từ đa nghĩa", "Từ đơn có một tiếng; từ phức có hai tiếng trở lên. Từ ghép có các tiếng quan hệ về nghĩa; từ láy có các tiếng lặp âm, vần hoặc cả hai. Từ đa nghĩa có nghĩa gốc và nghĩa chuyển; dựa vào ngữ cảnh để xác định nghĩa.", "“Nhà” là từ đơn, “nhà cửa” là từ ghép, “xinh xắn” là từ láy. “Chân” trong “chân bàn” là nghĩa chuyển.", "Tìm hai từ láy tả âm thanh và đặt câu với mỗi từ."],
  ],
  english: [
    ["can-ability", "Can và can't: nói về khả năng", "Can + động từ nguyên mẫu diễn tả khả năng; động từ sau can không thêm -s. Phủ định dùng can't (cannot). Câu hỏi đưa can lên trước chủ ngữ: Can you swim? Trả lời ngắn: Yes, I can / No, I can't.", "She can play the guitar, but she can't sing well.", "Viết ba câu về điều em làm được và một điều em đang học để làm được."],
    ["possessives", "Tính từ sở hữu và sở hữu cách 's", "Tính từ sở hữu đứng trước danh từ: my, your, his, her, its, our, their. Sở hữu cách thêm 's sau danh từ chỉ người: Lan's bag. Phân biệt its (của nó) với it's (it is).", "This is my brother. His name is Nam. Nam's school is near our house.", "Giới thiệu ba thành viên gia đình bằng tính từ sở hữu và sở hữu cách."],
    ["imperatives", "Câu mệnh lệnh và nội quy", "Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu, không có chủ ngữ: Open your book. Phủ định dùng Don't + động từ. Thêm please để lịch sự. Câu mệnh lệnh thường dùng trong nội quy, hướng dẫn.", "Please be quiet in the library. Don't run in the corridor.", "Viết năm câu nội quy cho phòng học, gồm hai câu phủ định."],
  ],
  history: [
    ["india-china", "Ấn Độ và Trung Quốc cổ đại", "Ấn Độ cổ đại hình thành trên lưu vực sông Ấn và sông Hằng, để lại chữ Phạn, đạo Bà La Môn và đạo Phật. Trung Quốc cổ đại phát triển ở lưu vực Hoàng Hà và Trường Giang; năm 221 TCN, Tần Thủy Hoàng thống nhất Trung Quốc. Người Trung Quốc có nhiều phát minh như giấy, la bàn, thuốc súng.", "Giấy giúp lưu giữ và truyền bá chữ viết rộng rãi hơn so với thẻ tre.", "Chọn một phát minh cổ đại và nêu tác động của nó đến đời sống hiện nay."],
    ["greece-rome", "Hy Lạp và La Mã cổ đại", "Hy Lạp và La Mã nằm ven Địa Trung Hải, phát triển thủ công nghiệp và thương mại đường biển. Athens có nền dân chủ cổ đại, nhưng chỉ nam công dân tự do được tham gia. Thành tựu tiêu biểu gồm chữ cái Latinh, toán học, kiến trúc như đền Parthenon và đấu trường Colosseum.", "Định lí Pythagore là di sản toán học Hy Lạp vẫn được học hiện nay.", "Nêu một điểm giống và một điểm khác giữa dân chủ Athens và cách bầu ban cán sự lớp."],
    ["bac-thuoc", "Đấu tranh thời Bắc thuộc và chiến thắng Bạch Đằng", "Sau khi Âu Lạc mất độc lập, nhân dân liên tục khởi nghĩa: Hai Bà Trưng năm 40, Bà Triệu năm 248, Lý Bí năm 542 và lập nước Vạn Xuân năm 544. Năm 938, Ngô Quyền dùng trận địa cọc trên sông Bạch Đằng đánh tan quân Nam Hán, mở ra thời kì độc lập lâu dài.", "Trận Bạch Đằng tận dụng thủy triều: nhử thuyền giặc vào bãi cọc khi nước lên, đánh khi nước rút.", "Lập trục thời gian bốn sự kiện trên và nêu ý nghĩa của năm 938."],
  ],
  geography: [
    ["earth-structure", "Cấu tạo Trái Đất và mảng kiến tạo", "Trái Đất gồm ba lớp: vỏ, manti và nhân. Vỏ Trái Đất mỏng, chia thành các mảng kiến tạo di chuyển rất chậm. Ở ranh giới các mảng thường xảy ra động đất, núi lửa và hình thành núi.", "Nhật Bản nằm gần ranh giới các mảng nên thường có động đất.", "Giải thích vì sao các trận động đất mạnh thường tập trung ở một số khu vực nhất định."],
    ["climate-zones", "Các đới khí hậu trên Trái Đất", "Trái Đất có năm đới khí hậu: một đới nóng nằm giữa hai chí tuyến, hai đới ôn hòa và hai đới lạnh quanh hai cực. Nhiệt độ thay đổi chủ yếu do góc chiếu của tia sáng Mặt Trời theo vĩ độ. Việt Nam nằm trong đới nóng.", "Ở xích đạo, Mặt Trời chiếu gần thẳng góc nên nóng quanh năm; ở vùng cực, tia sáng xiên nên lạnh.", "So sánh nhiệt độ và cảnh quan giữa đới nóng và đới lạnh."],
    ["soil-life", "Đất và sinh vật trên Trái Đất", "Đất gồm chất khoáng, chất hữu cơ, nước và không khí. Chất hữu cơ tạo độ phì giúp cây phát triển. Sinh vật phân bố theo khí hậu: rừng mưa nhiệt đới nhiều tầng, hoang mạc có thực vật chịu hạn.", "Xương rồng có lá biến thành gai để giảm thoát hơi nước ở nơi khô hạn.", "Kể hai việc giúp bảo vệ đất ở vườn trường hoặc gia đình."],
  ],
  informatics: [
    ["networks", "Mạng máy tính và Internet", "Mạng máy tính là các thiết bị kết nối để chia sẻ dữ liệu và tài nguyên. Mạng gồm thiết bị đầu cuối, thiết bị kết nối như bộ định tuyến và phần mềm mạng; kết nối có thể có dây hoặc không dây. Internet là mạng toàn cầu, mang lại nhiều lợi ích nhưng cũng có rủi ro về thông tin sai và lừa đảo.", "Máy in dùng chung trong phòng học là ví dụ chia sẻ tài nguyên qua mạng.", "Kể hai lợi ích và hai rủi ro khi dùng Internet, kèm cách phòng tránh."],
    ["web-browsing", "Trang web, trình duyệt và siêu liên kết", "Trang web được xem bằng trình duyệt, mỗi trang có địa chỉ riêng. Siêu liên kết giúp chuyển đến trang hoặc nội dung khác. Máy tìm kiếm giúp tìm trang theo từ khóa, nhưng kết quả đầu tiên không chắc đúng nhất. Biểu tượng khóa bảo vệ đường truyền, không bảo đảm nội dung đáng tin.", "Tìm “vòng tuần hoàn nước lớp 6” sẽ hẹp hơn chỉ tìm “nước”.", "Chọn hai trang web về cùng một chủ đề và so sánh tác giả, ngày cập nhật."],
    ["mind-maps", "Sơ đồ tư duy và soạn thảo văn bản", "Sơ đồ tư duy đặt chủ đề ở trung tâm, các ý chính tỏa ra thành nhánh, ý phụ là nhánh con. Khi soạn thảo, định dạng kí tự (phông, cỡ, kiểu) và định dạng đoạn (căn lề, giãn dòng) giúp văn bản dễ đọc. Dùng định dạng thống nhất, không lạm dụng màu.", "Sơ đồ “Bảo vệ môi trường” có các nhánh: rác thải, nước, cây xanh.", "Vẽ sơ đồ tư duy cho kế hoạch học tập một tuần."],
  ],
  technology: [
    ["smart-home", "Ngôi nhà thông minh", "Ngôi nhà thông minh dùng thiết bị có cảm biến và điều khiển tự động hoặc từ xa. Hệ thống có thể gồm chiếu sáng, an ninh, điều hòa nhiệt độ và giải trí. Mục tiêu là tiện nghi, an toàn và tiết kiệm năng lượng; cần bảo mật mật khẩu thiết bị.", "Đèn hành lang tự bật khi cảm biến phát hiện người và tự tắt sau vài phút.", "Đề xuất một thiết bị tự động giúp tiết kiệm điện ở nhà em và giải thích cách hoạt động."],
    ["home-appliances", "Sử dụng đồ dùng điện an toàn", "Mỗi đồ dùng điện có thông số định mức như điện áp 220 V và công suất. Dùng đúng điện áp, đọc hướng dẫn trước khi sử dụng. Không chạm thiết bị khi tay ướt, không kéo dây để rút phích, không cắm quá nhiều thiết bị vào một ổ.", "Nồi cơm ghi 220 V – 700 W nghĩa là dùng với điện áp 220 V, công suất khoảng 700 W.", "Kiểm tra một đồ dùng điện ở nhà, ghi lại thông số và một lưu ý an toàn."],
    ["nutrition", "Dinh dưỡng và bữa ăn hợp lí", "Thực phẩm chia thành các nhóm: giàu tinh bột, giàu chất đạm, giàu chất béo, giàu vitamin và chất khoáng. Bữa ăn hợp lí có đủ các nhóm với lượng phù hợp. Nên ăn đủ bữa, đặc biệt bữa sáng, uống đủ nước và hạn chế đồ ngọt, đồ chiên.", "Bữa cơm có cơm, cá, rau luộc và chuối cung cấp đủ các nhóm chất.", "Lên thực đơn một bữa ăn tối cân đối cho gia đình em."],
  ],
  civics: [
    ["caring", "Yêu thương con người", "Yêu thương con người là quan tâm, chia sẻ và giúp đỡ người khác bằng hành động phù hợp. Yêu thương cần tôn trọng mong muốn của người được giúp, không phô trương. Với việc vượt quá khả năng, hãy nhờ người lớn hỗ trợ.", "Chép bài giúp bạn nghỉ ốm và giảng lại phần bạn chưa hiểu.", "Ghi một việc làm thể hiện sự quan tâm em có thể làm trong tuần này."],
    ["danger-response", "Ứng phó với tình huống nguy hiểm", "Tình huống nguy hiểm có thể từ tự nhiên như bão, lũ, hoặc từ con người như cháy, bị người lạ dụ dỗ. Nguyên tắc chung: giữ bình tĩnh, rời khỏi nơi nguy hiểm, báo người lớn tin cậy. Nhớ các số khẩn cấp 113 (công an), 114 (cứu hỏa), 115 (cấp cứu).", "Khi người lạ rủ đi cùng, từ chối, đi đến chỗ đông người và báo thầy cô hoặc bố mẹ.", "Viết ba bước em sẽ làm khi phát hiện khói ở nhà."],
    ["thrift", "Tiết kiệm trong sinh hoạt hằng ngày", "Tiết kiệm là sử dụng hợp lí tiền bạc, thời gian, điện, nước và đồ dùng. Tiết kiệm khác keo kiệt: vẫn chi cho việc cần thiết và giúp người khác khi có thể. Thói quen nhỏ như tắt đèn, khóa vòi nước tạo thay đổi lớn.", "Tận dụng mặt sau giấy nháp và giữ gìn sách vở để dùng lâu hơn.", "Theo dõi một tuần các khoản chi tiêu nhỏ và tìm một khoản có thể giảm."],
  ],
  "physical-education": [
    ["sprint", "Chạy cự li ngắn: xuất phát và tăng tốc", "Chạy cự li ngắn cần khởi động kĩ. Xuất phát cao: chân thuận phía trước, thân hơi đổ về trước, nghe hiệu lệnh mới chạy. Khi chạy, đánh tay phối hợp, chạy trên nửa trước bàn chân, giữ đúng ô chạy. Về đích chạy chậm dần, không dừng đột ngột.", "Khi nghe “Vào chỗ – Sẵn sàng – Chạy”, chỉ rời vạch ở khẩu lệnh cuối.", "Nhờ bạn quan sát tư thế xuất phát của em và ghi một điểm cần sửa."],
    ["long-jump", "Nhảy xa và tiếp đất an toàn", "Nhảy xa gồm bốn giai đoạn: chạy đà, giậm nhảy, bay trên không và tiếp đất. Giậm nhảy bằng một chân trên ván, tiếp đất bằng hai chân, chùng gối để giảm chấn. Chỉ tập khi hố cát đã được xới và kiểm tra, không có vật cứng.", "Chạy đà đều nhịp giúp chân giậm rơi đúng ván hơn là chạy thật nhanh từ xa.", "Đếm số bước chạy đà phù hợp với em và ghi lại sau ba lần thử."],
    ["hydration", "Uống nước và nghỉ ngơi khi vận động", "Khi vận động, cơ thể mất nước qua mồ hôi. Uống nước từng ngụm nhỏ trước, trong và sau khi tập. Nếu chóng mặt, buồn nôn, đau ngực hoặc khó thở, dừng ngay và báo giáo viên. Tránh tập nặng ngay sau khi ăn no hoặc dưới nắng gắt.", "Mang bình nước cá nhân và uống vài ngụm sau mỗi lượt chạy.", "Lập danh sách những dấu hiệu cơ thể cần dừng tập và báo người lớn."],
  ],
  music: [
    ["staff-notes", "Khuông nhạc và khóa Son", "Khuông nhạc có năm dòng kẻ và bốn khe, đếm từ dưới lên. Bảy tên nốt là Đô, Rê, Mi, Pha, Son, La, Si. Khóa Son đặt ở dòng 2, nên nốt trên dòng 2 là Son. Từ dòng 1 lên: Mi (dòng 1), Pha (khe 1), Son (dòng 2), La (khe 2), Si (dòng 3).", "Nốt nằm ở khe giữa dòng 2 và dòng 3 là La.", "Vẽ khuông nhạc, đặt khóa Son và ghi năm nốt từ Mi đến Si."],
    ["singing-breath", "Hát đúng và giữ hơi", "Hát tốt cần tư thế thẳng lưng, vai thả lỏng. Hít hơi bằng mũi xuống bụng, thở ra đều theo câu hát. Khởi động giọng bằng bài luyện thanh nhẹ, phát âm rõ lời. Không gào to, nghỉ khi giọng mệt hoặc đau họng.", "Ngân “ma – me – mi – mo – mu” theo thang âm nhẹ trước khi hát.", "Chọn một câu hát dài, đánh dấu chỗ lấy hơi và tập hát hai lần."],
    ["folk-songs", "Dân ca Việt Nam", "Dân ca do nhân dân sáng tác và lưu truyền qua truyền miệng, gắn với lao động, sinh hoạt và lễ hội. Mỗi vùng có làn điệu riêng: quan họ Bắc Ninh, hò Huế, lí Nam Bộ. Dân ca quan họ Bắc Ninh được UNESCO ghi danh năm 2009.", "Hò kéo lưới có nhịp đều giúp người lao động phối hợp động tác.", "Nghe một bài dân ca và nêu bài đó thuộc vùng nào, gắn với hoạt động gì."],
  ],
  "visual-arts": [
    ["lines-forms", "Đường nét và hình khối", "Nét có thể thẳng, cong, gấp khúc, đậm hoặc mảnh; mỗi loại gợi cảm giác khác nhau. Hình có hai chiều; khối có ba chiều và chiếm không gian. Ánh sáng tạo vùng sáng, tối giúp diễn tả khối trên mặt giấy.", "Nét cong mềm gợi sóng nước; nét gấp khúc gợi tia chớp.", "Vẽ một quả cam và tô đậm nhạt để thể hiện khối tròn."],
    ["theme-drawing", "Vẽ tranh theo chủ đề", "Vẽ theo chủ đề bắt đầu từ ý tưởng, rồi phác bố cục với hình chính lớn, rõ và hình phụ hỗ trợ. Màu sắc nên có gam chủ đạo. Ghi lại vài phác thảo nhỏ trước khi chọn bố cục chính.", "Chủ đề “Ngày hội ở trường” có thể chọn nhóm bạn kéo co làm hình chính.", "Phác hai bố cục khác nhau cho chủ đề “Gia đình em” và chọn một."],
    ["prehistoric-art", "Mĩ thuật thời tiền sử", "Người tiền sử vẽ và khắc trên vách hang, thường là thú vật và cảnh săn bắt. Màu được làm từ đất, than, khoáng chất. Các hang Lascaux (Pháp) và Altamira (Tây Ban Nha) nổi tiếng với tranh vẽ thú. Những hình vẽ này là tư liệu tìm hiểu đời sống con người xa xưa.", "Hình bò rừng ở Altamira dùng gờ đá tự nhiên để tạo cảm giác khối.", "Vẽ một con vật theo phong cách tranh hang động bằng ít nét và màu đất."],
  ],
  "national-defense": [
    ["traffic-safety", "Tham khảo: an toàn giao thông khi đến trường", "Đây là kĩ năng an toàn mở rộng. Đi bộ trên vỉa hè, sang đường ở vạch kẻ, quan sát hai phía. Đội mũ bảo hiểm đúng cách khi ngồi sau xe máy, cài quai. Học sinh chưa đủ tuổi theo quy định không điều khiển xe máy.", "Đội mũ đặt ngang trán, quai cài vừa khít dưới cằm.", "Vẽ sơ đồ đường từ nhà đến trường và đánh dấu một điểm cần chú ý."],
    ["drowning-prevention", "Tham khảo: phòng tránh đuối nước", "Chỉ bơi ở nơi an toàn, có người lớn hoặc cứu hộ. Không chơi gần ao, hồ, sông một mình. Khi thấy người đuối nước, không tự nhảy xuống nếu không được huấn luyện; hô to gọi người lớn và ném vật nổi như phao, can nhựa.", "Ném chai nhựa có nắp kín cho người đang chới với là cách hỗ trợ an toàn hơn nhảy xuống.", "Kể tên ba vật nổi có thể dùng để giúp người đuối nước từ trên bờ."],
    ["home-fire-safety", "Tham khảo: an toàn với điện và lửa trong nhà", "Không cắm quá nhiều thiết bị vào một ổ, không để vật dễ cháy gần bếp hoặc bóng đèn nóng. Khi có cháy, báo động, gọi 114, thoát ra theo lối an toàn, cúi thấp dưới khói, không dùng thang máy. Không quay lại lấy đồ.", "Dùng khăn ướt che mũi miệng và bò thấp vì khói nóng bốc lên trên.", "Cùng gia đình xác định hai lối thoát khi có cháy trong nhà."],
  ],
  "career-experience": [
    ["emotions", "Nhận diện và điều chỉnh cảm xúc", "Cảm xúc như vui, buồn, giận, lo đều bình thường. Gọi tên cảm xúc giúp hiểu bản thân. Có thể điều chỉnh bằng hít thở sâu, đếm chậm, đi bộ hoặc nói chuyện với người tin cậy, thay vì làm tổn thương người khác.", "Khi tức giận vì bị trêu, hít thở chậm năm lần trước khi trả lời.", "Ghi lại một lần em buồn hoặc giận và cách em đã vượt qua."],
    ["friendship", "Làm quen và giữ tình bạn", "Làm quen bắt đầu bằng lời chào, giới thiệu bản thân và hỏi về sở thích chung. Tình bạn bền khi tôn trọng, giữ lời hứa và biết xin lỗi. Bạn tốt không ép làm điều sai.", "Rủ một bạn mới cùng nhóm làm bài và hỏi bạn thích môn nào.", "Kể ba điều em có thể làm để là người bạn tốt hơn."],
    ["traditional-crafts", "Tìm hiểu nghề truyền thống", "Nghề truyền thống như gốm, dệt, mây tre đan gắn với làng nghề và văn hóa địa phương. Người làm nghề cần khéo léo, kiên trì và hiểu nguyên liệu. Khi tham quan, tuân theo hướng dẫn an toàn và tôn trọng sản phẩm.", "Làng gốm Bát Tràng (Hà Nội) nổi tiếng với gốm men, có lịch sử hàng trăm năm.", "Tìm hiểu một nghề truyền thống ở địa phương và ghi ba bước làm sản phẩm."],
  ],
};
