export const gradeSevenMoreLessons = {
  math: [
    ["real-numbers", "Số vô tỉ, căn bậc hai và số thực", "Căn bậc hai số học của số a không âm là số x không âm sao cho x² = a. Số vô tỉ viết được dưới dạng số thập phân vô hạn không tuần hoàn, ví dụ √2. Số hữu tỉ và số vô tỉ hợp thành tập số thực; mỗi số thực ứng với một điểm trên trục số.", "√16 = 4 vì 4² = 16 và 4 ≥ 0. √2 ≈ 1,414 là số vô tỉ.", "Sắp xếp các số 1,5; √2; 3/2; 1,41 theo thứ tự tăng dần."],
    ["inverse-proportion", "Tỉ lệ thức và tỉ lệ nghịch", "Tỉ lệ thức là đẳng thức của hai tỉ số a/b = c/d; khi đó a·d = b·c. Hai đại lượng tỉ lệ nghịch khi tích x·y luôn bằng một hằng số khác 0: một đại lượng tăng bao nhiêu lần thì đại lượng kia giảm bấy nhiêu lần.", "Nếu năng suất mỗi người như nhau, 3 người làm xong việc trong 12 ngày thì 6 người làm xong trong 6 ngày.", "Một xe đi quãng đường cố định: vận tốc 40 km/h hết 3 giờ. Tính thời gian khi đi 60 km/h."],
    ["polynomials", "Biểu thức đại số và đa thức một biến", "Biểu thức đại số gồm số, chữ và các phép toán. Đa thức một biến là tổng các đơn thức của cùng một biến; bậc của đa thức là số mũ lớn nhất. Nghiệm của đa thức P(x) là giá trị x làm P(x) = 0.", "P(x) = 2x² − 3x + 1 có bậc 2. P(1) = 2 − 3 + 1 = 0 nên x = 1 là nghiệm.", "Tính giá trị của Q(x) = x² − 4 tại x = 2 và x = −2, rồi kết luận về nghiệm."],
  ],
  science: [
    ["elements", "Nguyên tố hóa học và kí hiệu", "Nguyên tố hóa học là tập hợp các nguyên tử có cùng số proton trong hạt nhân. Mỗi nguyên tố có kí hiệu gồm một hoặc hai chữ cái, chữ đầu viết hoa: H, O, C, Na, Fe. Bảng tuần hoàn sắp xếp nguyên tố theo chiều tăng dần điện tích hạt nhân.", "Mọi nguyên tử có 8 proton đều thuộc nguyên tố oxygen, kí hiệu O.", "Viết kí hiệu của năm nguyên tố em gặp trong đời sống và nêu nơi gặp."],
    ["magnets", "Nam châm và từ trường", "Nam châm có hai cực Bắc (N) và Nam (S). Hai cực cùng tên đẩy nhau, khác tên hút nhau. Không gian quanh nam châm có từ trường; bên ngoài nam châm, đường sức từ đi ra từ cực Bắc và đi vào cực Nam. Kim la bàn là nam châm nhỏ chỉ hướng Bắc – Nam địa lí.", "Rắc mạt sắt quanh thanh nam châm sẽ thấy hình ảnh các đường sức từ.", "Dự đoán điều xảy ra khi đưa cực N của hai nam châm lại gần nhau và giải thích."],
    ["reproduction", "Sinh sản ở sinh vật", "Sinh sản vô tính tạo cơ thể mới không có sự kết hợp giao tử, ví dụ giâm cành, chiết cành, vi khuẩn phân đôi. Sinh sản hữu tính có sự kết hợp giao tử đực và cái, tạo con mang đặc điểm của cả bố và mẹ. Con người ứng dụng sinh sản vô tính để nhân giống nhanh cây trồng.", "Cành sắn cắm xuống đất mọc thành cây mới là sinh sản vô tính.", "So sánh ưu điểm của sinh sản vô tính và hữu tính trong trồng trọt."],
  ],
  literature: [
    ["essay-writing", "Đọc tùy bút và tản văn", "Tùy bút ghi lại cảm xúc, suy nghĩ của người viết một cách tự do, đậm dấu ấn cá nhân. Tản văn thường ngắn, giàu chất trữ tình, xuất phát từ những điều bình dị. Khi đọc, chú ý chi tiết được chọn và cảm xúc, suy ngẫm đi kèm.", "Thạch Lam viết về cốm như một thứ quà thanh nhã, gắn với hương lúa và nét văn hóa Hà Nội.", "Viết một đoạn tản văn ngắn về một món ăn quen thuộc, nêu cảm xúc của em."],
    ["proverbs", "Tục ngữ và kinh nghiệm dân gian", "Tục ngữ là câu nói ngắn gọn, có vần, nhịp, đúc kết kinh nghiệm về thiên nhiên, lao động và con người. Tục ngữ thường dùng hình ảnh cụ thể để nói điều khái quát. Khi vận dụng, cần hiểu đúng nghĩa và hoàn cảnh.", "“Chuồn chuồn bay thấp thì mưa, bay cao thì nắng, bay vừa thì râm” là kinh nghiệm dự báo thời tiết.", "Tìm hai câu tục ngữ về học tập và giải thích ý nghĩa."],
    ["numerals-adverbs", "Số từ và phó từ", "Số từ chỉ số lượng hoặc thứ tự của sự vật: hai, ba, thứ nhất. Phó từ đi kèm động từ, tính từ để bổ sung ý nghĩa thời gian (đã, đang, sẽ), mức độ (rất, khá), phủ định (không, chưa). Dùng đúng phó từ giúp câu chính xác hơn.", "“Em đã làm xong ba bài tập” có phó từ “đã” và số từ “ba”.", "Viết một đoạn ba câu về buổi học, gạch chân số từ và phó từ."],
  ],
  english: [
    ["time-prepositions", "Giới từ chỉ thời gian: in, on, at", "In dùng với tháng, năm, mùa, buổi trong ngày: in May, in 2025, in the morning. On dùng với ngày và thứ: on Monday, on 2 September. At dùng với giờ và một số cụm: at 7 o'clock, at night.", "My birthday is on 15 June. We have English at 8 a.m.", "Viết bốn câu về lịch sinh hoạt của em, mỗi câu dùng một giới từ thời gian."],
    ["as-as", "So sánh bằng: as ... as", "So sánh bằng dùng as + tính từ/trạng từ + as. Phủ định dùng not as ... as để nói kém hơn. Có thể dùng the same as hoặc different from để so sánh giống, khác.", "Nam is as tall as Minh. This book is not as interesting as that one.", "So sánh hai đồ vật trong phòng em bằng ba câu as ... as."],
    ["should-advice", "Lời khuyên với should và shouldn't", "Should + động từ nguyên mẫu dùng để khuyên nên làm gì; shouldn't để khuyên không nên. Động từ sau should không thêm -s. Câu hỏi xin lời khuyên: What should I do?", "You should drink more water. You shouldn't stay up late.", "Viết ba lời khuyên cho một bạn hay bị mệt khi đi học."],
  ],
  history: [
    ["early-independence", "Thời Ngô, Đinh, Tiền Lê", "Năm 939, Ngô Quyền xưng vương, đóng đô ở Cổ Loa. Đinh Bộ Lĩnh dẹp loạn mười hai sứ quân, lên ngôi năm 968, đặt quốc hiệu Đại Cồ Việt, đóng đô ở Hoa Lư. Năm 981, Lê Hoàn chỉ huy kháng chiến chống quân Tống thắng lợi.", "Việc đặt quốc hiệu và kinh đô khẳng định nền độc lập của quốc gia.", "Lập bảng tóm tắt ba triều đại: người sáng lập, kinh đô, sự kiện nổi bật."],
    ["early-le", "Thời Lê sơ và Bộ luật Hồng Đức", "Sau khởi nghĩa Lam Sơn, Lê Lợi lên ngôi năm 1428, lập triều Lê sơ. Dưới thời Lê Thánh Tông, nhà nước được củng cố, bộ luật Quốc triều hình luật (luật Hồng Đức) được ban hành, có điều khoản bảo vệ một số quyền lợi của phụ nữ. Giáo dục, khoa cử phát triển mạnh.", "Luật Hồng Đức cho phép con gái được hưởng phần tài sản thừa kế trong một số trường hợp.", "Nêu một điểm tiến bộ của luật Hồng Đức và lí do em đánh giá như vậy."],
    ["exploration", "Các cuộc phát kiến địa lí", "Cuối thế kỉ XV – đầu XVI, các nhà hàng hải châu Âu mở đường biển mới: Columbus đến châu Mỹ năm 1492, Vasco da Gama đến Ấn Độ năm 1498, đoàn thám hiểm của Magellan đi vòng quanh Trái Đất (1519–1522). Phát kiến mở rộng giao thương nhưng cũng dẫn đến xâm chiếm thuộc địa và buôn bán nô lệ.", "Chuyến đi của Magellan chứng minh Trái Đất hình cầu bằng thực tế hàng hải.", "Nêu một hệ quả tích cực và một hệ quả tiêu cực của phát kiến địa lí."],
  ],
  geography: [
    ["africa", "Châu Phi: thiên nhiên và dân cư", "Châu Phi có đường xích đạo đi qua gần giữa châu lục, nên phần lớn lãnh thổ nóng. Hoang mạc Sahara ở phía bắc là hoang mạc nóng lớn nhất thế giới; sông Nile chảy qua vùng khô hạn, nuôi dưỡng nền văn minh Ai Cập. Nhiều nước châu Phi có dân số trẻ, tăng nhanh.", "Dân cư Ai Cập tập trung dọc thung lũng sông Nile vì có nước và đất phù sa.", "Giải thích vì sao các thành phố lớn ở vùng khô hạn thường gần sông."],
    ["americas", "Châu Mỹ: địa hình và đô thị hóa", "Châu Mỹ trải dài từ vùng cực Bắc đến gần vùng cực Nam. Phía tây có hệ thống núi cao như dãy Rocky ở Bắc Mỹ và Andes ở Nam Mỹ. Rừng Amazon là rừng mưa nhiệt đới lớn nhất thế giới. Tỉ lệ dân thành thị ở châu Mỹ cao.", "Phá rừng Amazon làm giảm đa dạng sinh học và ảnh hưởng đến khí hậu.", "Kể hai vai trò của rừng Amazon đối với Trái Đất."],
    ["oceania-antarctica", "Châu Đại Dương và châu Nam Cực", "Phần lớn lục địa Australia khô hạn, dân cư tập trung ở ven biển phía đông và đông nam. Châu Nam Cực gần như bị băng phủ quanh năm, không có dân cư thường xuyên. Hiệp ước Nam Cực (1959) quy định châu lục này dùng cho mục đích hòa bình và nghiên cứu khoa học.", "Các trạm nghiên cứu ở Nam Cực đo băng để tìm hiểu biến đổi khí hậu.", "Giải thích vì sao dân cư Australia không phân bố đều."],
  ],
  informatics: [
    ["operating-systems", "Hệ điều hành và phần mềm ứng dụng", "Hệ điều hành quản lí phần cứng, tệp và cho phép chạy phần mềm ứng dụng. Ví dụ: Windows, macOS, Linux trên máy tính; Android, iOS trên điện thoại. Phần mềm ứng dụng phục vụ công việc cụ thể như soạn thảo, vẽ, nghe nhạc. Chỉ cài phần mềm từ nguồn tin cậy.", "Trình soạn thảo văn bản là phần mềm ứng dụng; nó cần hệ điều hành để chạy.", "Liệt kê ba phần mềm ứng dụng em dùng và cho biết hệ điều hành của thiết bị."],
    ["searching-algorithms", "Thuật toán tìm kiếm tuần tự và nhị phân", "Tìm kiếm tuần tự so sánh lần lượt từng phần tử cho đến khi tìm thấy hoặc hết dãy. Tìm kiếm nhị phân chỉ dùng cho dãy đã sắp xếp: so với phần tử giữa, rồi bỏ một nửa không chứa giá trị cần tìm. Với dãy dài, tìm kiếm nhị phân thường nhanh hơn nhiều.", "Tìm 7 trong dãy 1, 3, 5, 7, 9: phần tử giữa là 5, 7 > 5 nên chỉ xét 7, 9.", "Mô tả từng bước tìm số 15 trong dãy 2, 4, 8, 15, 16, 23, 42 bằng tìm kiếm nhị phân."],
    ["presentations", "Phần mềm trình chiếu", "Bài trình chiếu tốt có bố cục rõ: trang tiêu đề, nội dung, kết luận. Mỗi trang nên có ít chữ, ý ngắn, hình ảnh minh họa có ghi nguồn. Hiệu ứng chỉ dùng khi giúp làm rõ nội dung; chữ phải đủ lớn và tương phản với nền.", "Thay đoạn văn dài bằng ba gạch đầu dòng và một hình minh họa.", "Thiết kế dàn ý năm trang trình chiếu giới thiệu trường em."],
  ],
  technology: [
    ["forests", "Rừng và bảo vệ rừng", "Rừng điều hòa khí hậu, giữ đất, chống xói mòn, cung cấp gỗ và là nơi sống của nhiều loài. Bảo vệ rừng gồm trồng rừng, chăm sóc rừng, phòng cháy và không khai thác trái phép. Cây non cần được làm cỏ, tưới nước và bảo vệ khỏi gia súc.", "Rừng phòng hộ đầu nguồn giúp giảm lũ quét cho vùng hạ lưu.", "Đề xuất hai việc học sinh có thể làm để góp phần bảo vệ rừng."],
    ["animal-health", "Phòng bệnh cho vật nuôi", "Phòng bệnh cho vật nuôi gồm giữ chuồng sạch, khô, thoáng; cho ăn đủ chất; tiêm vaccine theo lịch. Khi vật nuôi có dấu hiệu bệnh như bỏ ăn, sốt, cần cách li và báo cán bộ thú y. Rửa tay sau khi tiếp xúc với vật nuôi.", "Tiêm vaccine dại cho chó, mèo giúp phòng bệnh cho cả vật nuôi và con người.", "Lập bảng ba việc chăm sóc hằng ngày cho một vật nuôi em biết."],
    ["soil-fertilizer", "Làm đất, bón phân và tưới nước", "Làm đất giúp đất tơi xốp, sạch cỏ dại. Phân hữu cơ (phân chuồng, phân xanh) cải tạo đất; phân vô cơ cung cấp chất dinh dưỡng nhanh. Bón lót trước khi trồng, bón thúc khi cây đang lớn. Tưới đủ ẩm, tránh úng; đeo găng tay khi dùng phân bón.", "Ủ vỏ rau củ thành phân hữu cơ giúp giảm rác và cải tạo đất trồng.", "Lập kế hoạch chăm sóc một chậu rau trong hai tuần."],
  ],
  civics: [
    ["active-learning", "Học tập tự giác, tích cực", "Học tập tự giác là chủ động học mà không cần nhắc nhở. Học tích cực là đặt câu hỏi, tìm cách giải, liên hệ thực tế. Có thể lập kế hoạch học tập, chia nhỏ mục tiêu và tự đánh giá kết quả hằng tuần.", "Tự ôn bài trước khi kiểm tra và ghi lại câu hỏi để hỏi thầy cô.", "Viết một mục tiêu học tập cụ thể cho tuần tới và cách kiểm tra."],
    ["school-violence", "Phòng, chống bạo lực học đường", "Bạo lực học đường gồm hành vi đánh đập, xúc phạm, cô lập, đe dọa, kể cả trên mạng. Khi bị bạo lực hoặc chứng kiến, cần giữ an toàn, báo thầy cô, cha mẹ. Không quay clip phát tán và không cổ vũ hành vi bạo lực.", "Khi thấy bạn bị nhóm khác trêu chọc, em có thể đưa bạn đi chỗ khác và báo giáo viên.", "Viết một quy tắc ứng xử giúp lớp em không có bạo lực."],
    ["money-management", "Quản lí tiền", "Quản lí tiền là biết lập kế hoạch thu chi, ưu tiên điều cần thiết và tiết kiệm. Có thể ghi sổ thu chi, chia tiền thành phần chi tiêu, tiết kiệm và chia sẻ. Tránh mua sắm theo cảm hứng hay áp lực bạn bè.", "Dành 20% tiền mừng tuổi để tiết kiệm mua sách.", "Lập bảng thu chi giả định cho một tháng và ghi khoản tiết kiệm."],
  ],
  "physical-education": [
    ["middle-distance", "Chạy cự li trung bình và phân phối sức", "Chạy cự li trung bình cần giữ tốc độ ổn định, phân phối sức hợp lí. Thở đều theo nhịp bước, giữ thân hơi đổ về trước, tay đánh tự nhiên. Không xuất phát quá nhanh; nếu đau ngực hoặc chóng mặt, dừng và báo giáo viên.", "Chạy 4 vòng sân với thời gian mỗi vòng gần bằng nhau tốt hơn vòng đầu quá nhanh.", "Ghi thời gian từng vòng trong một lần chạy và nhận xét độ đều."],
    ["throwing", "Ném bóng và phối hợp tay chân", "Ném bóng xa cần phối hợp: bước chân, xoay thân, vung tay và ra sức ở cổ tay. Mắt nhìn hướng ném. Chỉ ném khi khu vực phía trước không có người và theo hiệu lệnh giáo viên.", "Bước chân trái lên trước khi ném bằng tay phải giúp tăng lực ném.", "Nhờ bạn quan sát và nhận xét động tác bước chân khi em ném."],
    ["basketball-basics", "Bóng rổ: dẫn bóng và chuyền bóng", "Dẫn bóng bằng các đầu ngón tay, đẩy bóng xuống đất, mắt nhìn phía trước. Chuyền bóng bằng hai tay trước ngực: đẩy bóng thẳng về phía đồng đội. Chuyền đập đất giúp vượt qua người cản. Giữ khoảng cách an toàn với người khác.", "Dẫn bóng tay phải khi di chuyển sang phải, tay trái khi sang trái để bảo vệ bóng.", "Tập dẫn bóng 10 lần mỗi tay mà không nhìn bóng, ghi số lần mất bóng."],
  ],
  music: [
    ["c-major", "Gam Đô trưởng và cung, nửa cung", "Gam Đô trưởng gồm Đô, Rê, Mi, Pha, Son, La, Si, Đô. Khoảng cách giữa Mi – Pha và Si – Đô là nửa cung; các bậc liền kề khác cách nhau một cung. Nhận biết cung và nửa cung giúp hát đúng cao độ.", "Trên đàn phím, Mi và Pha nằm cạnh nhau, không có phím đen ở giữa.", "Hát gam Đô trưởng đi lên rồi đi xuống, đánh dấu vị trí nửa cung."],
    ["folk-instruments", "Nhạc cụ dân tộc Việt Nam", "Nhạc cụ dân tộc chia thành nhóm dây (đàn bầu, đàn tranh, đàn nguyệt), nhóm hơi (sáo trúc, kèn bầu) và nhóm gõ (trống, phách, đàn T'rưng). Đàn bầu chỉ có một dây, người chơi tạo cao độ bằng bồi âm và cần đàn.", "Tiếng sáo trúc thường gợi khung cảnh đồng quê, thanh bình.", "Nghe một bản nhạc có nhạc cụ dân tộc và đoán nhạc cụ đó thuộc nhóm nào."],
    ["round-singing", "Hát nối tiếp kiểu canon", "Canon là cách các nhóm cùng hát một giai điệu nhưng vào lệch nhau, tạo nhiều lớp âm thanh. Mỗi nhóm cần giữ nhịp chắc và nghe nhau để không lạc. Bài “Kìa con bướm vàng” thường được tập hát canon.", "Nhóm 1 hát câu đầu, khi sang câu thứ hai thì nhóm 2 bắt đầu câu đầu.", "Chia nhóm tập hát canon một bài quen thuộc và nhận xét nhóm nào giữ nhịp tốt."],
  ],
  "visual-arts": [
    ["printmaking", "Tranh in và kĩ thuật in đơn giản", "Tranh in dùng khuôn in để tạo nhiều bản giống nhau. Hình trên khuôn ngược chiều so với bản in. Tranh Đông Hồ được in từ ván khắc gỗ trên giấy dó quét hồ điệp. Có thể tập in bằng khuôn xốp, lá cây hoặc củ quả.", "Chữ khắc trên khuôn phải viết ngược thì bản in mới đọc được.", "Làm một khuôn in từ miếng xốp và in hoa văn lặp lại."],
    ["lettering", "Nghệ thuật chữ", "Chữ có nhiều kiểu: có chân, không chân, viết tay. Khi thiết kế chữ, chú ý độ đậm, khoảng cách giữa các chữ và độ dễ đọc. Kiểu chữ cần hợp với nội dung: chữ mềm mại cho thiệp, chữ rõ ràng cho biển báo.", "Tiêu đề báo tường dùng chữ in đậm, lớn để đọc được từ xa.", "Thiết kế tên của em bằng hai kiểu chữ khác nhau và so sánh cảm giác."],
    ["clay-sculpture", "Tạo hình khối bằng đất nặn", "Điêu khắc tạo ra tác phẩm ba chiều có thể quan sát từ nhiều phía. Nặn bắt đầu từ khối lớn, sau đó thêm chi tiết. Giữ đất ẩm khi làm, gắn các phần chắc chắn. Có thể dùng vật liệu tái chế làm lõi.", "Nặn con mèo: tạo khối thân, đầu, rồi thêm tai, đuôi.", "Nặn một con vật và quan sát nó từ ba hướng khác nhau."],
  ],
  "national-defense": [
    ["stranger-safety", "Tham khảo: phòng tránh bị dụ dỗ, bắt cóc", "Đây là kĩ năng an toàn mở rộng. Không đi theo hoặc nhận quà của người lạ, kể cả khi họ nói quen bố mẹ. Gia đình có thể thống nhất một “mật khẩu” riêng. Khi bị đeo bám, chạy đến nơi đông người và báo người lớn tin cậy.", "Người lạ nói “Mẹ cháu nhờ chú đón” nhưng không biết mật khẩu gia đình thì em không đi theo.", "Cùng gia đình thống nhất mật khẩu và người được phép đón em."],
    ["cycling-safety", "Tham khảo: an toàn khi đi xe đạp", "Kiểm tra phanh, lốp, đèn trước khi đi. Đội mũ bảo hiểm, đi bên phải, không dàn hàng ngang, không buông hai tay hay kéo đẩy xe khác. Giơ tay báo hiệu khi rẽ và quan sát phía sau.", "Phanh yếu cần sửa trước khi đi, không chờ đến khi xuống dốc.", "Lập danh sách kiểm tra xe đạp năm mục trước khi đến trường."],
    ["minor-first-aid", "Tham khảo: sơ cứu vết thương nhỏ", "Rửa tay trước khi sơ cứu. Rửa vết xước bằng nước sạch, dùng gạc sạch ép nhẹ để cầm máu, rồi băng lại. Vết thương sâu, chảy máu nhiều hoặc do vật bẩn gây ra cần đến cơ sở y tế; gọi 115 khi nặng.", "Bị trầy đầu gối khi chơi: rửa sạch, lau khô, dán băng cá nhân.", "Kiểm tra hộp sơ cứu ở nhà hoặc lớp và ghi những vật dụng còn thiếu."],
  ],
  "career-experience": [
    ["study-pressure", "Ứng phó với áp lực học tập", "Áp lực học tập có thể đến từ bài vở, kì vọng của gia đình và so sánh với bạn bè. Ứng phó bằng cách chia nhỏ việc, ngủ đủ, vận động, và chia sẻ với người tin cậy. Tìm hỗ trợ sớm khi thấy mất ngủ, chán nản kéo dài.", "Thay vì ôn cả chương trong một tối, chia thành ba buổi, mỗi buổi một phần.", "Liệt kê nguồn áp lực của em và một cách ứng phó cho mỗi nguồn."],
    ["volunteering", "Hoạt động thiện nguyện vừa sức", "Thiện nguyện là tự nguyện giúp đỡ cộng đồng mà không vì lợi ích riêng. Hoạt động vừa sức: quyên góp sách cũ, dọn vệ sinh khu phố, thăm người cao tuổi. Cần có người lớn đi cùng và tôn trọng người được giúp.", "Lớp tổ chức góp sách cũ tặng thư viện xã, có danh sách và biên bản bàn giao.", "Đề xuất một hoạt động thiện nguyện lớp em có thể làm và các bước thực hiện."],
    ["public-manners", "Văn hóa ứng xử nơi công cộng", "Nơi công cộng cần giữ trật tự, vệ sinh và tôn trọng người khác: xếp hàng, nói nhỏ, không xả rác, nhường chỗ cho người cần. Ứng xử văn minh cũng gồm việc không quay phim người khác khi chưa được đồng ý.", "Ở thư viện, tắt chuông điện thoại và nói chuyện nhỏ.", "Quan sát một nơi công cộng và ghi hai hành vi đẹp, một hành vi cần thay đổi."],
  ],
};
