export const gradeElevenMoreLessons = {
  math: [
    ["limits", "Giới hạn của dãy số và hàm số", "Dãy số có giới hạn L khi các số hạng tiến gần L tùy ý khi n đủ lớn. Một số giới hạn cơ bản: lim 1/n = 0, lim c = c. Giới hạn hàm số mô tả giá trị hàm tiến tới khi x tiến tới một điểm. Hàm số liên tục tại x₀ khi giới hạn tại đó bằng giá trị hàm.", "lim (2n + 1)/n = lim (2 + 1/n) = 2.", "Tính lim (3n − 2)/(n + 1) và giải thích từng bước."],
    ["exp-log", "Hàm số mũ và hàm số logarit", "Hàm số mũ y = aˣ với a > 0, a ≠ 1. Logarit cơ số a của b là số c sao cho aᶜ = b, kí hiệu log_a b. Một số tính chất: log_a(bc) = log_a b + log_a c; log_a aˣ = x. Hàm mũ mô tả tăng trưởng dân số, phân rã phóng xạ.", "log₂ 8 = 3 vì 2³ = 8.", "Tính log₃ 81 và log₁₀ 0,01."],
    ["space-perpendicular", "Quan hệ song song và vuông góc trong không gian", "Đường thẳng song song với mặt phẳng khi chúng không có điểm chung. Đường thẳng vuông góc với mặt phẳng khi nó vuông góc với hai đường thẳng cắt nhau nằm trong mặt phẳng đó. Hai mặt phẳng vuông góc khi một mặt phẳng chứa đường thẳng vuông góc với mặt phẳng kia.", "Cột nhà thẳng đứng vuông góc với mặt sàn nằm ngang.", "Tìm trong lớp học hai ví dụ đường thẳng vuông góc với mặt phẳng."],
  ],
  science: [
    ["electric-field", "Điện trường và tụ điện", "Điện trường là môi trường quanh điện tích, tác dụng lực lên điện tích khác. Cường độ điện trường E = F/q, đơn vị V/m. Tụ điện gồm hai bản dẫn cách điện, dùng tích điện; điện dung C = Q/U, đơn vị fara (F).", "Đèn flash máy ảnh dùng tụ điện để phóng điện nhanh tạo ánh sáng mạnh.", "Tính điện tích của tụ 10 μF khi đặt vào hiệu điện thế 12 V."],
    ["nitrogen-sulfur", "Nitrogen, sulfur và mưa acid", "Nitrogen chiếm khoảng 78% thể tích không khí, là thành phần của protein và phân bón. Sulfur dioxide (SO₂) và các oxide của nitrogen phát thải từ đốt nhiên liệu có thể tạo mưa acid. Mưa acid làm hại cây, ăn mòn công trình, chua đất và nước.", "Tượng đá vôi bị ăn mòn dần dưới tác động của mưa acid.", "Đề xuất hai biện pháp giảm phát thải gây mưa acid."],
    ["responses", "Cảm ứng ở sinh vật", "Cảm ứng là khả năng sinh vật tiếp nhận và phản ứng với kích thích. Ở thực vật, hướng động như ngọn cây hướng về ánh sáng, rễ hướng theo trọng lực. Ở động vật có hệ thần kinh, cảm ứng diễn ra nhanh dưới dạng phản xạ.", "Cây trồng cạnh cửa sổ nghiêng ngọn về phía ánh sáng.", "Thiết kế thí nghiệm đơn giản chứng minh cây hướng sáng."],
  ],
  literature: [
    ["modern-short-story", "Truyện ngắn hiện đại Việt Nam", "Truyện ngắn hiện đại chú trọng khắc họa tâm lí, số phận con người trong bối cảnh xã hội. Chú ý tình huống truyện, chi tiết nghệ thuật và điểm nhìn trần thuật. “Chí Phèo” của Nam Cao thể hiện bi kịch bị tước đoạt quyền làm người.", "Chi tiết bát cháo hành đánh thức khát vọng lương thiện của Chí Phèo.", "Phân tích một chi tiết nghệ thuật trong truyện ngắn em đã đọc."],
    ["drama-conflict", "Kịch: xung đột và lời thoại", "Kịch phản ánh đời sống qua hành động, lời thoại của nhân vật. Xung đột kịch là mâu thuẫn tạo nên hành động và kịch tính. Lời thoại gồm đối thoại, độc thoại, bàng thoại. “Vũ Như Tô” của Nguyễn Huy Tưởng đặt ra xung đột giữa khát vọng nghệ thuật và lợi ích nhân dân.", "Độc thoại nội tâm giúp bộc lộ suy nghĩ sâu kín của nhân vật.", "Xác định xung đột chính trong một trích đoạn kịch và các bên của xung đột."],
    ["modern-lyric", "Thơ trữ tình hiện đại", "Thơ hiện đại phá vỡ nhiều quy tắc thơ cũ, đề cao cái tôi cá nhân. “Vội vàng” của Xuân Diệu thể hiện tình yêu cuộc sống và ý thức về thời gian trôi. Khi đọc, chú ý cái tôi trữ tình, hình ảnh, nhịp thơ và từ ngữ mới lạ.", "Câu “Tôi muốn tắt nắng đi / Cho màu đừng nhạt mất” thể hiện khát vọng níu giữ vẻ đẹp.", "Chọn một khổ thơ hiện đại và phân tích cái tôi trữ tình."],
  ],
  english: [
    ["modal-deduction", "Động từ khuyết thiếu chỉ suy đoán", "Must + V dùng khi gần như chắc chắn điều gì đúng; can't + V khi chắc chắn không đúng; might/may/could + V khi có khả năng. Với quá khứ dùng must have + V3, can't have + V3, might have + V3.", "He must be tired after the match. She can't have seen the email.", "Viết ba câu suy đoán về một bạn vắng mặt hôm nay."],
    ["reporting-verbs", "Động từ tường thuật: advise, remind, suggest", "Một số động từ tường thuật đi với tân ngữ + to-infinitive: advise, remind, encourage, ask. Suggest đi với V-ing hoặc mệnh đề that. Chọn động từ phù hợp giúp truyền đạt đúng ý người nói.", "“You should rest,” the doctor said. → The doctor advised me to rest. He suggested going early.", "Chuyển ba câu trực tiếp sang gián tiếp dùng remind, advise, suggest."],
    ["tag-questions", "Câu hỏi đuôi", "Câu hỏi đuôi dùng để xác nhận thông tin. Câu khẳng định đi với đuôi phủ định và ngược lại; trợ động từ ở đuôi phù hợp với thì của câu. Trường hợp đặc biệt: I am ... , aren't I?; Let's ... , shall we?", "You are a student, aren't you? She didn't come, did she?", "Viết năm câu hỏi đuôi với các thì khác nhau."],
  ],
  history: [
    ["october-revolution", "Cách mạng tháng Mười Nga và Liên Xô", "Cách mạng tháng Mười Nga năm 1917 lật đổ chính phủ lâm thời, thành lập nhà nước Xô viết. Năm 1922, Liên bang Cộng hòa xã hội chủ nghĩa Xô viết (Liên Xô) được thành lập. Liên Xô đạt nhiều thành tựu về công nghiệp, khoa học nhưng cũng có hạn chế; tan rã năm 1991.", "Năm 1961, Liên Xô đưa Gagarin trở thành người đầu tiên bay vào vũ trụ.", "Nêu một thành tựu và một hạn chế của Liên Xô."],
    ["meiji", "Cải cách Minh Trị ở Nhật Bản", "Năm 1868, Thiên hoàng Minh Trị tiến hành cải cách toàn diện: xóa bỏ chế độ phong kiến, phát triển công nghiệp, cải cách giáo dục theo phương Tây và xây dựng quân đội hiện đại. Nhật Bản nhanh chóng trở thành nước công nghiệp và tránh bị biến thành thuộc địa.", "Chế độ giáo dục bắt buộc giúp Nhật Bản có lực lượng lao động có trình độ.", "So sánh cải cách Minh Trị với một đề nghị cải cách ở Việt Nam cuối thế kỉ XIX."],
    ["maritime-sovereignty", "Lịch sử bảo vệ chủ quyền biển đảo", "Các nhà nước Việt Nam đã xác lập và thực thi chủ quyền ở Hoàng Sa, Trường Sa từ nhiều thế kỉ, như tổ chức Hải đội Hoàng Sa đi khảo sát, khai thác. Ngày nay, Việt Nam kiên trì giải quyết tranh chấp bằng biện pháp hòa bình trên cơ sở luật pháp quốc tế.", "Các châu bản triều Nguyễn ghi chép việc cử người ra Hoàng Sa là tư liệu chủ quyền.", "Tìm một tư liệu lịch sử về chủ quyền biển đảo và nêu giá trị của nó."],
  ],
  geography: [
    ["usa-economy", "Kinh tế Hoa Kỳ", "Hoa Kỳ là nền kinh tế có GDP danh nghĩa lớn nhất thế giới, mạnh về dịch vụ, công nghệ cao, tài chính. Nông nghiệp có năng suất cao nhờ cơ giới hóa. Các trung tâm công nghệ như Thung lũng Silicon thu hút nhân lực toàn cầu.", "Nhiều công ty công nghệ lớn có trụ sở tại Hoa Kỳ.", "Nêu ba nhân tố giúp Hoa Kỳ phát triển kinh tế mạnh."],
    ["asean", "Hiệp hội các quốc gia Đông Nam Á (ASEAN)", "ASEAN thành lập ngày 8/8/1967 tại Bangkok. Việt Nam gia nhập ngày 28/7/1995. Năm 2025, Đông Timor được kết nạp, trở thành thành viên thứ 11. ASEAN hợp tác về kinh tế, văn hóa, an ninh, hướng tới cộng đồng gắn kết.", "Các nước ASEAN giảm thuế quan cho nhau, thúc đẩy thương mại khu vực.", "Nêu hai lợi ích Việt Nam có được khi tham gia ASEAN."],
    ["japan", "Nhật Bản: dân số già và công nghệ", "Nhật Bản là quần đảo nhiều núi, thường có động đất, ít tài nguyên khoáng sản. Dân số già hóa nhanh, tỉ lệ người cao tuổi cao, gây thiếu lao động. Nhật Bản mạnh về công nghiệp chế tạo, robot và đầu tư công nghệ để thích ứng.", "Robot được dùng hỗ trợ chăm sóc người cao tuổi ở Nhật Bản.", "Nêu hai giải pháp Nhật Bản có thể dùng để giải quyết thiếu lao động."],
  ],
  informatics: [
    ["sorting", "Thuật toán sắp xếp", "Sắp xếp đưa dãy về thứ tự tăng hoặc giảm. Sắp xếp nổi bọt đổi chỗ hai phần tử liền kề sai thứ tự; sắp xếp chọn tìm phần tử nhỏ nhất đưa lên đầu; sắp xếp chèn chèn từng phần tử vào đúng vị trí. Các thuật toán này có độ phức tạp O(n²) trong trường hợp xấu.", "Sắp xếp chèn cho dãy 5, 2, 4: chèn 2 trước 5 thành 2, 5, 4, rồi chèn 4 được 2, 4, 5.", "Mô tả từng bước sắp xếp nổi bọt dãy 4, 3, 1, 2."],
    ["db-security", "Bảo mật và sao lưu cơ sở dữ liệu", "Bảo mật cơ sở dữ liệu gồm phân quyền truy cập, xác thực người dùng, mã hóa và ghi nhật kí. Sao lưu định kì giúp khôi phục khi có sự cố. Chỉ cấp quyền tối thiểu cần thiết cho mỗi người dùng.", "Giáo viên được sửa điểm, học sinh chỉ được xem điểm của mình.", "Đề xuất phân quyền cho cơ sở dữ liệu thư viện trường: thủ thư, học sinh, quản trị."],
    ["open-source", "Phần mềm nguồn mở và giấy phép", "Phần mềm nguồn mở cho phép xem, sửa và phân phối mã nguồn theo điều kiện của giấy phép. Giấy phép MIT rất thoáng; GPL yêu cầu sản phẩm phái sinh cũng phải công bố mã nguồn theo GPL. Nguồn mở không có nghĩa là không có điều kiện.", "Linux và trình duyệt Firefox là phần mềm nguồn mở.", "Tìm giấy phép của một phần mềm nguồn mở và tóm tắt hai điều kiện."],
  ],
  technology: [
    ["combustion-engine", "Động cơ đốt trong", "Động cơ đốt trong bốn kì hoạt động theo chu trình: nạp, nén, cháy – giãn nở (sinh công) và thải. Chỉ kì cháy – giãn nở sinh công, các kì khác nhờ quán tính bánh đà. Động cơ dùng trong ô tô, xe máy, máy phát điện; cần bảo dưỡng định kì.", "Thay dầu bôi trơn đúng hạn giúp giảm ma sát và mài mòn động cơ.", "Vẽ sơ đồ bốn kì của động cơ và chú thích kì sinh công."],
    ["vehicle-safety", "Ô tô và các hệ thống an toàn", "Ô tô có hệ thống phanh, lái, treo và nhiều thiết bị an toàn như dây an toàn, túi khí, phanh chống bó cứng (ABS). Thắt dây an toàn ở mọi ghế giúp giảm nguy cơ chấn thương. Trẻ em cần ghế phù hợp.", "ABS giúp bánh xe không bị bó cứng, người lái vẫn điều khiển được hướng khi phanh gấp.", "Tìm hiểu cách hoạt động của túi khí và vì sao vẫn cần thắt dây an toàn."],
    ["composites", "Vật liệu composite và vật liệu mới", "Composite là vật liệu kết hợp hai thành phần trở lên: vật liệu nền và vật liệu cốt, tạo tính chất tốt hơn từng thành phần. Ví dụ: bê tông cốt thép, nhựa cốt sợi thủy tinh. Composite nhẹ, bền, dùng trong ô tô, máy bay, thể thao.", "Vợt cầu lông sợi carbon nhẹ và cứng hơn vợt kim loại.", "Kể ba sản phẩm dùng vật liệu composite và ưu điểm của chúng."],
  ],
  civics: [
    ["unemployment", "Tham khảo: thất nghiệp và việc làm", "Thất nghiệp là tình trạng người trong độ tuổi lao động, có khả năng và muốn làm việc nhưng chưa có việc làm. Có thất nghiệp tạm thời, cơ cấu và chu kì. Nâng cao kĩ năng, học tập suốt đời giúp giảm nguy cơ thất nghiệp.", "Tự động hóa có thể khiến một số nghề giảm nhu cầu, tạo thất nghiệp cơ cấu.", "Nêu hai kĩ năng giúp người lao động thích ứng với thay đổi việc làm."],
    ["equality", "Tham khảo: quyền bình đẳng của công dân", "Mọi công dân bình đẳng trước pháp luật về quyền và nghĩa vụ, không phân biệt dân tộc, giới tính, tôn giáo, địa vị. Bình đẳng giới được thể hiện trong học tập, lao động, gia đình. Phân biệt đối xử là vi phạm pháp luật.", "Nam và nữ có quyền ngang nhau trong lựa chọn ngành học.", "Tìm một ví dụ về bình đẳng giới trong trường học."],
    ["business-ethics", "Tham khảo: ý tưởng và đạo đức kinh doanh", "Ý tưởng kinh doanh tốt xuất phát từ nhu cầu thị trường và năng lực của bản thân. Đạo đức kinh doanh gồm trung thực, trách nhiệm với khách hàng, cộng đồng và môi trường. Kinh doanh gian dối có thể bị xử lí theo pháp luật.", "Ghi đúng thành phần, hạn sử dụng trên bao bì là thể hiện trung thực.", "Phác ý tưởng kinh doanh nhỏ ở trường và nêu một nguyên tắc đạo đức."],
  ],
  "physical-education": [
    ["table-tennis", "Bóng bàn: giao bóng và trả bóng", "Khi giao bóng, đặt bóng trên lòng bàn tay mở, tung bóng lên gần như thẳng đứng ít nhất 16 cm, đánh khi bóng rơi xuống; bóng chạm bàn bên mình rồi sang bàn đối phương. Trả bóng cần điều chỉnh mặt vợt, di chuyển chân.", "Mặt vợt mở nhẹ giúp bóng bay qua lưới khi trả bóng thấp.", "Tập giao bóng 20 lần và ghi số lần giao hợp lệ."],
    ["shot-put", "Đẩy tạ: kĩ thuật và an toàn", "Đẩy tạ phối hợp chân, hông, thân và tay. Quả tạ đặt sát cổ, đẩy chứ không ném. Chỉ đẩy khi khu vực phía trước trống và theo hiệu lệnh. Nhặt tạ bằng cách lăn hoặc mang, không ném trả.", "Xoay hông trước khi duỗi tay giúp tăng lực đẩy.", "Quan sát video đẩy tạ và liệt kê ba bước kĩ thuật."],
    ["injury-care", "Phòng tránh và xử lí chấn thương thường gặp", "Chấn thương thường gặp khi tập: bong gân, căng cơ, trầy xước. Phòng tránh bằng khởi động kĩ, tập đúng kĩ thuật, trang phục phù hợp. Khi bị bong gân, ngừng tập, chườm lạnh, băng ép nhẹ, kê cao và đi khám nếu sưng đau nhiều.", "Cổ chân bị lật khi chạy: ngồi nghỉ, chườm đá bọc khăn, không cố chạy tiếp.", "Lập danh sách các bước xử lí ban đầu khi bị bong gân."],
  ],
  music: [
    ["western-classical", "Tham khảo: âm nhạc cổ điển phương Tây", "Âm nhạc cổ điển phương Tây có nhiều thời kì: Baroque (Bach), Cổ điển (Mozart, Haydn), Lãng mạn (Beethoven giai đoạn sau, Chopin). Giao hưởng là tác phẩm lớn cho dàn nhạc, thường có nhiều chương. Nghe nhạc cổ điển, chú ý chủ đề, sự phát triển và tương phản.", "Bản Giao hưởng số 5 của Beethoven mở đầu bằng mô-típ bốn nốt nổi tiếng.", "Nghe một chương giao hưởng và mô tả sự thay đổi sắc thái."],
    ["xoan-then", "Tham khảo: Hát Xoan và Thực hành Then", "Hát Xoan Phú Thọ gắn với tín ngưỡng thờ Hùng Vương, được UNESCO ghi danh năm 2011. Thực hành Then của người Tày, Nùng, Thái gắn với đàn tính, được UNESCO ghi danh năm 2019. Đây là di sản cần được bảo tồn qua truyền dạy và thực hành cộng đồng.", "Đàn tính là nhạc cụ đặc trưng đi cùng lời hát Then.", "Tìm hiểu một di sản âm nhạc được UNESCO ghi danh và vai trò của cộng đồng."],
    ["digital-music", "Tham khảo: âm nhạc số và phần mềm", "Phần mềm sản xuất âm nhạc (DAW) cho phép ghi âm, chỉnh sửa, phối nhiều track. MIDI ghi lại thông tin nốt, không phải âm thanh, nên dễ chỉnh sửa. Dùng mẫu âm thanh cần kiểm tra giấy phép.", "Một bản phối có thể gồm track trống, bass, giai điệu và giọng hát riêng.", "Thử tạo một đoạn nhạc 8 ô nhịp bằng phần mềm miễn phí."],
  ],
  "visual-arts": [
    ["impressionism", "Tham khảo: hội họa Ấn tượng", "Trường phái Ấn tượng (cuối thế kỉ XIX, Pháp) chú trọng ánh sáng và khoảnh khắc, vẽ ngoài trời, nét bút nhanh. Tên gọi xuất phát từ bức “Ấn tượng, mặt trời mọc” của Claude Monet (1872). Màu sắc tươi sáng, đặt cạnh nhau thay vì pha trộn kĩ.", "Monet vẽ nhiều bức về cùng một đống rơm ở các thời điểm ánh sáng khác nhau.", "Vẽ một cảnh ngoài trời trong 15 phút, tập trung vào ánh sáng."],
    ["grid-layout", "Tham khảo: lưới bố cục trong thiết kế đồ họa", "Lưới bố cục chia trang thành các cột, hàng giúp sắp xếp chữ, hình thống nhất. Khoảng trắng giúp nội dung dễ đọc. Thứ bậc thông tin được tạo bằng kích thước, độ đậm, màu và vị trí.", "Tạp chí thường dùng lưới 3 cột để bố trí bài viết và hình ảnh.", "Thiết kế lại một trang thông báo của lớp theo lưới 2 cột."],
    ["animation", "Tham khảo: hoạt hình và đồ họa chuyển động", "Hoạt hình tạo ảo giác chuyển động bằng chuỗi hình liên tiếp. Nguyên lí nén – giãn và chuyển động chậm dần – nhanh dần giúp chuyển động tự nhiên. Có thể bắt đầu bằng hoạt hình lật trang hoặc phần mềm miễn phí.", "Quả bóng nảy bị nén khi chạm đất và giãn khi bay lên.", "Làm hoạt hình lật trang 12 hình về quả bóng nảy."],
  ],
  "national-defense": [
    ["national-security", "Bảo vệ an ninh quốc gia và trật tự an toàn xã hội", "An ninh quốc gia là sự ổn định, phát triển bền vững của chế độ và sự bất khả xâm phạm độc lập, chủ quyền. Trật tự an toàn xã hội là trạng thái xã hội ổn định, có kỉ cương. Công dân có trách nhiệm chấp hành pháp luật, phát hiện và báo cáo hành vi vi phạm.", "Phong trào toàn dân bảo vệ an ninh Tổ quốc huy động người dân tham gia giữ gìn trật tự khu dân cư.", "Nêu hai việc học sinh có thể làm để góp phần giữ trật tự an toàn ở trường."],
    ["online-fraud", "Phòng, chống lừa đảo qua mạng", "Các hình thức lừa đảo phổ biến: giả danh cơ quan chức năng, việc nhẹ lương cao, trúng thưởng, mượn tiền qua tài khoản bị chiếm. Không chuyển tiền, không cung cấp mã OTP, xác minh qua kênh chính thức. Báo công an khi bị lừa đảo.", "Cuộc gọi tự xưng công an yêu cầu chuyển tiền để “xác minh” là lừa đảo.", "Lập danh sách năm dấu hiệu nhận biết tin nhắn lừa đảo."],
    ["bandaging", "Kĩ thuật băng bó và chuyển thương", "Băng bó giúp cầm máu, bảo vệ vết thương và cố định xương gãy. Băng vừa chặt, không quá chặt làm tím đầu chi. Không di chuyển người nghi chấn thương cột sống trừ khi có nguy hiểm trước mắt; gọi 115 và chờ hỗ trợ chuyên môn.", "Nẹp cố định cẳng tay gãy cần qua cả khớp trên và khớp dưới chỗ gãy.", "Thực hành băng cổ tay cho bạn dưới sự hướng dẫn của giáo viên."],
  ],
  "career-experience": [
    ["project-teamwork", "Làm việc nhóm trong dự án", "Dự án nhóm hiệu quả cần mục tiêu chung, phân công rõ, mốc thời gian và kênh trao đổi. Họp ngắn định kì để cập nhật tiến độ. Giải quyết bất đồng bằng lắng nghe, dựa trên dữ liệu và mục tiêu chung.", "Bảng phân công ghi rõ ai làm gì, hạn chót và sản phẩm cần nộp.", "Lập kế hoạch dự án nhóm 4 tuần với phân công và mốc thời gian."],
    ["university-majors", "Tìm hiểu ngành học và nghề tương ứng", "Một ngành học có thể dẫn đến nhiều nghề và một nghề có thể đến từ nhiều ngành. Tìm hiểu chương trình đào tạo, môn học, cơ hội việc làm qua website chính thức của trường. Kết hợp sở thích, năng lực và điều kiện gia đình.", "Ngành Công nghệ thông tin có thể dẫn đến nghề lập trình, kiểm thử, quản trị mạng.", "Chọn hai ngành học, so sánh môn học chính và nghề nghiệp liên quan."],
    ["professional-ethics", "Đạo đức nghề nghiệp", "Đạo đức nghề nghiệp là chuẩn mực hành xử trong công việc: trung thực, trách nhiệm, tôn trọng, bảo mật thông tin. Vi phạm có thể gây hại cho người khác và uy tín nghề. Mỗi nghề có quy tắc đạo đức riêng.", "Nhân viên y tế phải giữ bí mật thông tin bệnh nhân.", "Chọn một nghề và nêu hai quy tắc đạo đức quan trọng."],
  ],
};
