export const subjects = [
  {
    id: "math",
    name: "Toán học",
    shortName: "Toán",
    category: "TƯ DUY & CON SỐ",
    color: "blue",
    symbol: "∑",
    description: "Giải đố nhanh, tư duy thật chất!",
    topics: [
      {
        id: "algebra",
        title: "Phương trình vui",
        description: "Tìm x và mở khóa bí mật",
        level: "CƠ BẢN",
        duration: "5 phút",
        questions: [
          {
            prompt: "Nếu 3x + 5 = 20, giá trị của x là bao nhiêu?",
            answers: ["3", "5", "8", "15"],
            correct: 1,
            explanation: "Trừ 5 ở hai vế, ta có 3x = 15. Chia cho 3, vậy x = 5.",
          },
          {
            prompt: "Một chiếc áo giá 240.000đ đang được giảm 25%. Giá mới là bao nhiêu?",
            answers: ["60.000đ", "160.000đ", "180.000đ", "215.000đ"],
            correct: 2,
            explanation: "Số tiền giảm là 240.000 × 25% = 60.000đ. Giá mới còn 180.000đ.",
          },
          {
            prompt: "Rút gọn biểu thức 2(a + 3) − a.",
            answers: ["a + 3", "a + 6", "2a + 3", "3a + 6"],
            correct: 1,
            explanation: "Phân phối 2 vào ngoặc rồi thu gọn: 2a + 6 − a = a + 6.",
          },
          {
            prompt: "Nếu y = 4, giá trị của 2y² là bao nhiêu?",
            answers: ["16", "24", "32", "64"],
            correct: 2,
            explanation: "Thay y = 4: 2 × 4² = 2 × 16 = 32.",
          },
          {
            prompt: "Một số khi nhân với 6 rồi cộng 2 thì bằng 32. Số đó là?",
            answers: ["4", "5", "6", "7"],
            correct: 1,
            explanation: "Gọi số cần tìm là x: 6x + 2 = 32 nên 6x = 30 và x = 5.",
          },
        ],
      },
      {
        id: "geometry",
        title: "Hình học không gian",
        description: "Khám phá hình khối quanh ta",
        level: "KHÁM PHÁ",
        duration: "5 phút",
        questions: [
          {
            prompt: "Một hình lập phương có bao nhiêu mặt?",
            answers: ["4 mặt", "6 mặt", "8 mặt", "12 mặt"],
            correct: 1,
            explanation: "Hình lập phương có 6 mặt vuông bằng nhau, 8 đỉnh và 12 cạnh.",
          },
          {
            prompt: "Diện tích hình tròn bán kính 3 cm là bao nhiêu?",
            answers: ["6π cm²", "9π cm²", "12π cm²", "18π cm²"],
            correct: 1,
            explanation: "Diện tích hình tròn là πr². Với r = 3, ta được 9π cm².",
          },
          {
            prompt: "Tổng ba góc trong một tam giác bằng bao nhiêu?",
            answers: ["90°", "180°", "270°", "360°"],
            correct: 1,
            explanation: "Tổng số đo các góc trong của mọi tam giác luôn bằng 180°.",
          },
          {
            prompt: "Hình hộp chữ nhật có bao nhiêu cạnh?",
            answers: ["8 cạnh", "10 cạnh", "12 cạnh", "16 cạnh"],
            correct: 2,
            explanation: "Có 4 cạnh ở mặt trên, 4 cạnh ở mặt dưới và 4 cạnh đứng: tổng cộng 12.",
          },
          {
            prompt: "Một hình vuông có cạnh dài 7 cm. Chu vi là bao nhiêu?",
            answers: ["14 cm", "21 cm", "28 cm", "49 cm"],
            correct: 2,
            explanation: "Chu vi hình vuông bằng 4 lần độ dài cạnh: 4 × 7 = 28 cm.",
          },
        ],
      },
      {
        id: "fractions",
        title: "Phân số tốc độ",
        description: "Tính nhẩm và về đích",
        level: "TĂNG TỐC",
        duration: "5 phút",
        questions: [
          {
            prompt: "Phân số nào bằng 3/4?",
            answers: ["6/10", "9/12", "12/20", "15/24"],
            correct: 1,
            explanation: "Nhân cả tử và mẫu của 3/4 với 3 ta được 9/12.",
          },
          {
            prompt: "Tính 1/2 + 1/4.",
            answers: ["1/6", "2/6", "2/4", "3/4"],
            correct: 3,
            explanation: "Quy đồng 1/2 thành 2/4, rồi cộng 2/4 + 1/4 = 3/4.",
          },
          {
            prompt: "2/3 của 18 là bao nhiêu?",
            answers: ["6", "9", "12", "15"],
            correct: 2,
            explanation: "18 chia 3 được 6; 6 nhân 2 được 12.",
          },
          {
            prompt: "Rút gọn phân số 15/25.",
            answers: ["2/5", "3/5", "3/4", "5/3"],
            correct: 1,
            explanation: "Chia cả tử và mẫu cho ước chung lớn nhất là 5: 15/25 = 3/5.",
          },
          {
            prompt: "Viết 0,2 dưới dạng phân số tối giản.",
            answers: ["1/2", "1/4", "1/5", "2/5"],
            correct: 2,
            explanation: "0,2 = 2/10 = 1/5 sau khi rút gọn.",
          },
        ],
      },
    ],
  },
  {
    id: "science",
    name: "Khoa học",
    shortName: "Khoa học",
    category: "KHÁM PHÁ & THÍ NGHIỆM",
    color: "green",
    symbol: "✳",
    description: "Hỏi “tại sao?” và tìm câu trả lời.",
    topics: [
      {
        id: "physics",
        title: "Vật lý quanh ta",
        description: "Những quy luật thú vị",
        level: "KHÁM PHÁ",
        duration: "5 phút",
        questions: [
          {
            prompt: "Ánh sáng Mặt Trời đến Trái Đất mất khoảng bao lâu?",
            answers: ["8 giây", "8 phút", "8 giờ", "8 ngày"],
            correct: 1,
            explanation: "Ánh sáng đi khoảng 150 triệu km từ Mặt Trời đến Trái Đất trong gần 8 phút 20 giây.",
          },
          {
            prompt: "Đơn vị đo cường độ dòng điện là gì?",
            answers: ["Vôn (V)", "Oát (W)", "Ampe (A)", "Jun (J)"],
            correct: 2,
            explanation: "Ampe, ký hiệu A, là đơn vị đo cường độ dòng điện trong hệ SI.",
          },
          {
            prompt: "Âm thanh không thể truyền qua môi trường nào?",
            answers: ["Không khí", "Nước", "Thép", "Chân không"],
            correct: 3,
            explanation: "Âm thanh cần môi trường vật chất để truyền, vì vậy không truyền được trong chân không.",
          },
          {
            prompt: "Lực nào giữ các hành tinh chuyển động quanh Mặt Trời?",
            answers: ["Lực ma sát", "Lực đàn hồi", "Lực hấp dẫn", "Lực đẩy"],
            correct: 2,
            explanation: "Lực hấp dẫn giữa Mặt Trời và các hành tinh giữ chúng trên quỹ đạo.",
          },
          {
            prompt: "Nhiệt độ nước sôi ở áp suất khí quyển tiêu chuẩn là bao nhiêu?",
            answers: ["0°C", "50°C", "100°C", "150°C"],
            correct: 2,
            explanation: "Ở áp suất khí quyển tiêu chuẩn, nước sôi ở 100°C.",
          },
        ],
      },
      {
        id: "biology",
        title: "Bí mật cơ thể",
        description: "Từ tế bào đến hệ cơ quan",
        level: "CƠ BẢN",
        duration: "5 phút",
        questions: [
          {
            prompt: "Cơ quan nào bơm máu đi khắp cơ thể?",
            answers: ["Phổi", "Gan", "Tim", "Thận"],
            correct: 2,
            explanation: "Tim co bóp nhịp nhàng để bơm máu đến phổi và các cơ quan trong cơ thể.",
          },
          {
            prompt: "Cây xanh hấp thụ khí nào khi quang hợp?",
            answers: ["Ôxi", "Nitơ", "Hiđrô", "Cacbon điôxít"],
            correct: 3,
            explanation: "Trong quang hợp, cây hấp thụ CO₂ và nước để tạo chất hữu cơ, đồng thời thải ôxi.",
          },
          {
            prompt: "Đơn vị cấu tạo và chức năng cơ bản của sự sống là gì?",
            answers: ["Mô", "Cơ quan", "Tế bào", "Hệ cơ quan"],
            correct: 2,
            explanation: "Tế bào là đơn vị cấu tạo và chức năng cơ bản của mọi cơ thể sống.",
          },
          {
            prompt: "Xương nào dài nhất trong cơ thể người?",
            answers: ["Xương cánh tay", "Xương đùi", "Xương sườn", "Xương chày"],
            correct: 1,
            explanation: "Xương đùi là xương dài và khỏe nhất trong bộ xương người.",
          },
          {
            prompt: "Cơ quan nào giúp trao đổi khí khi chúng ta hít thở?",
            answers: ["Dạ dày", "Phổi", "Tim", "Não"],
            correct: 1,
            explanation: "Ở phổi, ôxi đi vào máu và cacbon điôxít được đưa ra ngoài khi thở.",
          },
        ],
      },
      {
        id: "chemistry",
        title: "Phòng thí nghiệm",
        description: "Nguyên tố và phản ứng",
        level: "TĂNG TỐC",
        duration: "5 phút",
        questions: [
          {
            prompt: "Ký hiệu hóa học của vàng là gì?",
            answers: ["Ag", "Au", "Fe", "Cu"],
            correct: 1,
            explanation: "Vàng có ký hiệu Au, bắt nguồn từ tên Latin aurum.",
          },
          {
            prompt: "Nước tinh khiết có công thức hóa học nào?",
            answers: ["CO₂", "O₂", "H₂O", "NaCl"],
            correct: 2,
            explanation: "Mỗi phân tử nước gồm hai nguyên tử hiđrô và một nguyên tử ôxi: H₂O.",
          },
          {
            prompt: "Dung dịch có pH nhỏ hơn 7 thường có tính chất gì?",
            answers: ["Axit", "Bazơ", "Trung tính", "Kim loại"],
            correct: 0,
            explanation: "Ở điều kiện thông thường, dung dịch có pH nhỏ hơn 7 là dung dịch axit.",
          },
          {
            prompt: "Khí nào chiếm tỉ lệ lớn nhất trong không khí?",
            answers: ["Ôxi", "Cacbon điôxít", "Nitơ", "Hiđrô"],
            correct: 2,
            explanation: "Nitơ chiếm khoảng 78% thể tích không khí khô.",
          },
          {
            prompt: "Muối ăn có công thức hóa học là gì?",
            answers: ["HCl", "NaOH", "NaCl", "KCl"],
            correct: 2,
            explanation: "Muối ăn thông thường là natri clorua, có công thức NaCl.",
          },
        ],
      },
    ],
  },
];

function createStarterQuestion(prompt, correctAnswer, incorrectAnswers, explanation) {
  return {
    prompt,
    answers: [correctAnswer, ...incorrectAnswers],
    correct: 0,
    explanation,
  };
}

function createStarterTopic(id, title, description, art, questionData) {
  return {
    id,
    title,
    description,
    level: "KHÁM PHÁ",
    duration: "5 phút",
    art,
    questions: questionData.map(([prompt, answer, alternatives, explanation]) =>
      createStarterQuestion(prompt, answer, alternatives, explanation),
    ),
  };
}

const additionalSubjects = [
  {
    id: "literature",
    name: "Ngữ văn",
    shortName: "Văn",
    category: "ĐỌC HIỂU & NGÔN TỪ",
    color: "rose",
    symbol: "文",
    description: "Đọc sâu, cảm nhận hay, viết điều mình nghĩ.",
    topics: [createStarterTopic("literary-reading", "Đọc hiểu văn bản", "Khám phá hình ảnh và ý nghĩa trong văn học", ["Aa", "✍", "文"], [
      ["Từ ngữ nào diễn tả sự vật bằng cách gọi tên sự vật khác có nét tương đồng?", "Ẩn dụ", ["Nhân hóa", "Liệt kê", "Nói quá"], "Ẩn dụ gọi tên sự vật này bằng tên sự vật khác dựa trên nét tương đồng giữa chúng."],
      ["Trong câu “Mặt trời xuống biển như hòn lửa”, tác giả sử dụng biện pháp tu từ nào?", "So sánh", ["Điệp ngữ", "Hoán dụ", "Nói giảm"], "Từ “như” nối hai hình ảnh có nét tương đồng: mặt trời và hòn lửa."],
      ["Nhân vật chính trong một truyện thường là ai?", "Nhân vật giữ vai trò trung tâm của câu chuyện", ["Người chỉ xuất hiện ở phần kết", "Người kể chuyện trong mọi trường hợp", "Nhân vật không có lời thoại"], "Nhân vật chính giữ vai trò trung tâm và thường gắn với các sự việc quan trọng của truyện."],
      ["Tác dụng thường gặp của ngôi kể thứ nhất là gì?", "Tạo cảm giác gần gũi qua lời kể của người trong cuộc", ["Kể được suy nghĩ của mọi nhân vật cùng lúc", "Loại bỏ hoàn toàn cảm xúc", "Chỉ dùng để kể sự việc có thật"], "Ngôi kể thứ nhất thường tạo sự gần gũi, chủ quan qua trải nghiệm của người kể xưng “tôi”."],
      ["Khi nêu nhận xét về một nhân vật, dẫn chứng nào thuyết phục nhất?", "Chi tiết và lời nói cụ thể trong văn bản", ["Một ý kiến không liên quan của người đọc", "Chỉ nhắc lại tên nhân vật", "Một kết luận không kèm căn cứ"], "Nhận xét cần dựa vào chi tiết, hành động hoặc lời nói có trong văn bản."],
    ])],
  },
  {
    id: "english",
    name: "Tiếng Anh",
    shortName: "Anh",
    category: "NGÔN NGỮ & GIAO TIẾP",
    color: "violet",
    symbol: "A",
    description: "Tích lũy từ vựng, tự tin giao tiếp.",
    topics: [createStarterTopic("english-everyday", "English mỗi ngày", "Ngữ pháp và từ vựng trong tình huống quen thuộc", ["Hi!", "Aa", "ABC"], [
      ["Choose the correct form: “She ___ to school every day.”", "goes", ["go", "going", "went"], "Với chủ ngữ ngôi thứ ba số ít ở thì hiện tại đơn, động từ “go” thêm -es."],
      ["What is the past tense of “buy”?", "bought", ["buyed", "buys", "buying"], "“Buy” là động từ bất quy tắc; dạng quá khứ và quá khứ phân từ là “bought”."],
      ["Which word means “thư viện”?", "library", ["bookshop", "kitchen", "station"], "“Library” có nghĩa là thư viện, nơi mọi người có thể đọc hoặc mượn sách."],
      ["Choose the correct comparison: “A train is ___ than a bicycle.”", "faster", ["fast", "fastest", "more fast"], "So sánh hơn của tính từ ngắn “fast” là “faster”."],
      ["Complete the sentence: “There ___ two windows in my room.”", "are", ["is", "am", "be"], "Dùng “there are” trước danh từ số nhiều “two windows”."],
    ])],
  },
  {
    id: "history",
    name: "Lịch sử",
    shortName: "Sử",
    category: "DÒNG THỜI GIAN & SỰ KIỆN",
    color: "orange",
    symbol: "⌛",
    description: "Kết nối sự kiện hôm qua với hôm nay.",
    topics: [createStarterTopic("vietnam-history", "Dấu mốc Việt Nam", "Những sự kiện quan trọng trong lịch sử hiện đại", ["1945", "⏳", "★"], [
      ["Nước Việt Nam Dân chủ Cộng hòa ra đời vào ngày nào?", "2 tháng 9 năm 1945", ["19 tháng 8 năm 1945", "30 tháng 4 năm 1975", "7 tháng 5 năm 1954"], "Ngày 2/9/1945, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập tại Quảng trường Ba Đình."],
      ["Chiến thắng Điện Biên Phủ kết thúc vào năm nào?", "1954", ["1945", "1968", "1975"], "Chiến dịch Điện Biên Phủ kết thúc thắng lợi ngày 7/5/1954."],
      ["Cách mạng tháng Tám thành công vào năm nào?", "1945", ["1930", "1946", "1954"], "Tháng Tám năm 1945, nhân dân giành chính quyền trên cả nước."],
      ["Đường lối Đổi mới ở Việt Nam được đề ra tại Đại hội VI năm nào?", "1986", ["1975", "1980", "1995"], "Đại hội đại biểu toàn quốc lần thứ VI của Đảng năm 1986 đề ra đường lối Đổi mới."],
      ["Ngày giải phóng miền Nam, thống nhất đất nước là ngày nào?", "30 tháng 4 năm 1975", ["2 tháng 9 năm 1945", "7 tháng 5 năm 1954", "19 tháng 8 năm 1945"], "Ngày 30/4/1975 đánh dấu sự kết thúc chiến tranh và thống nhất đất nước."],
    ])],
  },
  {
    id: "geography",
    name: "Địa lý",
    shortName: "Địa lý",
    category: "BẢN ĐỒ & MÔI TRƯỜNG",
    color: "cyan",
    symbol: "◎",
    description: "Đọc bản đồ, khám phá thiên nhiên và con người.",
    topics: [createStarterTopic("vietnam-geography", "Khám phá địa lý Việt Nam", "Địa hình, khí hậu và vùng kinh tế", ["VN", "🧭", "🌏"], [
      ["Đồng bằng nào nằm ở cực Nam của Việt Nam?", "Đồng bằng sông Cửu Long", ["Đồng bằng sông Hồng", "Đồng bằng Thanh - Nghệ - Tĩnh", "Đồng bằng duyên hải Nam Trung Bộ"], "Đồng bằng sông Cửu Long nằm ở phía Nam, do hệ thống sông Tiền và sông Hậu bồi đắp."],
      ["Đỉnh núi cao nhất Việt Nam là đỉnh nào?", "Phan Xi Păng", ["Bạch Mã", "Ngọc Linh", "Tản Viên"], "Phan Xi Păng thuộc dãy Hoàng Liên Sơn, cao 3.143 m."],
      ["Tây Nguyên nổi tiếng với loại cây công nghiệp nào?", "Cà phê", ["Cây đay", "Cây cói", "Cây dừa nước"], "Tây Nguyên có đất badan rộng lớn và khí hậu phù hợp với cây cà phê."],
      ["Vịnh Hạ Long thuộc tỉnh, thành nào?", "Quảng Ninh", ["Khánh Hòa", "Kiên Giang", "Thanh Hóa"], "Vịnh Hạ Long nằm ở tỉnh Quảng Ninh, thuộc vùng Đông Bắc Việt Nam."],
      ["Gió mùa Đông Bắc thường làm miền Bắc nước ta có thời tiết như thế nào vào mùa đông?", "Lạnh và thường khô ở đầu mùa", ["Nóng quanh năm", "Mưa dông quanh năm", "Lạnh nhưng không bao giờ có mưa phùn"], "Gió mùa Đông Bắc khiến miền Bắc có mùa đông lạnh; đầu mùa thường lạnh khô, cuối mùa thường lạnh ẩm."],
    ])],
  },
  {
    id: "informatics",
    name: "Tin học",
    shortName: "Tin học",
    category: "TƯ DUY SỐ & AN TOÀN",
    color: "indigo",
    symbol: "⌘",
    description: "Tư duy thuật toán, sử dụng công nghệ an toàn.",
    topics: [createStarterTopic("digital-skills", "Công dân số thông thái", "Dữ liệu, thuật toán và an toàn trực tuyến", ["01", "⌘", "✓"], [
      ["Dãy số nhị phân chỉ sử dụng những chữ số nào?", "0 và 1", ["1 và 2", "0 đến 9", "A và B"], "Hệ nhị phân dùng hai chữ số 0 và 1 để biểu diễn dữ liệu."],
      ["Đặc điểm nào giúp mật khẩu an toàn hơn?", "Dài, khó đoán và kết hợp nhiều loại ký tự", ["Dùng ngày sinh để dễ nhớ", "Dùng “123456”", "Dùng chung một mật khẩu ở mọi nơi"], "Mật khẩu dài, khó đoán và khác nhau giữa các tài khoản giúp giảm nguy cơ bị chiếm quyền."],
      ["Thuật toán là gì?", "Một dãy hữu hạn các bước rõ ràng để giải quyết vấn đề", ["Một loại thiết bị lưu trữ", "Một ngôn ngữ chỉ máy tính mới hiểu", "Một trang web tìm kiếm"], "Thuật toán mô tả tuần tự các bước để giải quyết một bài toán hoặc nhiệm vụ."],
      ["Khi nhận liên kết đăng nhập lạ yêu cầu nhập mật khẩu, em nên làm gì?", "Không mở liên kết, kiểm tra với người lớn hoặc đơn vị chính thức", ["Nhập thử mật khẩu để kiểm tra", "Chuyển tiếp cho cả lớp", "Tải mọi tệp đính kèm"], "Liên kết lạ có thể dùng để lừa lấy thông tin; hãy kiểm tra qua kênh chính thức và báo người lớn."],
      ["Phần mềm bảng tính phù hợp nhất để làm việc nào?", "Tính toán và sắp xếp dữ liệu dạng bảng", ["Chỉnh sửa video chuyên nghiệp", "Quản lý thiết bị mạng", "Vẽ mô hình 3D"], "Bảng tính tổ chức dữ liệu theo hàng, cột và hỗ trợ công thức tính toán."],
    ])],
  },
  {
    id: "technology",
    name: "Công nghệ",
    shortName: "Công nghệ",
    category: "THIẾT KẾ & SÁNG TẠO",
    color: "yellow",
    symbol: "⚙",
    description: "Từ ý tưởng đến sản phẩm hữu ích.",
    topics: [createStarterTopic("design-thinking", "Nhà thiết kế sáng tạo", "Quy trình thiết kế và công nghệ quanh ta", ["⚙", "✏", "↗"], [
      ["Bước đầu tiên khi thiết kế một sản phẩm thường là gì?", "Xác định nhu cầu hoặc vấn đề cần giải quyết", ["Trang trí sản phẩm", "Sản xuất hàng loạt ngay", "Chọn màu bao bì"], "Cần hiểu người dùng và vấn đề trước khi đưa ra giải pháp thiết kế."],
      ["Vật liệu nào dẫn điện tốt trong các lựa chọn sau?", "Đồng", ["Cao su", "Thủy tinh", "Gỗ khô"], "Đồng là kim loại dẫn điện tốt và thường được dùng làm lõi dây dẫn."],
      ["Nguồn năng lượng nào có thể tái tạo?", "Ánh sáng Mặt Trời", ["Than đá", "Dầu mỏ", "Khí tự nhiên"], "Năng lượng Mặt Trời được bổ sung liên tục từ tự nhiên và là nguồn năng lượng tái tạo."],
      ["Vì sao nên thử nghiệm mẫu trước khi làm nhiều sản phẩm?", "Để phát hiện vấn đề và cải tiến thiết kế", ["Để tránh phải xác định nhu cầu", "Để bỏ qua ý kiến người dùng", "Để không cần kiểm tra an toàn"], "Thử nghiệm giúp đánh giá mẫu, phát hiện điểm cần sửa trước khi hoàn thiện."],
      ["Thiết bị nào giúp biến điện năng thành ánh sáng trong đèn?", "Bóng đèn", ["Công tắc", "Phích cắm", "Cầu chì"], "Bóng đèn chuyển đổi điện năng thành ánh sáng và một phần nhiệt năng."],
    ])],
  },
  {
    id: "civics",
    name: "GDCD & Kinh tế - Pháp luật",
    shortName: "GDCD / KTPL",
    category: "CÔNG DÂN & CUỘC SỐNG",
    color: "teal",
    symbol: "⚖",
    description: "Hiểu quyền, trách nhiệm và lựa chọn có trách nhiệm.",
    topics: [createStarterTopic("responsible-citizenship", "Công dân có trách nhiệm", "Quyền, nghĩa vụ và kỹ năng kinh tế hằng ngày", ["§", "⚖", "♡"], [
      ["Khi chứng kiến bạn bị bắt nạt, cách ứng xử an toàn và có trách nhiệm là gì?", "Báo người lớn đáng tin cậy và hỗ trợ bạn an toàn", ["Đứng xem và quay video", "Chia sẻ hình ảnh lên mạng", "Tự mình dùng bạo lực để trả đũa"], "Tìm sự hỗ trợ từ giáo viên hoặc người lớn và ưu tiên an toàn của người bị bắt nạt."],
      ["Quy tắc giao thông đường bộ áp dụng với ai?", "Mọi người tham gia giao thông", ["Chỉ người lái ô tô", "Chỉ người trưởng thành", "Chỉ người đi bộ"], "Người đi bộ, người đi xe đạp và người điều khiển phương tiện đều cần tuân thủ quy tắc giao thông."],
      ["Nếu muốn mua một món đồ, bước nào giúp quản lý tiền hợp lý?", "So sánh nhu cầu, giá cả và số tiền mình có", ["Mua ngay món đắt nhất", "Vay tiền mà không xem khả năng trả", "Bỏ qua thông tin sản phẩm"], "Lập kế hoạch và cân đối ngân sách giúp đưa ra quyết định chi tiêu phù hợp."],
      ["Thông tin cá nhân của người khác nên được chia sẻ khi nào?", "Khi có sự đồng ý và lý do phù hợp", ["Bất cứ khi nào thấy thú vị", "Khi đăng lên nhóm đông người", "Khi người khác không biết"], "Tôn trọng quyền riêng tư nghĩa là không tự ý thu thập hoặc phát tán thông tin của người khác."],
      ["Nếu không đồng ý với ý kiến của bạn, cách thảo luận phù hợp là gì?", "Lắng nghe và trình bày quan điểm bằng lý lẽ tôn trọng", ["Công kích cá nhân", "Ngắt lời và chế giễu", "Đăng thông tin riêng tư của bạn"], "Trao đổi bình tĩnh, lắng nghe và nêu lý do giúp giải quyết bất đồng một cách tôn trọng."],
    ])],
  },
  {
    id: "physical-education",
    name: "Giáo dục thể chất",
    shortName: "Thể chất",
    category: "VẬN ĐỘNG & SỨC KHỎE",
    color: "red",
    symbol: "↗",
    description: "Vận động vui, rèn sức bền và tinh thần đồng đội.",
    topics: [createStarterTopic("active-and-healthy", "Vận động khỏe mạnh", "Nguyên tắc luyện tập an toàn và fair play", ["🏃", "⚽", "💪"], [
      ["Vì sao nên khởi động trước khi vận động mạnh?", "Giúp cơ thể chuẩn bị dần và giảm nguy cơ chấn thương", ["Để không cần uống nước", "Để cơ thể mất sức trước", "Để bỏ qua phần luyện tập chính"], "Khởi động làm cơ và tim mạch thích nghi dần với cường độ vận động."],
      ["Khi tập luyện ra nhiều mồ hôi, điều gì giúp cơ thể hoạt động an toàn?", "Uống nước phù hợp và nghỉ khi thấy mệt", ["Cố tập tiếp dù chóng mặt", "Không uống nước cả buổi", "Chỉ uống nước tăng lực"], "Bổ sung nước và nghỉ ngơi khi cơ thể có dấu hiệu quá sức giúp hạn chế mất nước."],
      ["Tinh thần fair play trong thi đấu là gì?", "Tôn trọng luật chơi, đối thủ và đồng đội", ["Thắng bằng mọi cách", "Cố ý làm đối thủ bị thương", "Không chấp nhận quyết định trọng tài"], "Fair play đề cao sự trung thực, tôn trọng luật và tôn trọng những người cùng thi đấu."],
      ["Nếu cảm thấy đau bất thường trong lúc tập, nên làm gì?", "Dừng lại và báo cho giáo viên hoặc người phụ trách", ["Cố tiếp tục với cường độ cao hơn", "Giấu triệu chứng", "Tự ý dùng thuốc của người khác"], "Dừng vận động và báo người có trách nhiệm giúp xử lý sớm, an toàn."],
      ["Để cải thiện sức bền, cách tập nào phù hợp?", "Tăng thời lượng hoặc cường độ từ từ và nghỉ hợp lý", ["Tập hết sức liên tục mỗi ngày", "Không cần ngủ đủ", "Chỉ luyện tập một lần thật lâu"], "Luyện tập tiến triển dần kết hợp nghỉ ngơi giúp cơ thể thích nghi và phục hồi."],
    ])],
  },
  {
    id: "music",
    name: "Âm nhạc",
    shortName: "Âm nhạc",
    category: "GIAI ĐIỆU & NHỊP ĐIỆU",
    color: "pink",
    symbol: "♫",
    description: "Lắng nghe, cảm nhận và sáng tạo giai điệu.",
    topics: [createStarterTopic("music-and-rhythm", "Nhịp điệu vui", "Làm quen với những yếu tố cơ bản của âm nhạc", ["♫", "♪", "♬"], [
      ["Tốc độ nhanh hay chậm của một bản nhạc được gọi là gì?", "Tempo (tốc độ)", ["Cao độ", "Âm sắc", "Hòa âm"], "Tempo cho biết nhịp độ nhanh hay chậm của âm nhạc."],
      ["Cao độ cho biết đặc điểm nào của âm thanh?", "Âm thanh trầm hay bổng", ["Âm thanh dài hay ngắn", "Âm thanh to hay nhỏ", "Nhạc cụ nặng hay nhẹ"], "Cao độ mô tả âm thanh nghe trầm hoặc bổng."],
      ["Nhịp trong âm nhạc giúp người nghe cảm nhận điều gì?", "Sự đều đặn và cách sắp xếp phách", ["Màu sắc của nhạc cụ", "Lời bài hát được viết bằng chữ gì", "Kích thước sân khấu"], "Nhịp tổ chức các phách theo mẫu đều đặn trong bản nhạc."],
      ["Ký hiệu “f” trong bản nhạc thường chỉ cách thể hiện nào?", "Mạnh (forte)", ["Nhẹ (piano)", "Rất chậm", "Lặp lại từ đầu"], "Ký hiệu f là viết tắt của forte, nghĩa là chơi hoặc hát mạnh."],
      ["Hòa tấu là hình thức biểu diễn như thế nào?", "Nhiều nhạc cụ hoặc người biểu diễn cùng phối hợp", ["Một người đọc thầm bản nhạc", "Chỉ có tiếng vỗ tay", "Một nhạc cụ chơi mà không theo nhịp"], "Hòa tấu là sự phối hợp của nhiều nhạc cụ trong cùng một tác phẩm."],
    ])],
  },
  {
    id: "visual-arts",
    name: "Mỹ thuật",
    shortName: "Mỹ thuật",
    category: "HÌNH ẢNH & THIẾT KẾ",
    color: "purple",
    symbol: "◈",
    description: "Quan sát thế giới qua màu sắc, hình khối và đường nét.",
    topics: [createStarterTopic("art-and-design", "Ngôn ngữ tạo hình", "Màu sắc, bố cục và cách quan sát nghệ thuật", ["◈", "🎨", "✿"], [
      ["Ba màu cơ bản trong hội họa truyền thống thường được dạy là gì?", "Đỏ, vàng và xanh lam", ["Đen, trắng và xám", "Cam, tím và xanh lục", "Nâu, hồng và vàng"], "Đỏ, vàng và xanh lam là bộ ba màu cơ bản thường dùng để giới thiệu pha màu trong hội họa."],
      ["Bố cục trong một bức tranh giúp điều gì?", "Sắp xếp các hình ảnh để tạo sự cân đối và hướng nhìn", ["Làm tranh tự động chuyển động", "Thay thế mọi màu sắc", "Quyết định giá tiền của tranh"], "Bố cục tổ chức các yếu tố thị giác để tạo trọng tâm và sự hài hòa."],
      ["Một vật thể hình khối được thể hiện có chiều sâu tốt hơn nhờ yếu tố nào?", "Sáng, tối và bóng đổ", ["Chỉ dùng một đường viền", "Xóa mọi vùng tối", "Đặt vật thể ngoài trang giấy"], "Sáng, tối và bóng đổ gợi tả thể tích và hướng chiếu sáng."],
      ["Màu nào thường tạo cảm giác ấm áp?", "Đỏ cam", ["Xanh lam", "Xanh lục", "Tím xanh"], "Các màu như đỏ, cam và vàng thường được gọi là nhóm màu nóng."],
      ["Khi góp ý sản phẩm nghệ thuật của bạn, cách nào phù hợp?", "Nêu điều mình quan sát được và góp ý cụ thể, tôn trọng", ["Chê bai người làm", "So sánh để làm bạn xấu hổ", "Tự ý sửa sản phẩm của bạn"], "Phản hồi cụ thể, tử tế giúp người sáng tạo có thêm ý tưởng để phát triển."],
    ])],
  },
  {
    id: "national-defense",
    name: "GDQP và An ninh",
    shortName: "QP-AN",
    category: "AN TOÀN & TRÁCH NHIỆM",
    color: "slate",
    symbol: "★",
    description: "Học kỹ năng an toàn và trách nhiệm với cộng đồng.",
    topics: [createStarterTopic("safety-and-community", "An toàn cùng cộng đồng", "Kỹ năng ứng phó và ý thức bảo vệ cộng đồng", ["★", "🛡", "✓"], [
      ["Khi nghe thông báo sơ tán tại trường, em nên làm gì?", "Bình tĩnh làm theo hướng dẫn của giáo viên", ["Chạy ngược lại lấy đồ", "Tách khỏi lớp để quay phim", "Chen lấn để đi trước"], "Giữ bình tĩnh, đi theo lối thoát hiểm và làm theo hướng dẫn của người phụ trách."],
      ["Trong trường hợp khẩn cấp, số điện thoại cứu hỏa ở Việt Nam là số nào?", "114", ["111", "113", "115"], "114 là số điện thoại báo cháy và yêu cầu cứu nạn, cứu hộ; 113 gọi công an, 115 gọi cấp cứu y tế."],
      ["Khi phát hiện vật lạ có dấu hiệu nguy hiểm, cách xử lý an toàn là gì?", "Không chạm vào, tránh xa và báo người lớn hoặc cơ quan chức năng", ["Mang về nhà kiểm tra", "Đá hoặc di chuyển vật đó", "Rủ bạn đến xem gần hơn"], "Không chạm hoặc tự di chuyển vật đáng ngờ; hãy giữ khoảng cách và báo người có trách nhiệm."],
      ["Nếu nhận được tin chưa kiểm chứng về tình huống khẩn cấp, em nên làm gì?", "Kiểm tra thông tin từ cơ quan hoặc kênh chính thức trước khi chia sẻ", ["Chia sẻ ngay để mọi người sợ", "Thêm chi tiết cho hấp dẫn", "Gửi tiếp vào mọi nhóm chat"], "Kiểm chứng thông tin giúp tránh gây hoang mang và lan truyền tin sai."],
      ["Khi gặp người bị nạn, ưu tiên đầu tiên là gì?", "Đảm bảo an toàn cho mình và gọi người có chuyên môn hỗ trợ", ["Tự thực hiện việc vượt quá khả năng", "Tụ tập đông người quanh nạn nhân", "Di chuyển nạn nhân trong mọi trường hợp"], "Hãy tránh tạo thêm nguy hiểm, gọi cấp cứu hoặc người lớn và làm theo hướng dẫn chuyên môn."],
    ])],
  },
  {
    id: "career-experience",
    name: "Trải nghiệm & Hướng nghiệp",
    shortName: "Hướng nghiệp",
    category: "BẢN THÂN & TƯƠNG LAI",
    color: "lime",
    symbol: "✦",
    description: "Hiểu điểm mạnh và khám phá con đường phù hợp.",
    topics: [createStarterTopic("know-yourself", "Khám phá điểm mạnh", "Đặt mục tiêu, hợp tác và tìm hiểu nghề nghiệp", ["🎯", "✦", "↗"], [
      ["Mục tiêu SMART cần có đặc điểm nào?", "Cụ thể và có thể đo lường, phù hợp, thực tế, có thời hạn", ["Không cần xác định điều muốn làm", "Luôn phụ thuộc vào người khác", "Không có mốc thời gian"], "SMART thường gồm: cụ thể, đo lường được, có thể đạt được, phù hợp và có thời hạn."],
      ["Khi làm việc nhóm, cách nào giúp mọi người phối hợp tốt?", "Lắng nghe, phân chia nhiệm vụ rõ ràng và cùng chịu trách nhiệm", ["Để một người làm hết", "Không chia sẻ tiến độ", "Tranh công khi hoàn thành"], "Phân công minh bạch và trao đổi thường xuyên giúp nhóm phối hợp hiệu quả."],
      ["Cách tốt để tìm hiểu một nghề mình quan tâm là gì?", "Tìm nguồn tin đáng tin cậy và hỏi người có kinh nghiệm", ["Chỉ dựa vào một video ngắn", "Chọn nghề theo lời đồn", "Bỏ qua yêu cầu học tập của nghề"], "Kết hợp nguồn tin đáng tin cậy với trao đổi cùng người có kinh nghiệm giúp hiểu công việc thực tế."],
      ["Sau khi nhận góp ý về bài làm, thái độ nào giúp mình tiến bộ?", "Xem xét góp ý phù hợp và thử cải thiện", ["Bỏ qua mọi góp ý", "Xem góp ý là sự công kích", "Không bao giờ thử lại"], "Phản hồi có ích giúp nhận ra điểm mạnh và điều cần luyện tập thêm."],
      ["Khi chưa biết mình thích lĩnh vực nào, bước đầu tiên phù hợp là gì?", "Thử nhiều hoạt động an toàn và ghi nhận điều mình hứng thú", ["Chọn ngẫu nhiên rồi không tìm hiểu", "Nghĩ rằng mình không có điểm mạnh", "Chỉ chọn giống bạn bè"], "Trải nghiệm đa dạng giúp nhận ra sở thích, giá trị và khả năng của bản thân."],
    ])],
  },
];

subjects.push(...additionalSubjects);

export const matchSets = {
  algebra: [
    { term: "3x + 5 = 20", meaning: "Phương trình có nghiệm x = 5", explanation: "Trừ 5 hai vế rồi chia cho 3: x = 5." },
    { term: "Giảm 25% chiếc áo giá 240.000đ", meaning: "Giảm 60.000đ; giá mới 180.000đ", explanation: "25% là một phần tư: giảm 60.000đ, vậy giá mới còn 180.000đ." },
    { term: "2(a + 3) − a", meaning: "a + 6", explanation: "Phân phối 2 rồi thu gọn: 2a + 6 − a = a + 6." },
    { term: "2y² khi y = 4", meaning: "32", explanation: "Thay y = 4: 2 × 4² = 2 × 16 = 32." },
    { term: "6x + 2 = 32", meaning: "x = 5", explanation: "Trừ 2 rồi chia cho 6: x = 30 ÷ 6 = 5." },
  ],
  geometry: [
    { term: "Hình lập phương", meaning: "6 mặt vuông bằng nhau", explanation: "Hình lập phương có 6 mặt, tất cả đều là hình vuông bằng nhau." },
    { term: "Diện tích hình tròn", meaning: "πr²", explanation: "Diện tích hình tròn được tính bằng pi nhân bình phương bán kính." },
    { term: "Tổng ba góc tam giác", meaning: "180°", explanation: "Tổng số đo ba góc trong của mọi tam giác luôn là 180°." },
    { term: "Hình hộp chữ nhật", meaning: "12 cạnh", explanation: "Hình hộp chữ nhật có 4 cạnh trên, 4 cạnh dưới và 4 cạnh đứng." },
    { term: "Chu vi hình vuông cạnh 7 cm", meaning: "28 cm", explanation: "Chu vi bằng 4 lần cạnh: 4 × 7 = 28 cm." },
  ],
  fractions: [
    { term: "Phân số bằng 3/4", meaning: "9/12", explanation: "Nhân cả tử và mẫu của 3/4 với 3 được 9/12." },
    { term: "1/2 + 1/4", meaning: "3/4", explanation: "Quy đồng 1/2 thành 2/4 rồi cộng: 2/4 + 1/4 = 3/4." },
    { term: "2/3 của 18", meaning: "12", explanation: "18 chia 3 được 6; 6 nhân 2 được 12." },
    { term: "Rút gọn 15/25", meaning: "3/5", explanation: "Chia cả tử và mẫu cho ước chung lớn nhất là 5." },
    { term: "0,2 dưới dạng phân số", meaning: "1/5", explanation: "0,2 = 2/10; rút gọn được 1/5." },
  ],
  physics: [
    { term: "Ánh sáng Mặt Trời đến Trái Đất", meaning: "Khoảng 8 phút 20 giây", explanation: "Ánh sáng truyền khoảng 150 triệu km trong gần 8 phút 20 giây." },
    { term: "Cường độ dòng điện", meaning: "Ampe (A)", explanation: "Ampe, ký hiệu A, là đơn vị đo cường độ dòng điện trong hệ SI." },
    { term: "Âm thanh trong chân không", meaning: "Không thể truyền", explanation: "Âm thanh cần môi trường vật chất để truyền, nên không đi qua chân không." },
    { term: "Lực giữ hành tinh quanh Mặt Trời", meaning: "Lực hấp dẫn", explanation: "Lực hấp dẫn giữa Mặt Trời và các hành tinh giữ chúng trên quỹ đạo." },
    { term: "Nhiệt độ sôi của nước tinh khiết", meaning: "100°C ở áp suất tiêu chuẩn", explanation: "Ở áp suất khí quyển tiêu chuẩn, nước sôi tại 100°C." },
  ],
  biology: [
    { term: "Cơ quan bơm máu đi khắp cơ thể", meaning: "Tim", explanation: "Tim co bóp nhịp nhàng để đưa máu đến phổi và các cơ quan." },
    { term: "Khí cây xanh hấp thụ khi quang hợp", meaning: "Cacbon điôxít (CO₂)", explanation: "Cây hấp thụ CO₂ và nước để tạo chất hữu cơ, đồng thời thải ôxi." },
    { term: "Đơn vị cơ bản của sự sống", meaning: "Tế bào", explanation: "Tế bào là đơn vị cấu tạo và chức năng cơ bản của mọi cơ thể sống." },
    { term: "Xương dài nhất cơ thể người", meaning: "Xương đùi", explanation: "Xương đùi là xương dài và khỏe nhất trong bộ xương người." },
    { term: "Cơ quan trao đổi khí khi hô hấp", meaning: "Phổi", explanation: "Tại phổi, ôxi đi vào máu và cacbon điôxít được thải ra." },
  ],
  chemistry: [
    { term: "Ký hiệu hóa học của vàng", meaning: "Au", explanation: "Au bắt nguồn từ tên Latin của vàng là aurum." },
    { term: "Công thức hóa học của nước", meaning: "H₂O", explanation: "Mỗi phân tử nước gồm hai nguyên tử hiđrô và một nguyên tử ôxi." },
    { term: "Dung dịch có pH nhỏ hơn 7", meaning: "Có tính axit", explanation: "Ở điều kiện thông thường, dung dịch có pH nhỏ hơn 7 là axit." },
    { term: "Khí chiếm tỉ lệ lớn nhất trong không khí", meaning: "Nitơ (khoảng 78%)", explanation: "Nitơ chiếm khoảng 78% thể tích không khí khô." },
    { term: "Công thức hóa học của muối ăn", meaning: "NaCl", explanation: "Muối ăn thông thường là natri clorua, có công thức NaCl." },
  ],
};

for (const subject of additionalSubjects) {
  for (const topic of subject.topics) {
    matchSets[topic.id] = topic.questions.map((question) => ({
      term: question.prompt,
      meaning: question.answers[question.correct],
      explanation: question.explanation,
    }));
  }
}
